import type {
  CommerceAcceptanceDraftInput,
  CommerceLegalRuntime,
} from "@voyant-travel/commerce/runtime-port"
import type { VoyantRuntimeHostPrimitives } from "@voyant-travel/core"
import { eq } from "drizzle-orm"

import { contracts } from "./contracts/schema.js"
import { contractsService } from "./contracts/service.js"
import { generateContractPdfForBooking } from "./runtime.js"

/** Legal-owned contract operations consumed by Commerce checkout. */
export function createCommerceLegalRuntime(
  primitives: VoyantRuntimeHostPrimitives,
): CommerceLegalRuntime {
  return {
    async getContract(db, contractId) {
      const [contract] = await db
        .select()
        .from(contracts)
        .where(eq(contracts.id, contractId))
        .limit(1)
      return contract ?? null
    },
    listSignatures: (db, contractId) => contractsService.listSignatures(db, contractId),
    sendContract: (db, contractId, eventBus) =>
      contractsService.sendContract(db, contractId, { eventBus }),
    signContract: (db, contractId, input, eventBus) =>
      contractsService.signContract(db, contractId, input as never, { eventBus }),
    persistAcceptanceDraftContract,
    generateContractPdf: ({ bindings, db, eventBus, bookingId, force }) =>
      generateContractPdfForBooking(primitives, bindings, db, eventBus, bookingId, { force }),
  }
}

async function persistAcceptanceDraftContract(
  db: Parameters<CommerceLegalRuntime["persistAcceptanceDraftContract"]>[0],
  { booking, acceptance, requestMeta }: CommerceAcceptanceDraftInput,
): Promise<void> {
  const template = await contractsService.findTemplateBySlug(db, acceptance.templateSlug)
  if (!template?.currentVersionId) {
    console.warn(
      `[catalog-checkout] persistAcceptanceDraftContract: template "${acceptance.templateSlug}" not found or has no current version; skipping.`,
    )
    return
  }

  const acceptanceMetadata = {
    templateId: acceptance.templateId,
    templateSlug: acceptance.templateSlug,
    acceptedAt: acceptance.acceptedAt,
    acceptedMarketing: acceptance.acceptedMarketing,
    clientIp: requestMeta.clientIp ?? "",
    userAgent: requestMeta.userAgent ?? "",
    renderedHtmlLength: acceptance.renderedHtml.length,
  }
  const existing = (
    await contractsService.listContracts(db, { bookingId: booking.id, limit: 1, offset: 0 })
  ).data[0]

  if (existing) {
    const prior = (existing.metadata as Record<string, unknown> | null) ?? {}
    await contractsService.updateContract(db, existing.id, {
      metadata: { ...prior, acceptance: acceptanceMetadata },
    })
    return
  }

  await contractsService.createContract(db, {
    scope: "customer",
    status: "draft",
    title: `${template.name} — ${booking.bookingNumber}`,
    templateVersionId: template.currentVersionId,
    seriesId: null,
    bookingId: booking.id,
    personId: booking.personId,
    organizationId: booking.organizationId,
    language: template.language,
    variables: {},
    metadata: {
      autoGenerated: true,
      trigger: "storefront.checkout-acceptance",
      acceptance: acceptanceMetadata,
    },
  })
}
