// AUTO-GENERATED by `voyant db schemas --emit` (or `voyant db generate`).
// Source of truth: voyant.config.ts (modules + additionalSchemas + schemas).
// Do not edit by hand — re-run the command to refresh.
export const schema = [
  "../../packages/db/src/schema/index.ts",
  "../../packages/action-ledger/src/schema.ts",
  "../../packages/relationships/src/schema.ts",
  "../../packages/quotes/src/schema.ts",
  "../../packages/identity/src/schema.ts",
  "../../packages/distribution/src/schema.ts",
  "../../packages/inventory/src/schema.ts",
  "../../packages/commerce/src/schema.ts",
  "../../packages/catalog/src/schema.ts",
  "../../packages/bookings/src/schema.ts",
  "../../packages/finance/src/schema.ts",
  "../../packages/operations/src/schema.ts",
  "../../packages/notifications/src/schema.ts",
  "../../packages/flights/src/reference/local-postgres.ts",
  "../../packages/legal/src/schema.ts",
  "../../packages/storefront-verification/src/schema.ts",
  "../../packages/trip-composer/src/schema.ts",
  "../../packages/catalog-authoring/src/schema.ts",
  "../../packages/workflow-runs/src/schema.ts",
  "../../packages/accommodations/src/schema.ts",
  "../../packages/charters/src/schema.ts",
  "../../packages/cruises/src/schema.ts",
  "./src/db/schema.ts",
  "./drizzle.links.generated.ts",
] as const
