import { defineModule, providePort, requirePort } from "@voyant-travel/core/project"

import { identityAccessRuntimePort } from "./identity-access-runtime-port.js"
import { teamManagementRuntimePort } from "./team-management-runtime-port.js"

export const authInvitationsVoyantModule = defineModule({
  id: "@voyant-travel/auth#invitations",
  packageName: "@voyant-travel/auth",
  localId: "auth.invitations",
  provides: { ports: [providePort(identityAccessRuntimePort)] },
  runtimePorts: [requirePort(identityAccessRuntimePort)],
  api: [
    {
      id: "@voyant-travel/auth#invitations.api.admin",
      surface: "admin",
      mount: "invitations",
      resource: "team",
      openapi: { document: "invitations" },
      transactional: true,
      runtime: {
        entry: "@voyant-travel/auth/identity-access-graph-runtime",
        export: "createInvitationsVoyantRuntime",
      },
    },
    {
      id: "@voyant-travel/auth#invitations.api.public",
      surface: "public",
      mount: "invitations",
      anonymous: true,
      openapi: { document: "invitations" },
      transactional: true,
      runtime: {
        entry: "@voyant-travel/auth/identity-access-graph-runtime",
        export: "createInvitationsVoyantRuntime",
      },
    },
  ],
  presentations: [
    {
      id: "@voyant-travel/auth#presentation.local-auth",
      runtime: {
        entry: "@voyant-travel/auth-react/local-auth-routes",
        export: "createLocalAuthRouteContribution",
      },
    },
  ],
  meta: {
    ownership: "package",
    agentTools: {
      posture: "not-applicable",
      rationale:
        "This unit owns public invitation acceptance; staff invitation management is exposed by the guarded auth team runtime.",
    },
  },
})

export const authTeamVoyantModule = defineModule({
  id: "@voyant-travel/auth#team",
  packageName: "@voyant-travel/auth",
  localId: "auth.team",
  provides: { ports: [providePort(teamManagementRuntimePort)] },
  runtimePorts: [requirePort(teamManagementRuntimePort)],
  api: [
    {
      id: "@voyant-travel/auth#team.api.admin",
      surface: "admin",
      mount: "team",
      resource: "team",
      openapi: { document: "team" },
      transactional: true,
      runtime: {
        entry: "@voyant-travel/auth/identity-access-graph-runtime",
        export: "createTeamVoyantRuntime",
      },
    },
  ],
  access: {
    resources: [
      {
        id: "@voyant-travel/auth#access.team",
        resource: "team",
        label: "Team",
        description: "Manage staff team members and their access.",
        wildcard: "explicit-resource",
        actions: [
          {
            action: "read",
            label: "View team",
            description: "View staff team members.",
          },
          {
            action: "write",
            label: "Manage team",
            description: "Invite staff and update roles or access.",
            sensitive: true,
            wildcard: "explicit",
          },
          {
            action: "delete",
            label: "Remove team access",
            description: "Revoke invitations or deactivate staff team members.",
            sensitive: true,
            wildcard: "explicit",
          },
        ],
      },
    ],
  },
  tools: [
    {
      id: "@voyant-travel/auth#team.tool.get-capabilities",
      name: "get_team_management_capabilities",
      runtime: {
        entry: "@voyant-travel/auth/tools",
        export: "getTeamManagementCapabilitiesTool",
      },
      requiredScopes: ["team:read"],
      context: ["teamManagement"],
      risk: "low",
    },
    {
      id: "@voyant-travel/auth#team.tool.list-members",
      name: "list_team_members",
      runtime: { entry: "@voyant-travel/auth/tools", export: "listTeamMembersTool" },
      requiredScopes: ["team:read"],
      context: ["teamManagement"],
      risk: "medium",
    },
    {
      id: "@voyant-travel/auth#team.tool.list-roles",
      name: "list_team_roles",
      runtime: { entry: "@voyant-travel/auth/tools", export: "listTeamRolesTool" },
      requiredScopes: ["team:read"],
      context: ["teamManagement"],
      risk: "low",
    },
    {
      id: "@voyant-travel/auth#team.tool.list-invitations",
      name: "list_team_invitations",
      runtime: { entry: "@voyant-travel/auth/tools", export: "listTeamInvitationsTool" },
      requiredScopes: ["team:read"],
      context: ["teamManagement"],
      risk: "medium",
    },
    {
      id: "@voyant-travel/auth#team.tool.invite-member",
      name: "invite_team_member",
      runtime: { entry: "@voyant-travel/auth/tools", export: "inviteTeamMemberTool" },
      requiredScopes: ["team:write"],
      context: ["teamManagement"],
      risk: "high",
    },
    {
      id: "@voyant-travel/auth#team.tool.revoke-invitation",
      name: "revoke_team_invitation",
      runtime: { entry: "@voyant-travel/auth/tools", export: "revokeTeamInvitationTool" },
      requiredScopes: ["team:delete"],
      context: ["teamManagement"],
      risk: "high",
    },
    {
      id: "@voyant-travel/auth#team.tool.update-member-role",
      name: "update_team_member_role",
      runtime: { entry: "@voyant-travel/auth/tools", export: "updateTeamMemberRoleTool" },
      requiredScopes: ["team:write"],
      context: ["teamManagement"],
      risk: "high",
    },
    {
      id: "@voyant-travel/auth#team.tool.activate-member",
      name: "activate_team_member",
      runtime: { entry: "@voyant-travel/auth/tools", export: "activateTeamMemberTool" },
      requiredScopes: ["team:write"],
      context: ["teamManagement"],
      risk: "high",
    },
    {
      id: "@voyant-travel/auth#team.tool.deactivate-member",
      name: "deactivate_team_member",
      runtime: { entry: "@voyant-travel/auth/tools", export: "deactivateTeamMemberTool" },
      requiredScopes: ["team:delete"],
      context: ["teamManagement"],
      risk: "high",
    },
  ],
  actions: [
    {
      id: "@voyant-travel/auth#team.action.get-capabilities",
      version: "v1",
      kind: "read",
      targetType: "team-capabilities",
      resource: "team",
      action: "read",
      requiredScopes: ["team:read"],
      risk: "low",
      ledger: "optional",
      approval: "never",
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.get-capabilities"] },
    },
    {
      id: "@voyant-travel/auth#team.action.list-members",
      version: "v1",
      kind: "sensitive-read",
      targetType: "team-member",
      resource: "team",
      action: "read",
      requiredScopes: ["team:read"],
      risk: "medium",
      ledger: "required",
      approval: "never",
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.list-members"] },
    },
    {
      id: "@voyant-travel/auth#team.action.list-roles",
      version: "v1",
      kind: "read",
      targetType: "team-role",
      resource: "team",
      action: "read",
      requiredScopes: ["team:read"],
      risk: "low",
      ledger: "optional",
      approval: "never",
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.list-roles"] },
    },
    {
      id: "@voyant-travel/auth#team.action.list-invitations",
      version: "v1",
      kind: "sensitive-read",
      targetType: "team-invitation",
      resource: "team",
      action: "read",
      requiredScopes: ["team:read"],
      risk: "medium",
      ledger: "required",
      approval: "never",
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.list-invitations"] },
    },
    {
      id: "@voyant-travel/auth#team.action.invite-member",
      version: "v1",
      kind: "execute",
      targetType: "team-invitation",
      resource: "team",
      action: "write",
      requiredScopes: ["team:write"],
      risk: "high",
      ledger: "required",
      approval: "required",
      reversible: false,
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.invite-member"] },
    },
    {
      id: "@voyant-travel/auth#team.action.revoke-invitation",
      version: "v1",
      kind: "execute",
      targetType: "team-invitation",
      resource: "team",
      action: "delete",
      requiredScopes: ["team:delete"],
      risk: "high",
      ledger: "required",
      approval: "required",
      reversible: false,
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.revoke-invitation"] },
    },
    {
      id: "@voyant-travel/auth#team.action.update-member-role",
      version: "v1",
      kind: "execute",
      targetType: "team-member",
      resource: "team",
      action: "write",
      requiredScopes: ["team:write"],
      risk: "high",
      ledger: "required",
      approval: "required",
      reversible: true,
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.update-member-role"] },
    },
    {
      id: "@voyant-travel/auth#team.action.activate-member",
      version: "v1",
      kind: "execute",
      targetType: "team-member",
      resource: "team",
      action: "write",
      requiredScopes: ["team:write"],
      risk: "high",
      ledger: "required",
      approval: "required",
      reversible: true,
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.activate-member"] },
    },
    {
      id: "@voyant-travel/auth#team.action.deactivate-member",
      version: "v1",
      kind: "execute",
      targetType: "team-member",
      resource: "team",
      action: "delete",
      requiredScopes: ["team:delete"],
      risk: "high",
      ledger: "required",
      approval: "required",
      reversible: false,
      allowedActorTypes: ["staff"],
      from: { tools: ["@voyant-travel/auth#team.tool.deactivate-member"] },
    },
  ],
  admin: {
    compositionOrder: 5,
    setupSteps: [{ id: "@voyant-travel/auth#setup.team", skippable: true }],
    runtime: {
      entry: "@voyant-travel/auth-react/admin",
      export: "createSelectedAuthTeamAdminExtension",
    },
    copy: [
      {
        id: "@voyant-travel/auth#team.admin.copy",
        namespace: "auth.admin.team",
        fallbackLocale: "en",
        runtime: {
          entry: "@voyant-travel/auth-react/i18n",
          export: "authUiMessageDefinitions",
        },
      },
    ],
    routes: [
      {
        id: "@voyant-travel/auth#team.admin.route",
        path: "/settings/team",
        requiredScopes: ["team:read"],
        runtime: {
          entry: "@voyant-travel/auth-react/admin",
          export: "createSelectedAuthTeamAdminExtension",
        },
      },
    ],
  },
  meta: {
    ownership: "package",
  },
})
