export {
  getFacilitiesQueryOptions,
  getFacilitiesQueryOptions as getPlacesQueryOptions,
  getFacilityFeatureQueryOptions,
  getFacilityFeatureQueryOptions as getPlaceFeatureQueryOptions,
  getFacilityFeaturesQueryOptions,
  getFacilityFeaturesQueryOptions as getPlaceFeaturesQueryOptions,
  getFacilityOperationScheduleQueryOptions,
  getFacilityOperationScheduleQueryOptions as getPlaceOperationScheduleQueryOptions,
  getFacilityOperationSchedulesQueryOptions,
  getFacilityOperationSchedulesQueryOptions as getPlaceOperationSchedulesQueryOptions,
  getFacilityQueryOptions,
  getFacilityQueryOptions as getPlaceQueryOptions,
  getPropertiesQueryOptions,
  getPropertyGroupMemberQueryOptions,
  getPropertyGroupMembersQueryOptions,
  getPropertyGroupQueryOptions,
  getPropertyGroupsQueryOptions,
  getPropertyQueryOptions,
} from "@voyantjs/facilities-react"
