import type { Module } from "@voyant-travel/core"
import type { ApiModule } from "@voyant-travel/hono/module"

import { productsCompatibilityLinkable } from "./linkables.js"
import { productRoutes } from "./routes.js"
import { publicProductRoutes } from "./routes-public.js"

export {
  appendProductMutationLedgerEntry,
  type ProductLedgerMutationAction,
} from "./action-ledger.js"
export { productsBookingExtension } from "./booking-extension.js"
export {
  emitProductContentChanged,
  PRODUCT_CONTENT_CHANGED_EVENT,
  type ProductContentChangedEvent,
} from "./events.js"
export { productLinkable } from "./linkables.js"
export {
  buildProductReadModelDoc,
  invalidateProductReadModel,
  type ProductReadModelQuery,
  type ProductReadModelVariant,
  type ProductReadModelVariantInput,
  type ProductSlugResolution,
  productDocKey,
  productDocQueryFromVariant,
  productDocVariant,
  productSlugMapKey,
  readThroughProductDoc,
  readThroughSlugMapping,
  type WarmProductReadModelInput,
  type WarmProductReadModelResult,
  warmProductReadModel,
} from "./read-model.js"
export type { ProductRoutes } from "./routes.js"
export type { PublicProductRoutes } from "./routes-public.js"
export { publicProductRoutes } from "./routes-public.js"
export { productsService } from "./service.js"
export { catalogProductsService } from "./service-catalog.js"
export { publicProductsService } from "./service-public.js"
export const productsModule: Module = {
  name: "products",
  linkable: productsCompatibilityLinkable,
}

export const productsApiModule: ApiModule = {
  module: productsModule,
  adminRoutes: productRoutes,
  publicRoutes: publicProductRoutes,
}

export {
  type InventoryAuthoringSurface,
  type InventoryInterfaceDescriptor,
  inventoryApiModule,
  inventoryBookingExtension,
  inventoryInterfaceDescriptor,
  inventoryLinkable,
  inventoryModule,
  inventoryProductCompatibilityLinkable,
  inventoryProductLinkable,
  inventoryProductRoutes,
  productsCompatibilityLinkable,
  publicInventoryProductRoutes,
} from "./interface.js"
export type {
  NewOptionUnit,
  NewOptionUnitTranslation,
  NewProduct,
  NewProductActivationSetting,
  NewProductCapability,
  NewProductCategory,
  NewProductDay,
  NewProductDayService,
  NewProductDayTranslation,
  NewProductDeliveryFormat,
  NewProductFaq,
  NewProductFeature,
  NewProductItinerary,
  NewProductLocation,
  NewProductMedia,
  NewProductNote,
  NewProductOption,
  NewProductOptionTranslation,
  NewProductTag,
  NewProductTicketSetting,
  NewProductTranslation,
  NewProductType,
  NewProductVersion,
  NewProductVisibilitySetting,
  OptionUnit,
  OptionUnitTranslation,
  Product,
  ProductActivationSetting,
  ProductCapability,
  ProductCategory,
  ProductDay,
  ProductDayService,
  ProductDayTranslation,
  ProductDeliveryFormat,
  ProductFaq,
  ProductFeature,
  ProductItinerary,
  ProductLocation,
  ProductMedia,
  ProductNote,
  ProductOption,
  ProductOptionTranslation,
  ProductTag,
  ProductTicketSetting,
  ProductTranslation,
  ProductType,
  ProductVersion,
  ProductVisibilitySetting,
} from "./schema.js"
export {
  destinations,
  destinationTranslations,
  optionUnits,
  optionUnitTranslations,
  productActivationSettings,
  productCapabilities,
  productCategories,
  productCategoryProducts,
  productDayServices,
  productDays,
  productDayTranslations,
  productDeliveryFormats,
  productDestinations,
  productFaqs,
  productFeatures,
  productItineraries,
  productLocations,
  productMedia,
  productMediaTypeEnum,
  productNotes,
  productOptions,
  productOptionTranslations,
  products,
  productTagProducts,
  productTags,
  productTicketSettings,
  productTranslations,
  productTypes,
  productVersions,
  productVisibilitySettings,
} from "./schema.js"
export {
  duplicateItinerarySchema,
  insertDaySchema,
  insertDayServiceSchema,
  insertItinerarySchema,
  insertOptionUnitSchema,
  insertOptionUnitTranslationSchema,
  insertProductActivationSettingSchema,
  insertProductCapabilitySchema,
  insertProductCategorySchema,
  insertProductDayTranslationSchema,
  insertProductDeliveryFormatSchema,
  insertProductFaqSchema,
  insertProductFeatureSchema,
  insertProductLocationSchema,
  insertProductMediaSchema,
  insertProductNoteSchema,
  insertProductOptionSchema,
  insertProductOptionTranslationSchema,
  insertProductSchema,
  insertProductTagSchema,
  insertProductTicketSettingSchema,
  insertProductTranslationSchema,
  insertProductTypeSchema,
  insertProductVisibilitySettingSchema,
  insertVersionSchema,
  optionUnitListQuerySchema,
  optionUnitTranslationListQuerySchema,
  productActivationSettingListQuerySchema,
  productCapabilityListQuerySchema,
  productCategoryListQuerySchema,
  productDeliveryFormatListQuerySchema,
  productFaqListQuerySchema,
  productFeatureListQuerySchema,
  productListQuerySchema,
  productLocationListQuerySchema,
  productMediaListQuerySchema,
  productOptionListQuerySchema,
  productOptionTranslationListQuerySchema,
  productTagListQuerySchema,
  productTicketSettingListQuerySchema,
  productTranslationListQuerySchema,
  productTypeListQuerySchema,
  productVisibilitySettingListQuerySchema,
  reorderProductMediaSchema,
  selectProductSchema,
  setProductOpenGraphMediaSchema,
  updateDaySchema,
  updateDayServiceSchema,
  updateItinerarySchema,
  updateOptionUnitSchema,
  updateOptionUnitTranslationSchema,
  updateProductActivationSettingSchema,
  updateProductCapabilitySchema,
  updateProductCategorySchema,
  updateProductDayTranslationSchema,
  updateProductDeliveryFormatSchema,
  updateProductFaqSchema,
  updateProductFeatureSchema,
  updateProductLocationSchema,
  updateProductMediaSchema,
  updateProductOptionSchema,
  updateProductOptionTranslationSchema,
  updateProductSchema,
  updateProductTagSchema,
  updateProductTicketSettingSchema,
  updateProductTranslationSchema,
  updateProductTypeSchema,
  updateProductVisibilitySettingSchema,
  upsertProductBrochureSchema,
} from "./validation.js"
export type {
  CatalogSearchDocument,
  CatalogSearchDocumentListQuery,
  CatalogSearchDocumentListResponse,
  LocalizedCatalogProductDetail,
  LocalizedCatalogProductSummary,
} from "./validation-catalog.js"
export {
  catalogSearchDocumentListQuerySchema,
  catalogSearchDocumentListResponseSchema,
  catalogSearchDocumentSchema,
  localizedCatalogProductDetailSchema,
  localizedCatalogProductSummarySchema,
} from "./validation-catalog.js"
export {
  publicCatalogDestinationListQuerySchema,
  publicCatalogDestinationListResponseSchema,
  publicCatalogDestinationSchema,
} from "./validation-public.js"
