import type { Module } from "@voyantjs/core"

export const commerceModule: Module = {
  name: "commerce",
}

export {
  CommercialDecisionError,
  createCommerceAdapterRegistry,
  createCommercialDecisionEvaluator,
  evaluateCommercialDecision,
  recordCommercialSnapshot,
} from "./interface.js"
export type {
  CommercialAdapterHandle,
  CommercialAdapterRegistrationKind,
  CommercialAvailabilityFact,
  CommercialBuyerRef,
  CommercialChannelRef,
  CommercialCurrencyCode,
  CommercialDecision,
  CommercialDecisionErrorCode,
  CommercialDecisionEvaluationContext,
  CommercialDecisionEvaluator,
  CommercialDecisionInput,
  CommercialDecisionReason,
  CommercialDecisionStatus,
  CommercialDecisionTrace,
  CommercialDecisionTraceOutcome,
  CommercialDecisionTraceSource,
  CommercialFxFact,
  CommercialItemRef,
  CommercialJson,
  CommercialMarketRef,
  CommercialMoney,
  CommercialParty,
  CommercialPriceAvailabilityAdapter,
  CommercialPriceAvailabilityResult,
  CommercialPricingComponent,
  CommercialPricingFacts,
  CommercialPromotionFact,
  CommercialPromotionFacts,
  CommercialProviderHandle,
  CommercialSellabilityFact,
  CommercialSnapshotRecord,
  CommercialSnapshotRepository,
  CommercialSnapshotTarget,
  CommercialSnapshotWriteInput,
  EvaluateCommercialDecision,
} from "./types.js"
