import "./pricing-assignment/age.suite.js"
import "./pricing-assignment/draft-person-priced.suite.js"
import "./pricing-assignment/draft-accommodation.suite.js"
import "./pricing-assignment/extras.suite.js"
import "./pricing-assignment/travelers-to-rows.suite.js"
import "./pricing-assignment/verify.suite.js"
