// Generated by scripts/generate-ui-geography-data.mjs. Do not edit by hand.

export const countries = [
  {
    "name": "Afghanistan",
    "code": "AF"
  },
  {
    "name": "Åland Islands",
    "code": "AX"
  },
  {
    "name": "Albania",
    "code": "AL"
  },
  {
    "name": "Algeria",
    "code": "DZ"
  },
  {
    "name": "American Samoa",
    "code": "AS"
  },
  {
    "name": "Andorra",
    "code": "AD"
  },
  {
    "name": "Angola",
    "code": "AO"
  },
  {
    "name": "Anguilla",
    "code": "AI"
  },
  {
    "name": "Antarctica",
    "code": "AQ"
  },
  {
    "name": "Antigua and Barbuda",
    "code": "AG"
  },
  {
    "name": "Argentina",
    "code": "AR"
  },
  {
    "name": "Armenia",
    "code": "AM"
  },
  {
    "name": "Aruba",
    "code": "AW"
  },
  {
    "name": "Australia",
    "code": "AU"
  },
  {
    "name": "Austria",
    "code": "AT"
  },
  {
    "name": "Azerbaijan",
    "code": "AZ"
  },
  {
    "name": "Bahamas",
    "code": "BS"
  },
  {
    "name": "Bahrain",
    "code": "BH"
  },
  {
    "name": "Bangladesh",
    "code": "BD"
  },
  {
    "name": "Barbados",
    "code": "BB"
  },
  {
    "name": "Belarus",
    "code": "BY"
  },
  {
    "name": "Belgium",
    "code": "BE"
  },
  {
    "name": "Belize",
    "code": "BZ"
  },
  {
    "name": "Benin",
    "code": "BJ"
  },
  {
    "name": "Bermuda",
    "code": "BM"
  },
  {
    "name": "Bhutan",
    "code": "BT"
  },
  {
    "name": "Bolivia",
    "code": "BO"
  },
  {
    "name": "Bosnia and Herzegovina",
    "code": "BA"
  },
  {
    "name": "Botswana",
    "code": "BW"
  },
  {
    "name": "Bouvet Island",
    "code": "BV"
  },
  {
    "name": "Brazil",
    "code": "BR"
  },
  {
    "name": "British Indian Ocean Territory",
    "code": "IO"
  },
  {
    "name": "Brunei Darussalam",
    "code": "BN"
  },
  {
    "name": "Bulgaria",
    "code": "BG"
  },
  {
    "name": "Burkina Faso",
    "code": "BF"
  },
  {
    "name": "Burundi",
    "code": "BI"
  },
  {
    "name": "Cambodia",
    "code": "KH"
  },
  {
    "name": "Cameroon",
    "code": "CM"
  },
  {
    "name": "Canada",
    "code": "CA"
  },
  {
    "name": "Cape Verde",
    "code": "CV"
  },
  {
    "name": "Cayman Islands",
    "code": "KY"
  },
  {
    "name": "Central African Republic",
    "code": "CF"
  },
  {
    "name": "Chad",
    "code": "TD"
  },
  {
    "name": "Chile",
    "code": "CL"
  },
  {
    "name": "China",
    "code": "CN"
  },
  {
    "name": "Christmas Island",
    "code": "CX"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "code": "CC"
  },
  {
    "name": "Colombia",
    "code": "CO"
  },
  {
    "name": "Comoros",
    "code": "KM"
  },
  {
    "name": "Congo",
    "code": "CG"
  },
  {
    "name": "Congo, The Democratic Republic of the",
    "code": "CD"
  },
  {
    "name": "Cook Islands",
    "code": "CK"
  },
  {
    "name": "Costa Rica",
    "code": "CR"
  },
  {
    "name": "Cote D'Ivoire",
    "code": "CI"
  },
  {
    "name": "Croatia",
    "code": "HR"
  },
  {
    "name": "Cuba",
    "code": "CU"
  },
  {
    "name": "Cyprus",
    "code": "CY"
  },
  {
    "name": "Czech Republic",
    "code": "CZ"
  },
  {
    "name": "Denmark",
    "code": "DK"
  },
  {
    "name": "Djibouti",
    "code": "DJ"
  },
  {
    "name": "Dominica",
    "code": "DM"
  },
  {
    "name": "Dominican Republic",
    "code": "DO"
  },
  {
    "name": "Ecuador",
    "code": "EC"
  },
  {
    "name": "Egypt",
    "code": "EG"
  },
  {
    "name": "El Salvador",
    "code": "SV"
  },
  {
    "name": "Equatorial Guinea",
    "code": "GQ"
  },
  {
    "name": "Eritrea",
    "code": "ER"
  },
  {
    "name": "Estonia",
    "code": "EE"
  },
  {
    "name": "Ethiopia",
    "code": "ET"
  },
  {
    "name": "Falkland Islands (Malvinas)",
    "code": "FK"
  },
  {
    "name": "Faroe Islands",
    "code": "FO"
  },
  {
    "name": "Fiji",
    "code": "FJ"
  },
  {
    "name": "Finland",
    "code": "FI"
  },
  {
    "name": "France",
    "code": "FR"
  },
  {
    "name": "French Guiana",
    "code": "GF"
  },
  {
    "name": "French Polynesia",
    "code": "PF"
  },
  {
    "name": "French Southern Territories",
    "code": "TF"
  },
  {
    "name": "Gabon",
    "code": "GA"
  },
  {
    "name": "Gambia",
    "code": "GM"
  },
  {
    "name": "Georgia",
    "code": "GE"
  },
  {
    "name": "Germany",
    "code": "DE"
  },
  {
    "name": "Ghana",
    "code": "GH"
  },
  {
    "name": "Gibraltar",
    "code": "GI"
  },
  {
    "name": "Greece",
    "code": "GR"
  },
  {
    "name": "Greenland",
    "code": "GL"
  },
  {
    "name": "Grenada",
    "code": "GD"
  },
  {
    "name": "Guadeloupe",
    "code": "GP"
  },
  {
    "name": "Guam",
    "code": "GU"
  },
  {
    "name": "Guatemala",
    "code": "GT"
  },
  {
    "name": "Guernsey",
    "code": "GG"
  },
  {
    "name": "Guinea",
    "code": "GN"
  },
  {
    "name": "Guinea-Bissau",
    "code": "GW"
  },
  {
    "name": "Guyana",
    "code": "GY"
  },
  {
    "name": "Haiti",
    "code": "HT"
  },
  {
    "name": "Heard Island and Mcdonald Islands",
    "code": "HM"
  },
  {
    "name": "Holy See (Vatican City State)",
    "code": "VA"
  },
  {
    "name": "Honduras",
    "code": "HN"
  },
  {
    "name": "Hong Kong",
    "code": "HK"
  },
  {
    "name": "Hungary",
    "code": "HU"
  },
  {
    "name": "Iceland",
    "code": "IS"
  },
  {
    "name": "India",
    "code": "IN"
  },
  {
    "name": "Indonesia",
    "code": "ID"
  },
  {
    "name": "Iran, Islamic Republic Of",
    "code": "IR"
  },
  {
    "name": "Iraq",
    "code": "IQ"
  },
  {
    "name": "Ireland",
    "code": "IE"
  },
  {
    "name": "Isle of Man",
    "code": "IM"
  },
  {
    "name": "Israel",
    "code": "IL"
  },
  {
    "name": "Italy",
    "code": "IT"
  },
  {
    "name": "Jamaica",
    "code": "JM"
  },
  {
    "name": "Japan",
    "code": "JP"
  },
  {
    "name": "Jersey",
    "code": "JE"
  },
  {
    "name": "Jordan",
    "code": "JO"
  },
  {
    "name": "Kazakhstan",
    "code": "KZ"
  },
  {
    "name": "Kenya",
    "code": "KE"
  },
  {
    "name": "Kiribati",
    "code": "KI"
  },
  {
    "name": "Korea, Democratic People’s Republic of",
    "code": "KP"
  },
  {
    "name": "Korea, Republic of",
    "code": "KR"
  },
  {
    "name": "Kuwait",
    "code": "KW"
  },
  {
    "name": "Kyrgyzstan",
    "code": "KG"
  },
  {
    "name": "Lao People’s Democratic Republic",
    "code": "LA"
  },
  {
    "name": "Latvia",
    "code": "LV"
  },
  {
    "name": "Lebanon",
    "code": "LB"
  },
  {
    "name": "Lesotho",
    "code": "LS"
  },
  {
    "name": "Liberia",
    "code": "LR"
  },
  {
    "name": "Libyan Arab Jamahiriya",
    "code": "LY"
  },
  {
    "name": "Liechtenstein",
    "code": "LI"
  },
  {
    "name": "Lithuania",
    "code": "LT"
  },
  {
    "name": "Luxembourg",
    "code": "LU"
  },
  {
    "name": "Macao",
    "code": "MO"
  },
  {
    "name": "Macedonia, The Former Yugoslav Republic of",
    "code": "MK"
  },
  {
    "name": "Madagascar",
    "code": "MG"
  },
  {
    "name": "Malawi",
    "code": "MW"
  },
  {
    "name": "Malaysia",
    "code": "MY"
  },
  {
    "name": "Maldives",
    "code": "MV"
  },
  {
    "name": "Mali",
    "code": "ML"
  },
  {
    "name": "Malta",
    "code": "MT"
  },
  {
    "name": "Marshall Islands",
    "code": "MH"
  },
  {
    "name": "Martinique",
    "code": "MQ"
  },
  {
    "name": "Mauritania",
    "code": "MR"
  },
  {
    "name": "Mauritius",
    "code": "MU"
  },
  {
    "name": "Mayotte",
    "code": "YT"
  },
  {
    "name": "Mexico",
    "code": "MX"
  },
  {
    "name": "Micronesia, Federated States of",
    "code": "FM"
  },
  {
    "name": "Moldova, Republic of",
    "code": "MD"
  },
  {
    "name": "Monaco",
    "code": "MC"
  },
  {
    "name": "Mongolia",
    "code": "MN"
  },
  {
    "name": "Montserrat",
    "code": "MS"
  },
  {
    "name": "Morocco",
    "code": "MA"
  },
  {
    "name": "Mozambique",
    "code": "MZ"
  },
  {
    "name": "Myanmar",
    "code": "MM"
  },
  {
    "name": "Namibia",
    "code": "NA"
  },
  {
    "name": "Nauru",
    "code": "NR"
  },
  {
    "name": "Nepal",
    "code": "NP"
  },
  {
    "name": "Netherlands",
    "code": "NL"
  },
  {
    "name": "Netherlands Antilles",
    "code": "AN"
  },
  {
    "name": "New Caledonia",
    "code": "NC"
  },
  {
    "name": "New Zealand",
    "code": "NZ"
  },
  {
    "name": "Nicaragua",
    "code": "NI"
  },
  {
    "name": "Niger",
    "code": "NE"
  },
  {
    "name": "Nigeria",
    "code": "NG"
  },
  {
    "name": "Niue",
    "code": "NU"
  },
  {
    "name": "Norfolk Island",
    "code": "NF"
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP"
  },
  {
    "name": "Norway",
    "code": "NO"
  },
  {
    "name": "Oman",
    "code": "OM"
  },
  {
    "name": "Pakistan",
    "code": "PK"
  },
  {
    "name": "Palau",
    "code": "PW"
  },
  {
    "name": "Palestinian Territory, Occupied",
    "code": "PS"
  },
  {
    "name": "Panama",
    "code": "PA"
  },
  {
    "name": "Papua New Guinea",
    "code": "PG"
  },
  {
    "name": "Paraguay",
    "code": "PY"
  },
  {
    "name": "Peru",
    "code": "PE"
  },
  {
    "name": "Philippines",
    "code": "PH"
  },
  {
    "name": "Pitcairn",
    "code": "PN"
  },
  {
    "name": "Poland",
    "code": "PL"
  },
  {
    "name": "Portugal",
    "code": "PT"
  },
  {
    "name": "Puerto Rico",
    "code": "PR"
  },
  {
    "name": "Qatar",
    "code": "QA"
  },
  {
    "name": "Reunion",
    "code": "RE"
  },
  {
    "name": "Romania",
    "code": "RO"
  },
  {
    "name": "Russian Federation",
    "code": "RU"
  },
  {
    "name": "RWANDA",
    "code": "RW"
  },
  {
    "name": "Saint Helena",
    "code": "SH"
  },
  {
    "name": "Saint Kitts and Nevis",
    "code": "KN"
  },
  {
    "name": "Saint Lucia",
    "code": "LC"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "code": "PM"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "VC"
  },
  {
    "name": "Samoa",
    "code": "WS"
  },
  {
    "name": "San Marino",
    "code": "SM"
  },
  {
    "name": "Sao Tome and Principe",
    "code": "ST"
  },
  {
    "name": "Saudi Arabia",
    "code": "SA"
  },
  {
    "name": "Senegal",
    "code": "SN"
  },
  {
    "name": "Serbia and Montenegro",
    "code": "CS"
  },
  {
    "name": "Seychelles",
    "code": "SC"
  },
  {
    "name": "Sierra Leone",
    "code": "SL"
  },
  {
    "name": "Singapore",
    "code": "SG"
  },
  {
    "name": "Slovakia",
    "code": "SK"
  },
  {
    "name": "Slovenia",
    "code": "SI"
  },
  {
    "name": "Solomon Islands",
    "code": "SB"
  },
  {
    "name": "Somalia",
    "code": "SO"
  },
  {
    "name": "South Africa",
    "code": "ZA"
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "code": "GS"
  },
  {
    "name": "Spain",
    "code": "ES"
  },
  {
    "name": "Sri Lanka",
    "code": "LK"
  },
  {
    "name": "Sudan",
    "code": "SD"
  },
  {
    "name": "Suriname",
    "code": "SR"
  },
  {
    "name": "Svalbard and Jan Mayen",
    "code": "SJ"
  },
  {
    "name": "Swaziland",
    "code": "SZ"
  },
  {
    "name": "Sweden",
    "code": "SE"
  },
  {
    "name": "Switzerland",
    "code": "CH"
  },
  {
    "name": "Syrian Arab Republic",
    "code": "SY"
  },
  {
    "name": "Taiwan, Province of China",
    "code": "TW"
  },
  {
    "name": "Tajikistan",
    "code": "TJ"
  },
  {
    "name": "Tanzania, United Republic of",
    "code": "TZ"
  },
  {
    "name": "Thailand",
    "code": "TH"
  },
  {
    "name": "Timor-Leste",
    "code": "TL"
  },
  {
    "name": "Togo",
    "code": "TG"
  },
  {
    "name": "Tokelau",
    "code": "TK"
  },
  {
    "name": "Tonga",
    "code": "TO"
  },
  {
    "name": "Trinidad and Tobago",
    "code": "TT"
  },
  {
    "name": "Tunisia",
    "code": "TN"
  },
  {
    "name": "Turkey",
    "code": "TR"
  },
  {
    "name": "Turkmenistan",
    "code": "TM"
  },
  {
    "name": "Turks and Caicos Islands",
    "code": "TC"
  },
  {
    "name": "Tuvalu",
    "code": "TV"
  },
  {
    "name": "Uganda",
    "code": "UG"
  },
  {
    "name": "Ukraine",
    "code": "UA"
  },
  {
    "name": "United Arab Emirates",
    "code": "AE"
  },
  {
    "name": "United Kingdom",
    "code": "GB"
  },
  {
    "name": "United States",
    "code": "US"
  },
  {
    "name": "United States Minor Outlying Islands",
    "code": "UM"
  },
  {
    "name": "Uruguay",
    "code": "UY"
  },
  {
    "name": "Uzbekistan",
    "code": "UZ"
  },
  {
    "name": "Vanuatu",
    "code": "VU"
  },
  {
    "name": "Venezuela",
    "code": "VE"
  },
  {
    "name": "Viet Nam",
    "code": "VN"
  },
  {
    "name": "Virgin Islands, British",
    "code": "VG"
  },
  {
    "name": "Virgin Islands, U.S.",
    "code": "VI"
  },
  {
    "name": "Wallis and Futuna",
    "code": "WF"
  },
  {
    "name": "Western Sahara",
    "code": "EH"
  },
  {
    "name": "Yemen",
    "code": "YE"
  },
  {
    "name": "Zambia",
    "code": "ZM"
  },
  {
    "name": "Zimbabwe",
    "code": "ZW"
  }
] as const

export const currencies = {
  "EUR": {
    "code": "EUR",
    "name": "Euro",
    "symbol": "€"
  },
  "JOD": {
    "code": "JOD",
    "name": "Jordanian Dinar",
    "symbol": "JD"
  },
  "COP": {
    "code": "COP",
    "name": "Colombian Peso",
    "symbol": "CO$"
  },
  "JPY": {
    "code": "JPY",
    "name": "Japanese Yen",
    "symbol": "¥"
  },
  "TZS": {
    "code": "TZS",
    "name": "Tanzanian Shilling",
    "symbol": "TSh"
  },
  "TTD": {
    "code": "TTD",
    "name": "Trinidad and Tobago Dollar",
    "symbol": "TT$"
  },
  "XOF": {
    "code": "XOF",
    "name": "CFA Franc BCEAO",
    "symbol": "CFA"
  },
  "ILS": {
    "code": "ILS",
    "name": "Israeli New Sheqel",
    "symbol": "₪"
  },
  "AFN": {
    "code": "AFN",
    "name": "Afghan Afghani",
    "symbol": "Af"
  },
  "BGN": {
    "code": "BGN",
    "name": "Bulgarian Lev",
    "symbol": "BGN"
  },
  "BHD": {
    "code": "BHD",
    "name": "Bahraini Dinar",
    "symbol": "BD"
  },
  "BDT": {
    "code": "BDT",
    "name": "Bangladeshi Taka",
    "symbol": "Tk"
  },
  "AMD": {
    "code": "AMD",
    "name": "Armenian Dram",
    "symbol": "AMD"
  },
  "BWP": {
    "code": "BWP",
    "name": "Botswanan Pula",
    "symbol": "BWP"
  },
  "ALL": {
    "code": "ALL",
    "name": "Albanian Lek",
    "symbol": "ALL"
  },
  "BRL": {
    "code": "BRL",
    "name": "Brazilian Real",
    "symbol": "R$"
  },
  "AUD": {
    "code": "AUD",
    "name": "Australian Dollar",
    "symbol": "AU$"
  },
  "USD": {
    "code": "USD",
    "name": "US Dollar",
    "symbol": "$"
  },
  "BZD": {
    "code": "BZD",
    "name": "Belize Dollar",
    "symbol": "BZ$"
  },
  "IDR": {
    "code": "IDR",
    "name": "Indonesian Rupiah",
    "symbol": "Rp"
  },
  "CUP": {
    "code": "CUP",
    "name": "Cuban peso",
    "symbol": "MN$"
  },
  "TND": {
    "code": "TND",
    "name": "Tunisian Dinar",
    "symbol": "DT"
  },
  "BND": {
    "code": "BND",
    "name": "Brunei Dollar",
    "symbol": "BN$"
  },
  "DZD": {
    "code": "DZD",
    "name": "Algerian Dinar",
    "symbol": "DA"
  },
  "EGP": {
    "code": "EGP",
    "name": "Egyptian Pound",
    "symbol": "EGP"
  },
  "LBP": {
    "code": "LBP",
    "name": "Lebanese Pound",
    "symbol": "L.L."
  },
  "LKR": {
    "code": "LKR",
    "name": "Sri Lankan Rupee",
    "symbol": "SLRs"
  },
  "CZK": {
    "code": "CZK",
    "name": "Czech Republic Koruna",
    "symbol": "Kč"
  },
  "IQD": {
    "code": "IQD",
    "name": "Iraqi Dinar",
    "symbol": "IQD"
  },
  "KHR": {
    "code": "KHR",
    "name": "Cambodian Riel",
    "symbol": "KHR"
  },
  "KZT": {
    "code": "KZT",
    "name": "Kazakhstani Tenge",
    "symbol": "KZT"
  },
  "ETB": {
    "code": "ETB",
    "name": "Ethiopian Birr",
    "symbol": "Br"
  },
  "GNF": {
    "code": "GNF",
    "name": "Guinean Franc",
    "symbol": "FG"
  },
  "RSD": {
    "code": "RSD",
    "name": "Serbian Dinar",
    "symbol": "din."
  },
  "HKD": {
    "code": "HKD",
    "name": "Hong Kong Dollar",
    "symbol": "HK$"
  },
  "GHS": {
    "code": "GHS",
    "name": "Ghanaian Cedi",
    "symbol": "GH₵"
  },
  "AED": {
    "code": "AED",
    "name": "United Arab Emirates Dirham",
    "symbol": "AED"
  },
  "KMF": {
    "code": "KMF",
    "name": "Comorian Franc",
    "symbol": "CF"
  },
  "KRW": {
    "code": "KRW",
    "name": "South Korean Won",
    "symbol": "₩"
  },
  "JMD": {
    "code": "JMD",
    "name": "Jamaican Dollar",
    "symbol": "J$"
  },
  "MOP": {
    "code": "MOP",
    "name": "Macanese Pataca",
    "symbol": "MOP$"
  },
  "GTQ": {
    "code": "GTQ",
    "name": "Guatemalan Quetzal",
    "symbol": "GTQ"
  },
  "ARS": {
    "code": "ARS",
    "name": "Argentine Peso",
    "symbol": "AR$"
  },
  "AZN": {
    "code": "AZN",
    "name": "Azerbaijani Manat",
    "symbol": "man."
  },
  "INR": {
    "code": "INR",
    "name": "Indian Rupee",
    "symbol": "₹"
  },
  "MMK": {
    "code": "MMK",
    "name": "Myanma Kyat",
    "symbol": "MMK"
  },
  "BOB": {
    "code": "BOB",
    "name": "Bolivian Boliviano",
    "symbol": "Bs"
  },
  "LYD": {
    "code": "LYD",
    "name": "Libyan Dinar",
    "symbol": "LD"
  },
  "DOP": {
    "code": "DOP",
    "name": "Dominican Peso",
    "symbol": "RD$"
  },
  "YER": {
    "code": "YER",
    "name": "Yemeni Rial",
    "symbol": "YR"
  },
  "UYU": {
    "code": "UYU",
    "name": "Uruguayan Peso",
    "symbol": "$U"
  },
  "KES": {
    "code": "KES",
    "name": "Kenyan Shilling",
    "symbol": "Ksh"
  },
  "NZD": {
    "code": "NZD",
    "name": "New Zealand Dollar",
    "symbol": "NZ$"
  },
  "CRC": {
    "code": "CRC",
    "name": "Costa Rican Colón",
    "symbol": "₡"
  },
  "KWD": {
    "code": "KWD",
    "name": "Kuwaiti Dinar",
    "symbol": "KD"
  },
  "MUR": {
    "code": "MUR",
    "name": "Mauritian Rupee",
    "symbol": "MURs"
  },
  "NGN": {
    "code": "NGN",
    "name": "Nigerian Naira",
    "symbol": "₦"
  },
  "CNY": {
    "code": "CNY",
    "name": "Chinese Yuan",
    "symbol": "CN¥"
  },
  "PYG": {
    "code": "PYG",
    "name": "Paraguayan Guarani",
    "symbol": "₲"
  },
  "MXN": {
    "code": "MXN",
    "name": "Mexican Peso",
    "symbol": "MX$"
  },
  "ZAR": {
    "code": "ZAR",
    "name": "South African Rand",
    "symbol": "R"
  },
  "RWF": {
    "code": "RWF",
    "name": "Rwandan Franc",
    "symbol": "RWF"
  },
  "DJF": {
    "code": "DJF",
    "name": "Djiboutian Franc",
    "symbol": "Fdj"
  },
  "CAD": {
    "code": "CAD",
    "name": "Canadian Dollar",
    "symbol": "CA$"
  },
  "BYN": {
    "code": "BYN",
    "name": "Belarusian Ruble",
    "symbol": "Br"
  },
  "UGX": {
    "code": "UGX",
    "name": "Ugandan Shilling",
    "symbol": "USh"
  },
  "NIO": {
    "code": "NIO",
    "name": "Nicaraguan Córdoba",
    "symbol": "C$"
  },
  "XCD": {
    "code": "XCD",
    "name": "Eastern Caribbean dollar",
    "symbol": "EC$"
  },
  "NAD": {
    "code": "NAD",
    "name": "Namibian Dollar",
    "symbol": "N$"
  },
  "MYR": {
    "code": "MYR",
    "name": "Malaysian Ringgit",
    "symbol": "RM"
  },
  "HUF": {
    "code": "HUF",
    "name": "Hungarian Forint",
    "symbol": "Ft"
  },
  "PLN": {
    "code": "PLN",
    "name": "Polish Zloty",
    "symbol": "zł"
  },
  "SEK": {
    "code": "SEK",
    "name": "Swedish Krona",
    "symbol": "Skr"
  },
  "MDL": {
    "code": "MDL",
    "name": "Moldovan Leu",
    "symbol": "MDL"
  },
  "OMR": {
    "code": "OMR",
    "name": "Omani Rial",
    "symbol": "OMR"
  },
  "TRY": {
    "code": "TRY",
    "name": "Turkish Lira",
    "symbol": "TL"
  },
  "PEN": {
    "code": "PEN",
    "name": "Peruvian Nuevo Sol",
    "symbol": "S/."
  },
  "MZN": {
    "code": "MZN",
    "name": "Mozambican Metical",
    "symbol": "MTn"
  },
  "XAF": {
    "code": "XAF",
    "name": "CFA Franc BEAC",
    "symbol": "FCFA"
  },
  "MKD": {
    "code": "MKD",
    "name": "Macedonian Denar",
    "symbol": "MKD"
  },
  "PAB": {
    "code": "PAB",
    "name": "Panamanian Balboa",
    "symbol": "B/."
  },
  "GBP": {
    "code": "GBP",
    "name": "British Pound Sterling",
    "symbol": "£"
  },
  "CLP": {
    "code": "CLP",
    "name": "Chilean Peso",
    "symbol": "CL$"
  },
  "PHP": {
    "code": "PHP",
    "name": "Philippine Peso",
    "symbol": "₱"
  },
  "TOP": {
    "code": "TOP",
    "name": "Tongan Paʻanga",
    "symbol": "T$"
  },
  "GEL": {
    "code": "GEL",
    "name": "Georgian Lari",
    "symbol": "GEL"
  },
  "RUB": {
    "code": "RUB",
    "name": "Russian Ruble",
    "symbol": "RUB"
  },
  "SDG": {
    "code": "SDG",
    "name": "Sudanese Pound",
    "symbol": "SDG"
  },
  "RON": {
    "code": "RON",
    "name": "Romanian Leu",
    "symbol": "RON"
  },
  "SGD": {
    "code": "SGD",
    "name": "Singapore Dollar",
    "symbol": "S$"
  },
  "SOS": {
    "code": "SOS",
    "name": "Somali Shilling",
    "symbol": "Ssh"
  },
  "THB": {
    "code": "THB",
    "name": "Thai Baht",
    "symbol": "฿"
  },
  "TWD": {
    "code": "TWD",
    "name": "New Taiwan Dollar",
    "symbol": "NT$"
  },
  "QAR": {
    "code": "QAR",
    "name": "Qatari Rial",
    "symbol": "QR"
  },
  "UZS": {
    "code": "UZS",
    "name": "Uzbekistan Som",
    "symbol": "UZS"
  },
  "SAR": {
    "code": "SAR",
    "name": "Saudi Riyal",
    "symbol": "SR"
  },
  "NOK": {
    "code": "NOK",
    "name": "Norwegian Krone",
    "symbol": "Nkr"
  },
  "HNL": {
    "code": "HNL",
    "name": "Honduran Lempira",
    "symbol": "HNL"
  },
  "MGA": {
    "code": "MGA",
    "name": "Malagasy Ariary",
    "symbol": "MGA"
  },
  "NPR": {
    "code": "NPR",
    "name": "Nepalese Rupee",
    "symbol": "NPRs"
  },
  "UAH": {
    "code": "UAH",
    "name": "Ukrainian Hryvnia",
    "symbol": "₴"
  },
  "PKR": {
    "code": "PKR",
    "name": "Pakistani Rupee",
    "symbol": "PKRs"
  },
  "VND": {
    "code": "VND",
    "name": "Vietnamese Dong",
    "symbol": "₫"
  },
  "ISK": {
    "code": "ISK",
    "name": "Icelandic Króna",
    "symbol": "Ikr"
  },
  "BAM": {
    "code": "BAM",
    "name": "Bosnia-Herzegovina Convertible Mark",
    "symbol": "KM"
  },
  "DKK": {
    "code": "DKK",
    "name": "Danish Krone",
    "symbol": "Dkr"
  },
  "CHF": {
    "code": "CHF",
    "name": "Swiss Franc",
    "symbol": "CHF"
  },
  "CDF": {
    "code": "CDF",
    "name": "Congolese Franc",
    "symbol": "CDF"
  },
  "MAD": {
    "code": "MAD",
    "name": "Moroccan Dirham",
    "symbol": "MAD"
  },
  "BIF": {
    "code": "BIF",
    "name": "Burundian Franc",
    "symbol": "FBu"
  },
  "IRR": {
    "code": "IRR",
    "name": "Iranian Rial",
    "symbol": "IRR"
  },
  "CVE": {
    "code": "CVE",
    "name": "Cape Verdean Escudo",
    "symbol": "CV$"
  }
} as const
