import type { FieldPolicyInput } from "@voyantjs/catalog/contract"

export const CRUISE_CORE_FIELD_POLICY: FieldPolicyInput[] = [
  // ── Source pointer / provenance ─────────────────────────────────────────
  {
    path: "source.kind",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "source.ref",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "seller.operator_id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },

  // ── Identity / lifecycle ────────────────────────────────────────────────
  {
    path: "id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "first-class-table",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "slug",
    class: "managed",
    merge: "source-only",
    drift: "high",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "createdAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "updatedAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "externalRefs",
    class: "managed",
    merge: "source-only",
    drift: "medium",
    reindex: "none",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Merchandisable / marketing ──────────────────────────────────────────
  {
    path: "name",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "description",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "shortDescription",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "highlights",
    class: "merchandisable",
    merge: "additive-list",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Note: split rule §7.1 — `inclusionsHtml` is human-readable copy;
    // `cruiseInclusionEntitlements` (deferred — child entity) is the
    // machine-evaluable form. Today they live in separate columns; the
    // split is honored.
    path: "inclusionsHtml",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "exclusionsHtml",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "heroImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "thumbnailUrl",
    class: "merchandisable",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "mapImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
]
