/**
 * Catalog plane field policy for root `cruises` rows.
 *
 * Deferred child-entity registries: sailings, cabin categories/decks,
 * itinerary days, and pricing grids.
 */

import { defineFieldPolicy, type FieldPolicyInput } from "@voyantjs/catalog/contract"

const CRUISE_FIELD_POLICY: FieldPolicyInput[] = [
  // ── Source pointer / provenance ─────────────────────────────────────────
  {
    path: "source.kind",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "source.ref",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "seller.operator_id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },

  // ── Identity / lifecycle ────────────────────────────────────────────────
  {
    path: "id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "first-class-table",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "slug",
    class: "managed",
    merge: "source-only",
    drift: "high",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "createdAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "updatedAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "externalRefs",
    class: "managed",
    merge: "source-only",
    drift: "medium",
    reindex: "none",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Merchandisable / marketing ──────────────────────────────────────────
  {
    path: "name",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "description",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "shortDescription",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "highlights",
    class: "merchandisable",
    merge: "additive-list",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Note: split rule §7.1 — `inclusionsHtml` is human-readable copy;
    // `cruiseInclusionEntitlements` (deferred — child entity) is the
    // machine-evaluable form. Today they live in separate columns; the
    // split is honored.
    path: "inclusionsHtml",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "exclusionsHtml",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "heroImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "thumbnailUrl",
    class: "merchandisable",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "mapImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Structural / facet-affecting ───────────────────────────────────────
  {
    path: "cruiseType",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Supply mechanic — cruises are always `scheduled` (fixed dated sailings
    // with cabin allotment). See docs/architecture/catalog-supply-models.md.
    path: "supplyModel",
    class: "structural",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "status",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "lineSupplierId",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "defaultShipId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "nights",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "embarkPortFacilityId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "embarkPortCanonicalPlaceId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "disembarkPortFacilityId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "disembarkPortCanonicalPlaceId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "region_ids[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "waterway_ids[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "port_ids[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "country_iso[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  // TODO(catalog): split into marketing_regions + facet_regions per §7.1.
  // Today's schema has one `regions` column; declared structural so search
  // facets work, but that means marketing edits to it would drift faceting.
  // Operationally this is mostly source-controlled today; flag for split.
  {
    path: "regions[]",
    class: "structural",
    merge: "additive-set",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "ops",
    overrideFriction: "confirm",
    sourceFreshness: "sync",
  },
  {
    path: "waterways[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "ports[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "countries[]",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Same TODO as `regions` — split into marketing_themes + facet_themes
    // when the rule lands.
    path: "themes[]",
    class: "structural",
    merge: "additive-set",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "ops",
    overrideFriction: "confirm",
    sourceFreshness: "sync",
  },

  // ── Volatile-indexed (browse-time approximations) ──────────────────────
  // The cached lowest-price (integer minor units) + departure window are
  // explicit Tier 1 indexed price summaries (architecture §5.4.3). Refreshed
  // on source freshness sync; quote-time price comes through volatile-live
  // elsewhere.
  {
    path: "lowestPriceCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "lowestPriceCurrencyCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "lowestPriceUnit",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "earliestDepartureCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "latestDepartureCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Distinct departure months (`YYYY-MM`) across the cruise's sailings.
    // Facet-affecting (string[]) so browse surfaces can filter by departure
    // month/year. Populated from the per-cruise sailing list at sync time —
    // the upstream search projection only carries the [earliest, latest]
    // window, not the per-month breakdown.
    path: "departureMonths[]",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Total sailing (departure) count — typed `int64` via the `Count` suffix.
    // Rendered on browse cards alongside the next departure date.
    path: "departureCount",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
]

/**
 * Resolved field-policy registry for cruises. Templates wire it into the
 * indexer, overlay resolver, and snapshot capture pipeline.
 */
export const cruiseCatalogPolicy = defineFieldPolicy(CRUISE_FIELD_POLICY)

export { CRUISE_FIELD_POLICY }
