/**
 * A typed client for the Admin API.
 *
 * Types live one module per document, so a consumer pays only for what it
 * imports — there is no flat client with several hundred operations on it:
 *
 * ```ts
 * import type { paths } from "@voyant-travel/admin-api-client/finance"
 * const finance = createAdminApiClient<paths>({ secretKey, baseUrl })
 * ```
 *
 * Regenerated by `pnpm generate:api-client` and diffed by
 * `verify:openapi-drift`. See docs/adr/0023-generated-api-clients.md.
 *
 * There is no publishable variant. Every `/v1/admin/*` route is secret-only by
 * construction, so a "publishable admin client" would be an empty type pretending
 * to be a boundary — the PK/SK split is a property of the public surface, where
 * `@voyant-travel/public-api-client/generated` carries it.
 */
import { classifyPublicApiKeyToken, PUBLIC_API_KEY_HEADER } from "@voyant-travel/graph-contracts"
import createClient, { type ClientOptions } from "openapi-fetch"

export class AdminApiClientCredentialError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "AdminApiClientCredentialError"
  }
}

export interface AdminApiClientOptions extends Omit<ClientOptions, "headers"> {
  /** A secret (`vsk_`) key. The Admin API accepts no other kind. */
  secretKey: string
  /** Extra headers. The credential header is set from `secretKey` and wins. */
  headers?: Record<string, string>
}

/**
 * Construct a client for one Admin API module.
 *
 * A publishable key is rejected **here**, not on the first request. A `vpk_` is
 * a browser-resident credential: if it reaches this constructor at all, someone
 * is about to ship it somewhere it can be read, and the useful moment to say so
 * is at wiring time rather than in a 401 from production.
 *
 * The kind is decided by `classifyPublicApiKeyToken` from `@voyant-travel/core`,
 * which is the repository's single prefix table. It is imported rather than
 * re-implemented for the reason recorded next to it: two copies of that table
 * drifting is an auth bypass, and a client that classified keys by its own rule
 * would be the copy that drifts.
 */
export function createAdminApiClient<Paths extends Record<string, unknown>>(
  options: AdminApiClientOptions,
) {
  const { secretKey, headers, ...rest } = options
  const kind = classifyPublicApiKeyToken(secretKey)

  if (kind === null) {
    throw new AdminApiClientCredentialError(
      "createAdminApiClient requires a Voyant public API key; the value given is not shaped like one.",
    )
  }
  if (kind !== "secret") {
    throw new AdminApiClientCredentialError(
      `createAdminApiClient requires a secret key, received a ${kind} one. The Admin API is not ` +
        "reachable with a browser-resident credential, and a publishable key must never be given " +
        "to a server client that could log or forward it.",
    )
  }

  const client = createClient<Paths>({
    ...rest,
    headers: { ...headers, [PUBLIC_API_KEY_HEADER]: secretKey },
  })

  // Setting the header on the client is not enough. openapi-fetch merges
  // per-call headers AFTER the client defaults, so
  // `client.GET(path, { headers: { "x-api-key": somethingElse } })` replaced the
  // validated secret — the constructor check could be walked straight past, and
  // the original tests missed it because they only ever set headers on the
  // constructor. Middleware runs after that merge, so the credential this client
  // was built with is the credential it sends.
  client.use({
    onRequest({ request }) {
      request.headers.set(PUBLIC_API_KEY_HEADER, secretKey)
      return request
    },
  })

  return client
}
