import {
  type AdminExtension,
  type AdminRouteLoaderContext,
  adminRoutePageModule,
  defineAdminExtension,
  type SelectedAdminExtensionFactoryContext,
} from "@voyant-travel/admin"
import { defaultFetcher } from "@voyant-travel/react"
import { BarChart3 } from "lucide-react"

/**
 * Semantic destinations the reporting admin surfaces navigate through
 * (packaged-admin RFC §4.7). Bound to the routes below so the host resolver is
 * generated by `voyant admin generate --destinations`.
 */
declare module "@voyant-travel/admin" {
  interface AdminDestinations {
    /** The reports list page (the reporting area's landing surface). */
    "report.list": Record<string, never>
    /** A single report's builder page. */
    "report.detail": { reportId: string }
  }
}

/** Adapt the host runtime into the reporting data client. */
function runtimeClient(runtime: AdminRouteLoaderContext["runtime"]) {
  return { baseUrl: runtime.baseUrl, fetcher: runtime.fetcher ?? defaultFetcher }
}

export interface CreateReportingAdminExtensionOptions {
  /** Mount path of the reporting pages inside the admin workspace. Default `/reporting`. */
  basePath?: string
  labels?: {
    reports?: string
  }
}

/**
 * The reporting admin contribution: the `/reporting` list route and the
 * `/reporting/$id` builder route, each carrying its lazy page module and a
 * loader primed off the host runtime. Query options are imported dynamically
 * inside loaders so the reporting data layer stays out of the workspace-chrome
 * chunk that evaluates this factory.
 */
export function createReportingAdminExtension(
  options: CreateReportingAdminExtensionOptions = {},
): AdminExtension {
  const { basePath = "/reporting", labels = {} } = options
  const { reports = "Reports" } = labels

  return defineAdminExtension({
    id: "reporting",
    routes: [
      {
        id: "reporting-index",
        path: basePath,
        title: reports,
        destination: "report.list",
        ssr: "data-only",
        page: () =>
          import("./pages/reports-index.js").then((module) => adminRoutePageModule(module.default)),
        loader: async ({ queryClient, runtime }: AdminRouteLoaderContext) => {
          const { getReportsQueryOptions, getCatalogQueryOptions } = await import("./api.js")
          const client = runtimeClient(runtime)
          await queryClient.ensureQueryData(getReportsQueryOptions(client))
          void queryClient.prefetchQuery(getCatalogQueryOptions(client))
        },
      },
      {
        id: "reporting-detail",
        path: `${basePath}/$id`,
        title: reports,
        destination: "report.detail",
        destinationParams: { id: "reportId" },
        ssr: "data-only",
        page: () => import("./pages/report-detail.js"),
        loader: async ({ queryClient, runtime, params }: AdminRouteLoaderContext) => {
          const id = params.id
          if (!id) return
          const { getReportQueryOptions, getCatalogQueryOptions } = await import("./api.js")
          const client = runtimeClient(runtime)
          await queryClient.ensureQueryData(getReportQueryOptions(client, id))
          void queryClient.prefetchQuery(getCatalogQueryOptions(client))
        },
      },
    ],
  })
}

/** Graph-selected factory: adds the operator navigation group. */
export function createSelectedReportingAdminExtension({
  navMessages,
}: SelectedAdminExtensionFactoryContext): AdminExtension {
  const labels = { reports: navMessages.reports ?? "Reports" }
  const extension = createReportingAdminExtension({ labels })

  return {
    ...extension,
    navigation: [
      {
        order: -20,
        items: [
          {
            id: "reporting",
            title: labels.reports,
            url: "/reporting",
            icon: BarChart3,
          },
        ],
      },
    ],
  }
}
