import assert from "node:assert/strict"
import { describe, it } from "node:test"

import {
  actionableReviewDetails,
  buildReviewRepairEvidencePacket,
  hasReviewRepairEvidence,
  resolveReviewRepairEvidencePath,
  reviewRepairArtifactPlan,
  reviewRepairBlocker,
  reviewRepairEvidenceEnvironment,
} from "../lib/agent-runner-review.mjs"
import { workItem } from "./agent-fixtures.mjs"

describe("agent runner review repair helpers", () => {
  it("extracts actionable PR review feedback", () => {
    const details = actionableReviewDetails({
      reviewDecision: "CHANGES_REQUESTED",
      reviewThreads: {
        unresolved: [
          {
            author: "review-bot",
            body: "Preflight before mutating fields.",
            line: 17,
            path: "scripts/lib/agent-project-fields.mjs",
          },
        ],
      },
    })

    assert.equal(details.actionable, true)
    assert.equal(
      reviewRepairBlocker(details),
      "PR changes requested; Unresolved PR review threads: 1 (scripts/lib/agent-project-fields.mjs:17: Preflight before mutating fields.)",
    )
  })

  it("plans ignored local review repair evidence paths", () => {
    const plan = reviewRepairArtifactPlan({
      date: new Date("2026-05-10T12:34:56.000Z"),
      item: workItem(),
      repoRoot: "/repo",
    })

    assert.equal(
      plan.evidencePointer,
      ".agent-runs/579-test-agent-project-intake-workflow/review-repair-2026-05-10T12-34-56-000Z.md",
    )
    assert.equal(hasReviewRepairEvidence(plan.evidencePointer), true)
    assert.equal(hasReviewRepairEvidence("docs/agent-evidence/active/579-test.md"), false)
    assert.equal(hasReviewRepairEvidence(".agent-runs/../../tmp/review-repair-x.md"), false)
    assert.equal(
      resolveReviewRepairEvidencePath({
        evidenceReference: plan.evidencePointer,
        repoRoot: "/repo",
      }),
      "/repo/.agent-runs/579-test-agent-project-intake-workflow/review-repair-2026-05-10T12-34-56-000Z.md",
    )
    assert.deepEqual(
      reviewRepairEvidenceEnvironment({
        evidenceReference: plan.evidencePointer,
        repoRoot: "/repo",
      }),
      {
        VOYANT_AGENT_REVIEW_REPAIR_EVIDENCE_PATH:
          "/repo/.agent-runs/579-test-agent-project-intake-workflow/review-repair-2026-05-10T12-34-56-000Z.md",
        VOYANT_AGENT_REVIEW_REPAIR_EVIDENCE_REFERENCE:
          ".agent-runs/579-test-agent-project-intake-workflow/review-repair-2026-05-10T12-34-56-000Z.md",
      },
    )
  })

  it("builds provider-neutral review repair packets", () => {
    const body = buildReviewRepairEvidencePacket({
      details: actionableReviewDetails({
        reviewDecision: "CHANGES_REQUESTED",
        reviewThreads: {
          unresolved: [
            {
              author: "review-bot",
              body: "Preflight before mutating fields.",
              line: 17,
              path: "scripts/lib/agent-project-fields.mjs",
            },
          ],
        },
      }),
      generatedAt: new Date("2026-05-10T12:34:56.000Z"),
      item: workItem(),
      pr: { url: "https://github.com/voyantjs/voyant/pull/626" },
      repository: "voyantjs/voyant",
    })

    assert.match(body, /# Review Repair Packet/)
    assert.match(body, /Review decision: CHANGES_REQUESTED/)
    assert.match(body, /Preflight before mutating fields/)
    assert.doesNotMatch(body, /codex|claude|generated by/i)
  })
})
