import assert from "node:assert/strict"
import { describe, it } from "node:test"

import {
  buildCiRepairEvidencePacket,
  ciRepairArtifactPlan,
  ciRepairEvidenceEnvironment,
  collectFailedCheckLogs,
  failingCheckDetails,
  hasCiRepairEvidence,
  resolveCiRepairEvidencePath,
} from "../lib/agent-runner-ci.mjs"
import { workItem } from "./agent-fixtures.mjs"

describe("agent runner CI repair helpers", () => {
  it("extracts failed check details from PR status rollups", () => {
    assert.deepEqual(
      failingCheckDetails({
        statusCheckRollup: [
          {
            conclusion: "FAILURE",
            detailsUrl: "https://github.com/voyantjs/voyant/actions/runs/123/job/456",
            name: "checks",
            status: "COMPLETED",
            workflowName: "CI",
          },
          {
            conclusion: "STALE",
            detailsUrl: "https://github.com/voyantjs/voyant/actions/runs/789/job/101",
            name: "stale",
            status: "COMPLETED",
            workflowName: "CI",
          },
          { conclusion: "", name: "pending", status: "IN_PROGRESS" },
          { conclusion: "SUCCESS", name: "build", status: "COMPLETED" },
        ],
      }),
      [
        {
          conclusion: "FAILURE",
          detailsUrl: "https://github.com/voyantjs/voyant/actions/runs/123/job/456",
          name: "checks",
          runId: "123",
          status: "COMPLETED",
          workflowName: "CI",
        },
        {
          conclusion: "STALE",
          detailsUrl: "https://github.com/voyantjs/voyant/actions/runs/789/job/101",
          name: "stale",
          runId: "789",
          status: "COMPLETED",
          workflowName: "CI",
        },
      ],
    )
  })

  it("plans ignored local CI repair evidence paths", () => {
    const plan = ciRepairArtifactPlan({
      date: new Date("2026-05-10T12:34:56.000Z"),
      item: workItem(),
      repoRoot: "/repo",
    })

    assert.equal(
      plan.evidencePointer,
      ".agent-runs/579-test-agent-project-intake-workflow/ci-repair-2026-05-10T12-34-56-000Z.md",
    )
    assert.equal(hasCiRepairEvidence(plan.evidencePointer), true)
    assert.equal(hasCiRepairEvidence("docs/agent-evidence/active/579-test.md"), false)
    assert.equal(hasCiRepairEvidence(".agent-runs/../../tmp/ci-repair-x.md"), false)
    assert.equal(
      resolveCiRepairEvidencePath({ evidenceReference: plan.evidencePointer, repoRoot: "/repo" }),
      "/repo/.agent-runs/579-test-agent-project-intake-workflow/ci-repair-2026-05-10T12-34-56-000Z.md",
    )
    assert.equal(
      resolveCiRepairEvidencePath({
        evidenceReference: ".agent-runs/../../tmp/ci-repair-x.md",
        repoRoot: "/repo",
      }),
      null,
    )
    assert.deepEqual(
      ciRepairEvidenceEnvironment({ evidenceReference: plan.evidencePointer, repoRoot: "/repo" }),
      {
        VOYANT_AGENT_CI_REPAIR_EVIDENCE_PATH:
          "/repo/.agent-runs/579-test-agent-project-intake-workflow/ci-repair-2026-05-10T12-34-56-000Z.md",
        VOYANT_AGENT_CI_REPAIR_EVIDENCE_REFERENCE:
          ".agent-runs/579-test-agent-project-intake-workflow/ci-repair-2026-05-10T12-34-56-000Z.md",
      },
    )
    assert.deepEqual(
      ciRepairEvidenceEnvironment({
        evidenceReference: "docs/agent-evidence/active/579-test.md",
        repoRoot: "/repo",
      }),
      {},
    )
  })

  it("collects each failed run log once and truncates large outputs", () => {
    const calls = []
    const logs = collectFailedCheckLogs({
      checks: [
        { name: "checks", runId: "123" },
        { name: "build", runId: "123" },
        { name: "lint", runId: "456" },
      ],
      maxLogBytes: 5,
      repository: "voyantjs/voyant",
      run: (args) => {
        calls.push(args)
        return "abcdef"
      },
      workspace: "/repo",
    })

    assert.deepEqual(
      calls.map((args) => args[2]),
      ["123", "456"],
    )
    assert.match(logs[0].output, /^abcde\n\n\[truncated after 5 bytes\]/)
  })

  it("builds a provider-neutral repair prompt packet", () => {
    const body = buildCiRepairEvidencePacket({
      checks: [{ conclusion: "FAILURE", detailsUrl: "https://example.test", name: "checks" }],
      generatedAt: new Date("2026-05-10T12:34:56.000Z"),
      item: workItem(),
      logs: [{ output: "test failed", runId: "123" }],
      pr: { url: "https://github.com/voyantjs/voyant/pull/626" },
      repository: "voyantjs/voyant",
    })

    assert.match(body, /# CI Repair Packet/)
    assert.match(body, /checks: FAILURE/)
    assert.match(body, /test failed/)
    assert.doesNotMatch(body, /codex|claude|generated by/i)
  })
})
