// GENERATED by voyant admin generate --routes — do not edit.
// Code-assembled admin route tree for package-delivered pages (packaged-admin
// RFC §4.8 endgame): every extension route contribution becomes a code-based
// route grafted under the workspace layout — NO per-route files exist for
// package-delivered pages. Path literals + typed search contracts stay in
// this module (they are what gives the host typed links via the
// `AdminExtensionRoutesBy*` interfaces merged in `router.tsx`); pages,
// loaders, SSR modes, and boundaries come from the extension contributions
// (resolved from the host-owned registry in `src/lib/admin-extensions.tsx`,
// so app-supplied factory options apply to the assembled routes).
// To eject a route, remove it here (and from the maps below) and add a
// hand-written route file — the generator skips files without this header.
import { createRoute } from "@tanstack/react-router"
import { adminExtensionChildRoutes, adminExtensionRouteOptions } from "@voyantjs/admin-app"
import {
  bookingDetailSearchSchema,
  bookingsIndexSearchSchema,
} from "@voyantjs/bookings-react/admin"
import { catalogSearchSchema, productDetailSearchSchema } from "@voyantjs/catalog-react/admin"

import { adminExtensions } from "@/lib/admin-extensions"
import { getApiUrl } from "@/lib/env"
import { operatorFetcher } from "@/lib/voyant-fetcher"
import { Route as WorkspaceRoute } from "@/routes/_workspace/route"

// operatorFetcher so SSR loaders forward the request cookie; resolved per
// loader call because `getApiUrl()` reads the runtime origin.
const runtime = () => ({ baseUrl: getApiUrl(), fetcher: operatorFetcher })

const workspace = () => WorkspaceRoute

function extension(id: string) {
  const match = adminExtensions.find((candidate) => candidate.id === id)
  if (!match) {
    throw new Error(`[admin.routes.generated] No registered admin extension "${id}".`)
  }
  return match
}

// ---------------------------------------------------------------------------
// availability
// ---------------------------------------------------------------------------

const availabilityExtension = extension("availability")

export const AvailabilityIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/availability",
  ...adminExtensionRouteOptions(availabilityExtension, "availability-index", runtime),
})

export const AvailabilitySlotDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/availability/$id",
  ...adminExtensionRouteOptions(availabilityExtension, "availability-slot-detail", runtime),
})

export const AvailabilityRuleDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/availability/rules/$id",
  ...adminExtensionRouteOptions(availabilityExtension, "availability-rule-detail", runtime),
})

export const AvailabilityStartTimeDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/availability/start-times/$id",
  ...adminExtensionRouteOptions(availabilityExtension, "availability-start-time-detail", runtime),
})

// ---------------------------------------------------------------------------
// bookings
// ---------------------------------------------------------------------------

const bookingsExtension = extension("bookings")

export const BookingsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/bookings",
  validateSearch: bookingsIndexSearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-index", runtime),
})

export const BookingsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/bookings/$id",
  validateSearch: bookingDetailSearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-detail", runtime),
})

// ---------------------------------------------------------------------------
// catalog
// ---------------------------------------------------------------------------

const catalogExtension = extension("catalog")

export const CatalogIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog",
  ...adminExtensionRouteOptions(catalogExtension, "catalog-index", runtime),
})

export const CatalogProductsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/products",
  validateSearch: catalogSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-products-index", runtime),
})

export const CatalogProductsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/products/$productId",
  validateSearch: productDetailSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-products-detail", runtime),
})

export const CatalogExcursionsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/excursions",
  validateSearch: catalogSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-excursions-index", runtime),
})

export const CatalogExcursionsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/excursions/$id",
  ...adminExtensionRouteOptions(catalogExtension, "catalog-excursions-detail", runtime),
})

export const CatalogToursIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/tours",
  validateSearch: catalogSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-tours-index", runtime),
})

export const CatalogToursDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/tours/$id",
  ...adminExtensionRouteOptions(catalogExtension, "catalog-tours-detail", runtime),
})

export const CatalogCruisesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/cruises",
  validateSearch: catalogSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-cruises-index", runtime),
})

export const CatalogCruisesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/cruises/$id",
  ...adminExtensionRouteOptions(catalogExtension, "catalog-cruises-detail", runtime),
})

export const CatalogAccommodationsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/accommodations",
  validateSearch: catalogSearchSchema,
  ...adminExtensionRouteOptions(catalogExtension, "catalog-accommodations-index", runtime),
})

export const CatalogAccommodationsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/accommodations/$id",
  ...adminExtensionRouteOptions(catalogExtension, "catalog-accommodations-detail", runtime),
})

// ---------------------------------------------------------------------------
// core
// ---------------------------------------------------------------------------

const coreExtension = extension("core")

export const CoreDashboardRoute = createRoute({
  getParentRoute: workspace,
  path: "/",
  ...adminExtensionRouteOptions(coreExtension, "core-dashboard", runtime),
})

export const CoreAccountRoute = createRoute({
  getParentRoute: workspace,
  path: "/account",
  ...adminExtensionRouteOptions(coreExtension, "core-account", runtime),
})

export const CoreSettingsRoute = createRoute({
  getParentRoute: workspace,
  path: "/settings",
  ...adminExtensionRouteOptions(coreExtension, "core-settings", runtime),
})

const coreSettings = () => CoreSettingsRoute

export const CoreSettingsIndexRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-index", runtime),
})

export const CoreSettingsTeamRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/team",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-team", runtime),
})

export const CoreSettingsApiTokensRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/api-tokens",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-api-tokens", runtime),
})

export const CoreSettingsChannelsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/channels",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-channels", runtime),
})

export const CoreSettingsTaxesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/taxes",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-taxes", runtime),
})

export const CoreSettingsCostCategoriesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/cost-categories",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-cost-categories", runtime),
})

export const CoreSettingsPricingCategoriesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/pricing-categories",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-pricing-categories", runtime),
})

export const CoreSettingsPriceCatalogsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/price-catalogs",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-price-catalogs", runtime),
})

export const CoreSettingsProductTypesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/product-types",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-product-types", runtime),
})

export const CoreSettingsProductTagsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/product-tags",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-product-tags", runtime),
})

// Settings subtree: the static children above keep literal paths for typed
// links; app-supplied extra settings pages (factory `settings.extraPages`,
// invisible to the generator) bind at runtime via adminExtensionChildRoutes.
export const CoreSettingsRouteWithChildren = CoreSettingsRoute.addChildren([
  CoreSettingsIndexRoute,
  CoreSettingsTeamRoute,
  CoreSettingsApiTokensRoute,
  CoreSettingsChannelsRoute,
  CoreSettingsTaxesRoute,
  CoreSettingsCostCategoriesRoute,
  CoreSettingsPricingCategoriesRoute,
  CoreSettingsPriceCatalogsRoute,
  CoreSettingsProductTypesRoute,
  CoreSettingsProductTagsRoute,
  ...adminExtensionChildRoutes(coreExtension, "core-settings", coreSettings, runtime, {
    exclude: [
      "/",
      "/team",
      "/api-tokens",
      "/channels",
      "/taxes",
      "/cost-categories",
      "/pricing-categories",
      "/price-catalogs",
      "/product-types",
      "/product-tags",
    ],
  }),
])

// ---------------------------------------------------------------------------
// crm
// ---------------------------------------------------------------------------

const crmExtension = extension("crm")

export const CrmPeopleIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/people",
  ...adminExtensionRouteOptions(crmExtension, "crm-people-index", runtime),
})

export const CrmPeopleDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/people/$id",
  ...adminExtensionRouteOptions(crmExtension, "crm-people-detail", runtime),
})

export const CrmOrganizationsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/organizations",
  ...adminExtensionRouteOptions(crmExtension, "crm-organizations-index", runtime),
})

export const CrmOrganizationsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/organizations/$id",
  ...adminExtensionRouteOptions(crmExtension, "crm-organizations-detail", runtime),
})

// ---------------------------------------------------------------------------
// finance
// ---------------------------------------------------------------------------

const financeExtension = extension("finance")

export const FinanceIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance",
  ...adminExtensionRouteOptions(financeExtension, "finance-index", runtime),
})

export const FinanceInvoicesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoices",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoices-index", runtime),
})

export const FinanceInvoicesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoices/$id",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoices-detail", runtime),
})

export const FinanceInvoiceNumberSeriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoice-number-series",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoice-number-series", runtime),
})

export const FinancePaymentsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/payments",
  ...adminExtensionRouteOptions(financeExtension, "finance-payments-index", runtime),
})

export const FinancePaymentsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/payments/$id",
  ...adminExtensionRouteOptions(financeExtension, "finance-payments-detail", runtime),
})

export const FinanceProfitabilityRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/profitability",
  ...adminExtensionRouteOptions(financeExtension, "finance-profitability", runtime),
})

// ---------------------------------------------------------------------------
// legal
// ---------------------------------------------------------------------------

const legalExtension = extension("legal")

export const LegalIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal",
  ...adminExtensionRouteOptions(legalExtension, "legal-index", runtime),
})

export const LegalContractsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/contracts",
  ...adminExtensionRouteOptions(legalExtension, "legal-contracts-index", runtime),
})

export const LegalContractsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/contracts/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-contracts-detail", runtime),
})

export const LegalTemplatesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/templates",
  ...adminExtensionRouteOptions(legalExtension, "legal-templates-index", runtime),
})

export const LegalTemplatesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/templates/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-templates-detail", runtime),
})

export const LegalPoliciesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/policies",
  ...adminExtensionRouteOptions(legalExtension, "legal-policies-index", runtime),
})

export const LegalPoliciesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/policies/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-policies-detail", runtime),
})

export const LegalNumberSeriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/number-series",
  ...adminExtensionRouteOptions(legalExtension, "legal-number-series", runtime),
})

// ---------------------------------------------------------------------------
// notifications
// ---------------------------------------------------------------------------

const notificationsExtension = extension("notifications")

export const NotificationsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-index", runtime),
})

export const NotificationsTemplatesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/templates",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-templates-index", runtime),
})

export const NotificationsTemplatesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/templates/$id",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-templates-detail", runtime),
})

export const NotificationsReminderRulesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-rules",
  ...adminExtensionRouteOptions(
    notificationsExtension,
    "notifications-reminder-rules-index",
    runtime,
  ),
})

export const NotificationsReminderRulesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-rules/$id",
  ...adminExtensionRouteOptions(
    notificationsExtension,
    "notifications-reminder-rules-detail",
    runtime,
  ),
})

export const NotificationsDeliveriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/deliveries",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-deliveries", runtime),
})

export const NotificationsReminderRunsRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-runs",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-reminder-runs", runtime),
})

export const NotificationsPreviewRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/preview",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-preview", runtime),
})

export const NotificationsSettingsRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/settings",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-settings", runtime),
})

// ---------------------------------------------------------------------------
// promotions
// ---------------------------------------------------------------------------

const promotionsExtension = extension("promotions")

export const PromotionsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/promotions",
  ...adminExtensionRouteOptions(promotionsExtension, "promotions-index", runtime),
})

// ---------------------------------------------------------------------------
// resources
// ---------------------------------------------------------------------------

const resourcesExtension = extension("resources")

export const ResourcesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/resources",
  ...adminExtensionRouteOptions(resourcesExtension, "resources-index", runtime),
})

export const ResourcesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/resources/$id",
  ...adminExtensionRouteOptions(resourcesExtension, "resources-detail", runtime),
})

export const ResourcesPoolDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/resources/pools/$id",
  ...adminExtensionRouteOptions(resourcesExtension, "resources-pool-detail", runtime),
})

export const ResourcesAssignmentDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/resources/assignments/$id",
  ...adminExtensionRouteOptions(resourcesExtension, "resources-assignment-detail", runtime),
})

export const ResourcesAllocationDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/resources/allocations/$id",
  ...adminExtensionRouteOptions(resourcesExtension, "resources-allocation-detail", runtime),
})

// ---------------------------------------------------------------------------
// suppliers
// ---------------------------------------------------------------------------

const suppliersExtension = extension("suppliers")

export const SuppliersIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/suppliers",
  ...adminExtensionRouteOptions(suppliersExtension, "suppliers-index", runtime),
})

export const SuppliersDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/suppliers/$id",
  ...adminExtensionRouteOptions(suppliersExtension, "suppliers-detail", runtime),
})

// ---------------------------------------------------------------------------
// tree + typed-link maps
// ---------------------------------------------------------------------------

export const adminExtensionRoutes = [
  AvailabilityIndexRoute,
  AvailabilitySlotDetailRoute,
  AvailabilityRuleDetailRoute,
  AvailabilityStartTimeDetailRoute,
  BookingsIndexRoute,
  BookingsDetailRoute,
  CatalogIndexRoute,
  CatalogProductsIndexRoute,
  CatalogProductsDetailRoute,
  CatalogExcursionsIndexRoute,
  CatalogExcursionsDetailRoute,
  CatalogToursIndexRoute,
  CatalogToursDetailRoute,
  CatalogCruisesIndexRoute,
  CatalogCruisesDetailRoute,
  CatalogAccommodationsIndexRoute,
  CatalogAccommodationsDetailRoute,
  CoreDashboardRoute,
  CoreAccountRoute,
  CoreSettingsRouteWithChildren,
  CrmPeopleIndexRoute,
  CrmPeopleDetailRoute,
  CrmOrganizationsIndexRoute,
  CrmOrganizationsDetailRoute,
  FinanceIndexRoute,
  FinanceInvoicesIndexRoute,
  FinanceInvoicesDetailRoute,
  FinanceInvoiceNumberSeriesRoute,
  FinancePaymentsIndexRoute,
  FinancePaymentsDetailRoute,
  FinanceProfitabilityRoute,
  LegalIndexRoute,
  LegalContractsIndexRoute,
  LegalContractsDetailRoute,
  LegalTemplatesIndexRoute,
  LegalTemplatesDetailRoute,
  LegalPoliciesIndexRoute,
  LegalPoliciesDetailRoute,
  LegalNumberSeriesRoute,
  NotificationsIndexRoute,
  NotificationsTemplatesIndexRoute,
  NotificationsTemplatesDetailRoute,
  NotificationsReminderRulesIndexRoute,
  NotificationsReminderRulesDetailRoute,
  NotificationsDeliveriesRoute,
  NotificationsReminderRunsRoute,
  NotificationsPreviewRoute,
  NotificationsSettingsRoute,
  PromotionsIndexRoute,
  ResourcesIndexRoute,
  ResourcesDetailRoute,
  ResourcesPoolDetailRoute,
  ResourcesAssignmentDetailRoute,
  ResourcesAllocationDetailRoute,
  SuppliersIndexRoute,
  SuppliersDetailRoute,
]

export interface AdminExtensionRoutesByFullPath {
  "/availability": typeof AvailabilityIndexRoute
  "/availability/$id": typeof AvailabilitySlotDetailRoute
  "/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/bookings": typeof BookingsIndexRoute
  "/bookings/$id": typeof BookingsDetailRoute
  "/catalog": typeof CatalogIndexRoute
  "/catalog/products": typeof CatalogProductsIndexRoute
  "/catalog/products/$productId": typeof CatalogProductsDetailRoute
  "/catalog/excursions": typeof CatalogExcursionsIndexRoute
  "/catalog/excursions/$id": typeof CatalogExcursionsDetailRoute
  "/catalog/tours": typeof CatalogToursIndexRoute
  "/catalog/tours/$id": typeof CatalogToursDetailRoute
  "/catalog/cruises": typeof CatalogCruisesIndexRoute
  "/catalog/cruises/$id": typeof CatalogCruisesDetailRoute
  "/catalog/accommodations": typeof CatalogAccommodationsIndexRoute
  "/catalog/accommodations/$id": typeof CatalogAccommodationsDetailRoute
  "/": typeof CoreDashboardRoute
  "/account": typeof CoreAccountRoute
  "/settings": typeof CoreSettingsRouteWithChildren
  "/settings/": typeof CoreSettingsIndexRoute
  "/settings/team": typeof CoreSettingsTeamRoute
  "/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/settings/channels": typeof CoreSettingsChannelsRoute
  "/settings/taxes": typeof CoreSettingsTaxesRoute
  "/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/people": typeof CrmPeopleIndexRoute
  "/people/$id": typeof CrmPeopleDetailRoute
  "/organizations": typeof CrmOrganizationsIndexRoute
  "/organizations/$id": typeof CrmOrganizationsDetailRoute
  "/finance": typeof FinanceIndexRoute
  "/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/finance/payments": typeof FinancePaymentsIndexRoute
  "/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/finance/profitability": typeof FinanceProfitabilityRoute
  "/legal": typeof LegalIndexRoute
  "/legal/contracts": typeof LegalContractsIndexRoute
  "/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/legal/templates": typeof LegalTemplatesIndexRoute
  "/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/legal/policies": typeof LegalPoliciesIndexRoute
  "/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/legal/number-series": typeof LegalNumberSeriesRoute
  "/notifications": typeof NotificationsIndexRoute
  "/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/notifications/preview": typeof NotificationsPreviewRoute
  "/notifications/settings": typeof NotificationsSettingsRoute
  "/promotions": typeof PromotionsIndexRoute
  "/resources": typeof ResourcesIndexRoute
  "/resources/$id": typeof ResourcesDetailRoute
  "/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/suppliers": typeof SuppliersIndexRoute
  "/suppliers/$id": typeof SuppliersDetailRoute
}

export interface AdminExtensionRoutesByTo {
  "/availability": typeof AvailabilityIndexRoute
  "/availability/$id": typeof AvailabilitySlotDetailRoute
  "/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/bookings": typeof BookingsIndexRoute
  "/bookings/$id": typeof BookingsDetailRoute
  "/catalog": typeof CatalogIndexRoute
  "/catalog/products": typeof CatalogProductsIndexRoute
  "/catalog/products/$productId": typeof CatalogProductsDetailRoute
  "/catalog/excursions": typeof CatalogExcursionsIndexRoute
  "/catalog/excursions/$id": typeof CatalogExcursionsDetailRoute
  "/catalog/tours": typeof CatalogToursIndexRoute
  "/catalog/tours/$id": typeof CatalogToursDetailRoute
  "/catalog/cruises": typeof CatalogCruisesIndexRoute
  "/catalog/cruises/$id": typeof CatalogCruisesDetailRoute
  "/catalog/accommodations": typeof CatalogAccommodationsIndexRoute
  "/catalog/accommodations/$id": typeof CatalogAccommodationsDetailRoute
  "/": typeof CoreDashboardRoute
  "/account": typeof CoreAccountRoute
  "/settings": typeof CoreSettingsIndexRoute
  "/settings/team": typeof CoreSettingsTeamRoute
  "/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/settings/channels": typeof CoreSettingsChannelsRoute
  "/settings/taxes": typeof CoreSettingsTaxesRoute
  "/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/people": typeof CrmPeopleIndexRoute
  "/people/$id": typeof CrmPeopleDetailRoute
  "/organizations": typeof CrmOrganizationsIndexRoute
  "/organizations/$id": typeof CrmOrganizationsDetailRoute
  "/finance": typeof FinanceIndexRoute
  "/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/finance/payments": typeof FinancePaymentsIndexRoute
  "/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/finance/profitability": typeof FinanceProfitabilityRoute
  "/legal": typeof LegalIndexRoute
  "/legal/contracts": typeof LegalContractsIndexRoute
  "/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/legal/templates": typeof LegalTemplatesIndexRoute
  "/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/legal/policies": typeof LegalPoliciesIndexRoute
  "/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/legal/number-series": typeof LegalNumberSeriesRoute
  "/notifications": typeof NotificationsIndexRoute
  "/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/notifications/preview": typeof NotificationsPreviewRoute
  "/notifications/settings": typeof NotificationsSettingsRoute
  "/promotions": typeof PromotionsIndexRoute
  "/resources": typeof ResourcesIndexRoute
  "/resources/$id": typeof ResourcesDetailRoute
  "/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/suppliers": typeof SuppliersIndexRoute
  "/suppliers/$id": typeof SuppliersDetailRoute
}

export interface AdminExtensionRoutesById {
  "/_workspace/availability": typeof AvailabilityIndexRoute
  "/_workspace/availability/$id": typeof AvailabilitySlotDetailRoute
  "/_workspace/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/_workspace/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/_workspace/bookings": typeof BookingsIndexRoute
  "/_workspace/bookings/$id": typeof BookingsDetailRoute
  "/_workspace/catalog": typeof CatalogIndexRoute
  "/_workspace/catalog/products": typeof CatalogProductsIndexRoute
  "/_workspace/catalog/products/$productId": typeof CatalogProductsDetailRoute
  "/_workspace/catalog/excursions": typeof CatalogExcursionsIndexRoute
  "/_workspace/catalog/excursions/$id": typeof CatalogExcursionsDetailRoute
  "/_workspace/catalog/tours": typeof CatalogToursIndexRoute
  "/_workspace/catalog/tours/$id": typeof CatalogToursDetailRoute
  "/_workspace/catalog/cruises": typeof CatalogCruisesIndexRoute
  "/_workspace/catalog/cruises/$id": typeof CatalogCruisesDetailRoute
  "/_workspace/catalog/accommodations": typeof CatalogAccommodationsIndexRoute
  "/_workspace/catalog/accommodations/$id": typeof CatalogAccommodationsDetailRoute
  "/_workspace/": typeof CoreDashboardRoute
  "/_workspace/account": typeof CoreAccountRoute
  "/_workspace/settings": typeof CoreSettingsRouteWithChildren
  "/_workspace/settings/": typeof CoreSettingsIndexRoute
  "/_workspace/settings/team": typeof CoreSettingsTeamRoute
  "/_workspace/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/_workspace/settings/channels": typeof CoreSettingsChannelsRoute
  "/_workspace/settings/taxes": typeof CoreSettingsTaxesRoute
  "/_workspace/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/_workspace/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/_workspace/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/_workspace/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/_workspace/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/_workspace/people": typeof CrmPeopleIndexRoute
  "/_workspace/people/$id": typeof CrmPeopleDetailRoute
  "/_workspace/organizations": typeof CrmOrganizationsIndexRoute
  "/_workspace/organizations/$id": typeof CrmOrganizationsDetailRoute
  "/_workspace/finance": typeof FinanceIndexRoute
  "/_workspace/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/_workspace/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/_workspace/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/_workspace/finance/payments": typeof FinancePaymentsIndexRoute
  "/_workspace/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/_workspace/finance/profitability": typeof FinanceProfitabilityRoute
  "/_workspace/legal": typeof LegalIndexRoute
  "/_workspace/legal/contracts": typeof LegalContractsIndexRoute
  "/_workspace/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/_workspace/legal/templates": typeof LegalTemplatesIndexRoute
  "/_workspace/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/_workspace/legal/policies": typeof LegalPoliciesIndexRoute
  "/_workspace/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/_workspace/legal/number-series": typeof LegalNumberSeriesRoute
  "/_workspace/notifications": typeof NotificationsIndexRoute
  "/_workspace/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/_workspace/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/_workspace/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/_workspace/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/_workspace/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/_workspace/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/_workspace/notifications/preview": typeof NotificationsPreviewRoute
  "/_workspace/notifications/settings": typeof NotificationsSettingsRoute
  "/_workspace/promotions": typeof PromotionsIndexRoute
  "/_workspace/resources": typeof ResourcesIndexRoute
  "/_workspace/resources/$id": typeof ResourcesDetailRoute
  "/_workspace/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/_workspace/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/_workspace/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/_workspace/suppliers": typeof SuppliersIndexRoute
  "/_workspace/suppliers/$id": typeof SuppliersDetailRoute
}
