// GENERATED by voyant admin generate --destinations — do not edit.
// Generated destination resolvers (packaged-admin RFC §4.7 endgame): every
// route contribution that declares a `destination:` annotation becomes a
// pure path-interpolation resolver here. The host's resolver map spreads
// this object FIRST and hand-writes only the genuinely custom resolvers
// (search-param construction, multi-route targets):
//   { ...generatedAdminDestinations, ...custom } satisfies AdminDestinationResolvers
// To eject the whole map, delete this header — the generator skips files
// without it. To override one key, re-declare it after the spread in the
// host map (later properties win); to unbind one, remove the
// contribution's `destination:` annotation and regenerate.
import type { AdminDestinationResolvers } from "@voyantjs/admin"
// Type-only: bind the mounted admin entries' `AdminDestinations`
// augmentations into this module without pulling any runtime code into
// the chunk that imports the resolver map.
import type {} from "@voyantjs/action-ledger-react/admin"
import type {} from "@voyantjs/availability-react/admin"
import type {} from "@voyantjs/bookings-react/admin"
import type {} from "@voyantjs/catalog-react/admin"
import type {} from "@voyantjs/relationships-react/admin"
import type {} from "@voyantjs/distribution-react/admin"
import type {} from "@voyantjs/finance-react/admin"
import type {} from "@voyantjs/flights-react/admin"
import type {} from "@voyantjs/legal-react/admin"
import type {} from "@voyantjs/notifications-react/admin"
import type {} from "@voyantjs/inventory-react/admin"
import type {} from "@voyantjs/commerce-react/promotions/admin"
import type {} from "@voyantjs/resources-react/admin"
import type {} from "@voyantjs/distribution-react/suppliers/admin"
import type {} from "@voyantjs/travel-composer-react/admin"

/** Resolvers for the route-backed subset of the declared destination keys. */
export const generatedAdminDestinations = {
  "availabilitySlot.detail": ({ slotId }) => `/availability/${encodeURIComponent(slotId)}`,
  "availabilitySlot.list": () => "/availability",
  "availabilityStartTime.detail": ({ startTimeId }) =>
    `/availability/start-times/${encodeURIComponent(startTimeId)}`,
  "booking.create": () => "/bookings/new",
  "booking.list": () => "/bookings",
  "contract.detail": ({ contractId }) => `/legal/contracts/${encodeURIComponent(contractId)}`,
  "contract.list": () => "/legal/contracts",
  "contractTemplate.detail": ({ templateId }) =>
    `/legal/templates/${encodeURIComponent(templateId)}`,
  "contractTemplate.list": () => "/legal/templates",
  "flight.search": () => "/flights",
  "invoice.detail": ({ invoiceId }) => `/finance/invoices/${encodeURIComponent(invoiceId)}`,
  "invoice.list": () => "/finance/invoices",
  "notificationReminderRule.detail": ({ ruleId }) =>
    `/notifications/reminder-rules/${encodeURIComponent(ruleId)}`,
  "notificationReminderRule.list": () => "/notifications/reminder-rules",
  "notificationTemplate.detail": ({ templateId }) =>
    `/notifications/templates/${encodeURIComponent(templateId)}`,
  "notificationTemplate.list": () => "/notifications/templates",
  "organization.detail": ({ organizationId }) =>
    `/organizations/${encodeURIComponent(organizationId)}`,
  "organization.list": () => "/organizations",
  "payment.detail": ({ paymentId }) => `/finance/payments/${encodeURIComponent(paymentId)}`,
  "payment.list": () => "/finance/payments",
  "person.detail": ({ personId }) => `/people/${encodeURIComponent(personId)}`,
  "person.list": () => "/people",
  "policy.detail": ({ policyId }) => `/legal/policies/${encodeURIComponent(policyId)}`,
  "policy.list": () => "/legal/policies",
  "product.detail": ({ productId }) => `/products/${encodeURIComponent(productId)}`,
  "product.list": () => "/products",
  "productCategory.list": () => "/products/categories",
  "resource.detail": ({ resourceId }) => `/resources/${encodeURIComponent(resourceId)}`,
  "resource.list": () => "/resources",
  "resourceAllocation.detail": ({ allocationId }) =>
    `/resources/allocations/${encodeURIComponent(allocationId)}`,
  "resourceAssignment.detail": ({ assignmentId }) =>
    `/resources/assignments/${encodeURIComponent(assignmentId)}`,
  "resourcePool.detail": ({ poolId }) => `/resources/pools/${encodeURIComponent(poolId)}`,
  "supplier.detail": ({ supplierId }) => `/suppliers/${encodeURIComponent(supplierId)}`,
  "supplier.list": () => "/suppliers",
  "supplierInvoice.detail": ({ supplierInvoiceId }) =>
    `/finance/supplier-invoices/${encodeURIComponent(supplierInvoiceId)}`,
  "supplierInvoice.list": () => "/finance/supplier-invoices",
  "trip.detail": ({ tripId }) => `/trips/${encodeURIComponent(tripId)}`,
  "trip.list": () => "/trips",
} satisfies Partial<AdminDestinationResolvers>
