// GENERATED by voyant admin generate — do not edit.
// Recreate after changing the modules list in voyant.config.*:
//   voyant admin generate

import { createCrmAdminExtension } from "@voyantjs/crm-ui/admin"
import { createSuppliersAdminExtension } from "@voyantjs/suppliers-ui/admin"
import { createPromotionsAdminExtension } from "@voyantjs/promotions-ui/admin"
import { createCatalogAdminExtension } from "@voyantjs/catalog-ui/admin"
import { createBookingsAdminExtension } from "@voyantjs/bookings-ui/admin"
import { createFinanceAdminExtension } from "@voyantjs/finance-ui/admin"
import { createNotificationsAdminExtension } from "@voyantjs/notifications-ui/admin"
import { createLegalAdminExtension } from "@voyantjs/legal-ui/admin"

/**
 * Admin extension factories keyed by module domain. Factories, not
 * instances — hosts call each with localized labels/icons before
 * registering the result.
 */
export const generatedAdminExtensionFactories = {
  crm: createCrmAdminExtension,
  suppliers: createSuppliersAdminExtension,
  promotions: createPromotionsAdminExtension,
  catalog: createCatalogAdminExtension,
  bookings: createBookingsAdminExtension,
  finance: createFinanceAdminExtension,
  notifications: createNotificationsAdminExtension,
  legal: createLegalAdminExtension,
} as const
