// GENERATED by voyant admin generate — do not edit.
// Recreate after changing the modules list in voyant.config.*:
//   voyant admin generate

import { createActionLedgerAdminExtension } from "@voyantjs/action-ledger-react/admin"
import { createRelationshipsAdminExtension } from "@voyantjs/relationships-react/admin"
import { createSuppliersAdminExtension } from "@voyantjs/suppliers-react/admin"
import { createProductsAdminExtension } from "@voyantjs/inventory-react/admin"
import { createPromotionsAdminExtension } from "@voyantjs/commerce-react/promotions/admin"
import { createCatalogAdminExtension } from "@voyantjs/catalog-react/admin"
import { createBookingsAdminExtension } from "@voyantjs/bookings-react/admin"
import { createFinanceAdminExtension } from "@voyantjs/finance-react/admin"
import { createAvailabilityAdminExtension } from "@voyantjs/availability-react/admin"
import { createDistributionAdminExtension } from "@voyantjs/distribution-react/admin"
import { createResourcesAdminExtension } from "@voyantjs/resources-react/admin"
import { createNotificationsAdminExtension } from "@voyantjs/notifications-react/admin"
import { createFlightsAdminExtension } from "@voyantjs/flights-react/admin"
import { createLegalAdminExtension } from "@voyantjs/legal-react/admin"
import { createTripComposerAdminExtension } from "@voyantjs/trip-composer-react/admin"

/**
 * Admin extension factories keyed by module domain. Factories, not
 * instances — hosts call each with localized labels/icons before
 * registering the result.
 */
export const generatedAdminExtensionFactories = {
  actionLedger: createActionLedgerAdminExtension,
  relationships: createRelationshipsAdminExtension,
  suppliers: createSuppliersAdminExtension,
  products: createProductsAdminExtension,
  promotions: createPromotionsAdminExtension,
  catalog: createCatalogAdminExtension,
  bookings: createBookingsAdminExtension,
  finance: createFinanceAdminExtension,
  availability: createAvailabilityAdminExtension,
  distribution: createDistributionAdminExtension,
  resources: createResourcesAdminExtension,
  notifications: createNotificationsAdminExtension,
  flights: createFlightsAdminExtension,
  legal: createLegalAdminExtension,
  tripComposer: createTripComposerAdminExtension,
} as const
