/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRouteImport } from './routes/pay'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as storefrontRouteRouteImport } from './routes/(storefront)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as ProposalQuoteVersionIdRouteImport } from './routes/proposal.$quoteVersionId'
import { Route as PaySessionIdRouteImport } from './routes/pay_.$sessionId'
import { Route as AccountantTokenRouteImport } from './routes/accountant.$token'
import { Route as WorkspaceFlightsRouteImport } from './routes/_workspace/flights'
import { Route as WorkspaceChannelSyncRouteImport } from './routes/_workspace/channel-sync'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as storefrontShopRouteImport } from './routes/(storefront)/shop'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceNotificationsIndexRouteImport } from './routes/_workspace/notifications/index'
import { Route as WorkspaceLegalIndexRouteImport } from './routes/_workspace/legal/index'
import { Route as WorkspaceFinanceIndexRouteImport } from './routes/_workspace/finance/index'
import { Route as WorkspaceCatalogIndexRouteImport } from './routes/_workspace/catalog/index'
import { Route as WorkspaceSettingsTeamRouteImport } from './routes/_workspace/settings/team'
import { Route as WorkspaceSettingsTaxesRouteImport } from './routes/_workspace/settings/taxes'
import { Route as WorkspaceSettingsProductTypesRouteImport } from './routes/_workspace/settings/product-types'
import { Route as WorkspaceSettingsProductTagsRouteImport } from './routes/_workspace/settings/product-tags'
import { Route as WorkspaceSettingsPricingCategoriesRouteImport } from './routes/_workspace/settings/pricing-categories'
import { Route as WorkspaceSettingsPriceCatalogsRouteImport } from './routes/_workspace/settings/price-catalogs'
import { Route as WorkspaceSettingsOperatorRouteImport } from './routes/_workspace/settings/operator'
import { Route as WorkspaceSettingsCostCategoriesRouteImport } from './routes/_workspace/settings/cost-categories'
import { Route as WorkspaceSettingsChannelsRouteImport } from './routes/_workspace/settings/channels'
import { Route as WorkspaceSettingsApiTokensRouteImport } from './routes/_workspace/settings/api-tokens'
import { Route as WorkspaceBookingsComposeRouteImport } from './routes/_workspace/bookings_.compose'
import { Route as WorkspaceBookingsNewRouteImport } from './routes/_workspace/bookings/new'
import { Route as storefrontShopComposerRouteImport } from './routes/(storefront)/shop_.composer'
import { Route as WorkspaceFinanceSupplierInvoicesIndexRouteImport } from './routes/_workspace/finance/supplier-invoices/index'
import { Route as WorkspaceFlightsBookOfferIdRouteImport } from './routes/_workspace/flights_.book.$offerId'
import { Route as WorkspaceFinanceSupplierInvoicesIdRouteImport } from './routes/_workspace/finance/supplier-invoices/$id'
import { Route as storefrontShopConfirmationBookingIdRouteImport } from './routes/(storefront)/shop_.confirmation.$bookingId'
import { Route as WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport } from './routes/_workspace/catalog_.journey.$entityModule.$entityId'
import { Route as storefrontShopProductsEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.products.$entityModule.$entityId'
import { Route as storefrontShopBookEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.book.$entityModule.$entityId'

const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontRouteRoute = storefrontRouteRouteImport.update({
  id: '/(storefront)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const ProposalQuoteVersionIdRoute = ProposalQuoteVersionIdRouteImport.update({
  id: '/proposal/$quoteVersionId',
  path: '/proposal/$quoteVersionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySessionIdRoute = PaySessionIdRouteImport.update({
  id: '/pay_/$sessionId',
  path: '/pay/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantTokenRoute = AccountantTokenRouteImport.update({
  id: '/accountant/$token',
  path: '/accountant/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceFlightsRoute = WorkspaceFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceChannelSyncRoute = WorkspaceChannelSyncRouteImport.update({
  id: '/channel-sync',
  path: '/channel-sync',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const storefrontShopRoute = storefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceNotificationsIndexRoute =
  WorkspaceNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalIndexRoute = WorkspaceLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceFinanceIndexRoute = WorkspaceFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceCatalogIndexRoute = WorkspaceCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsTeamRoute = WorkspaceSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsTaxesRoute = WorkspaceSettingsTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsProductTypesRoute =
  WorkspaceSettingsProductTypesRouteImport.update({
    id: '/product-types',
    path: '/product-types',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsProductTagsRoute =
  WorkspaceSettingsProductTagsRouteImport.update({
    id: '/product-tags',
    path: '/product-tags',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCategoriesRoute =
  WorkspaceSettingsPricingCategoriesRouteImport.update({
    id: '/pricing-categories',
    path: '/pricing-categories',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPriceCatalogsRoute =
  WorkspaceSettingsPriceCatalogsRouteImport.update({
    id: '/price-catalogs',
    path: '/price-catalogs',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsOperatorRoute =
  WorkspaceSettingsOperatorRouteImport.update({
    id: '/operator',
    path: '/operator',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsCostCategoriesRoute =
  WorkspaceSettingsCostCategoriesRouteImport.update({
    id: '/cost-categories',
    path: '/cost-categories',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsChannelsRoute =
  WorkspaceSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsApiTokensRoute =
  WorkspaceSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceBookingsComposeRoute =
  WorkspaceBookingsComposeRouteImport.update({
    id: '/bookings_/compose',
    path: '/bookings/compose',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceBookingsNewRoute = WorkspaceBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const storefrontShopComposerRoute = storefrontShopComposerRouteImport.update({
  id: '/shop_/composer',
  path: '/shop/composer',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const WorkspaceFinanceSupplierInvoicesIndexRoute =
  WorkspaceFinanceSupplierInvoicesIndexRouteImport.update({
    id: '/finance/supplier-invoices/',
    path: '/finance/supplier-invoices/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFlightsBookOfferIdRoute =
  WorkspaceFlightsBookOfferIdRouteImport.update({
    id: '/flights_/book/$offerId',
    path: '/flights/book/$offerId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceSupplierInvoicesIdRoute =
  WorkspaceFinanceSupplierInvoicesIdRouteImport.update({
    id: '/finance/supplier-invoices/$id',
    path: '/finance/supplier-invoices/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const storefrontShopConfirmationBookingIdRoute =
  storefrontShopConfirmationBookingIdRouteImport.update({
    id: '/shop_/confirmation/$bookingId',
    path: '/shop/confirmation/$bookingId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const WorkspaceCatalogJourneyEntityModuleEntityIdRoute =
  WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport.update({
    id: '/catalog_/journey/$entityModule/$entityId',
    path: '/catalog/journey/$entityModule/$entityId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const storefrontShopProductsEntityModuleEntityIdRoute =
  storefrontShopProductsEntityModuleEntityIdRouteImport.update({
    id: '/shop_/products/$entityModule/$entityId',
    path: '/shop/products/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const storefrontShopBookEntityModuleEntityIdRoute =
  storefrontShopBookEntityModuleEntityIdRouteImport.update({
    id: '/shop_/book/$entityModule/$entityId',
    path: '/shop/book/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/pay': typeof PayRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/account': typeof WorkspaceAccountRoute
  '/channel-sync': typeof WorkspaceChannelSyncRoute
  '/flights': typeof WorkspaceFlightsRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/shop/composer': typeof storefrontShopComposerRoute
  '/bookings/new': typeof WorkspaceBookingsNewRoute
  '/bookings/compose': typeof WorkspaceBookingsComposeRoute
  '/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/cost-categories': typeof WorkspaceSettingsCostCategoriesRoute
  '/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/catalog/': typeof WorkspaceCatalogIndexRoute
  '/finance/': typeof WorkspaceFinanceIndexRoute
  '/legal/': typeof WorkspaceLegalIndexRoute
  '/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/finance/supplier-invoices/$id': typeof WorkspaceFinanceSupplierInvoicesIdRoute
  '/flights/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/finance/supplier-invoices/': typeof WorkspaceFinanceSupplierInvoicesIndexRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/catalog/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRoutesByTo {
  '/pay': typeof PayRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/account': typeof WorkspaceAccountRoute
  '/channel-sync': typeof WorkspaceChannelSyncRoute
  '/flights': typeof WorkspaceFlightsRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/': typeof WorkspaceIndexRoute
  '/shop/composer': typeof storefrontShopComposerRoute
  '/bookings/new': typeof WorkspaceBookingsNewRoute
  '/bookings/compose': typeof WorkspaceBookingsComposeRoute
  '/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/cost-categories': typeof WorkspaceSettingsCostCategoriesRoute
  '/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/catalog': typeof WorkspaceCatalogIndexRoute
  '/finance': typeof WorkspaceFinanceIndexRoute
  '/legal': typeof WorkspaceLegalIndexRoute
  '/notifications': typeof WorkspaceNotificationsIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/finance/supplier-invoices/$id': typeof WorkspaceFinanceSupplierInvoicesIdRoute
  '/flights/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/finance/supplier-invoices': typeof WorkspaceFinanceSupplierInvoicesIndexRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/catalog/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(storefront)': typeof storefrontRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/pay': typeof PayRoute
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(storefront)/shop': typeof storefrontShopRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/channel-sync': typeof WorkspaceChannelSyncRoute
  '/_workspace/flights': typeof WorkspaceFlightsRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay_/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/(storefront)/shop_/composer': typeof storefrontShopComposerRoute
  '/_workspace/bookings/new': typeof WorkspaceBookingsNewRoute
  '/_workspace/bookings_/compose': typeof WorkspaceBookingsComposeRoute
  '/_workspace/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/_workspace/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/_workspace/settings/cost-categories': typeof WorkspaceSettingsCostCategoriesRoute
  '/_workspace/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/_workspace/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/_workspace/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/_workspace/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/_workspace/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/_workspace/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/_workspace/settings/team': typeof WorkspaceSettingsTeamRoute
  '/_workspace/catalog/': typeof WorkspaceCatalogIndexRoute
  '/_workspace/finance/': typeof WorkspaceFinanceIndexRoute
  '/_workspace/legal/': typeof WorkspaceLegalIndexRoute
  '/_workspace/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/(storefront)/shop_/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/_workspace/finance/supplier-invoices/$id': typeof WorkspaceFinanceSupplierInvoicesIdRoute
  '/_workspace/flights_/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/_workspace/finance/supplier-invoices/': typeof WorkspaceFinanceSupplierInvoicesIndexRoute
  '/(storefront)/shop_/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/(storefront)/shop_/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/_workspace/catalog_/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pay'
    | '/settings'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/account'
    | '/channel-sync'
    | '/flights'
    | '/accountant/$token'
    | '/pay/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/shop/composer'
    | '/bookings/new'
    | '/bookings/compose'
    | '/settings/api-tokens'
    | '/settings/channels'
    | '/settings/cost-categories'
    | '/settings/operator'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/settings/taxes'
    | '/settings/team'
    | '/catalog/'
    | '/finance/'
    | '/legal/'
    | '/notifications/'
    | '/settings/'
    | '/shop/confirmation/$bookingId'
    | '/finance/supplier-invoices/$id'
    | '/flights/book/$offerId'
    | '/finance/supplier-invoices/'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
    | '/catalog/journey/$entityModule/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pay'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/account'
    | '/channel-sync'
    | '/flights'
    | '/accountant/$token'
    | '/pay/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/'
    | '/shop/composer'
    | '/bookings/new'
    | '/bookings/compose'
    | '/settings/api-tokens'
    | '/settings/channels'
    | '/settings/cost-categories'
    | '/settings/operator'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/settings/taxes'
    | '/settings/team'
    | '/catalog'
    | '/finance'
    | '/legal'
    | '/notifications'
    | '/settings'
    | '/shop/confirmation/$bookingId'
    | '/finance/supplier-invoices/$id'
    | '/flights/book/$offerId'
    | '/finance/supplier-invoices'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
    | '/catalog/journey/$entityModule/$entityId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(storefront)'
    | '/_workspace'
    | '/pay'
    | '/_workspace/settings'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(storefront)/shop'
    | '/_workspace/account'
    | '/_workspace/channel-sync'
    | '/_workspace/flights'
    | '/accountant/$token'
    | '/pay_/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/_workspace/'
    | '/(storefront)/shop_/composer'
    | '/_workspace/bookings/new'
    | '/_workspace/bookings_/compose'
    | '/_workspace/settings/api-tokens'
    | '/_workspace/settings/channels'
    | '/_workspace/settings/cost-categories'
    | '/_workspace/settings/operator'
    | '/_workspace/settings/price-catalogs'
    | '/_workspace/settings/pricing-categories'
    | '/_workspace/settings/product-tags'
    | '/_workspace/settings/product-types'
    | '/_workspace/settings/taxes'
    | '/_workspace/settings/team'
    | '/_workspace/catalog/'
    | '/_workspace/finance/'
    | '/_workspace/legal/'
    | '/_workspace/notifications/'
    | '/_workspace/settings/'
    | '/(storefront)/shop_/confirmation/$bookingId'
    | '/_workspace/finance/supplier-invoices/$id'
    | '/_workspace/flights_/book/$offerId'
    | '/_workspace/finance/supplier-invoices/'
    | '/(storefront)/shop_/book/$entityModule/$entityId'
    | '/(storefront)/shop_/products/$entityModule/$entityId'
    | '/_workspace/catalog_/journey/$entityModule/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  storefrontRouteRoute: typeof storefrontRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  PayRoute: typeof PayRoute
  AccountantTokenRoute: typeof AccountantTokenRoute
  PaySessionIdRoute: typeof PaySessionIdRoute
  ProposalQuoteVersionIdRoute: typeof ProposalQuoteVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)': {
      id: '/(storefront)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/proposal/$quoteVersionId': {
      id: '/proposal/$quoteVersionId'
      path: '/proposal/$quoteVersionId'
      fullPath: '/proposal/$quoteVersionId'
      preLoaderRoute: typeof ProposalQuoteVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay_/$sessionId': {
      id: '/pay_/$sessionId'
      path: '/pay/$sessionId'
      fullPath: '/pay/$sessionId'
      preLoaderRoute: typeof PaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/$token': {
      id: '/accountant/$token'
      path: '/accountant/$token'
      fullPath: '/accountant/$token'
      preLoaderRoute: typeof AccountantTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/flights': {
      id: '/_workspace/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof WorkspaceFlightsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/channel-sync': {
      id: '/_workspace/channel-sync'
      path: '/channel-sync'
      fullPath: '/channel-sync'
      preLoaderRoute: typeof WorkspaceChannelSyncRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop': {
      id: '/(storefront)/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof storefrontShopRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/notifications/': {
      id: '/_workspace/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof WorkspaceNotificationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/': {
      id: '/_workspace/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof WorkspaceLegalIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/': {
      id: '/_workspace/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof WorkspaceFinanceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/catalog/': {
      id: '/_workspace/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof WorkspaceCatalogIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/team': {
      id: '/_workspace/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof WorkspaceSettingsTeamRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/taxes': {
      id: '/_workspace/settings/taxes'
      path: '/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof WorkspaceSettingsTaxesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/product-types': {
      id: '/_workspace/settings/product-types'
      path: '/product-types'
      fullPath: '/settings/product-types'
      preLoaderRoute: typeof WorkspaceSettingsProductTypesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/product-tags': {
      id: '/_workspace/settings/product-tags'
      path: '/product-tags'
      fullPath: '/settings/product-tags'
      preLoaderRoute: typeof WorkspaceSettingsProductTagsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing-categories': {
      id: '/_workspace/settings/pricing-categories'
      path: '/pricing-categories'
      fullPath: '/settings/pricing-categories'
      preLoaderRoute: typeof WorkspaceSettingsPricingCategoriesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/price-catalogs': {
      id: '/_workspace/settings/price-catalogs'
      path: '/price-catalogs'
      fullPath: '/settings/price-catalogs'
      preLoaderRoute: typeof WorkspaceSettingsPriceCatalogsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/operator': {
      id: '/_workspace/settings/operator'
      path: '/operator'
      fullPath: '/settings/operator'
      preLoaderRoute: typeof WorkspaceSettingsOperatorRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/cost-categories': {
      id: '/_workspace/settings/cost-categories'
      path: '/cost-categories'
      fullPath: '/settings/cost-categories'
      preLoaderRoute: typeof WorkspaceSettingsCostCategoriesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/channels': {
      id: '/_workspace/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof WorkspaceSettingsChannelsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/api-tokens': {
      id: '/_workspace/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof WorkspaceSettingsApiTokensRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/bookings_/compose': {
      id: '/_workspace/bookings_/compose'
      path: '/bookings/compose'
      fullPath: '/bookings/compose'
      preLoaderRoute: typeof WorkspaceBookingsComposeRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/new': {
      id: '/_workspace/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof WorkspaceBookingsNewRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop_/composer': {
      id: '/(storefront)/shop_/composer'
      path: '/shop/composer'
      fullPath: '/shop/composer'
      preLoaderRoute: typeof storefrontShopComposerRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/_workspace/finance/supplier-invoices/': {
      id: '/_workspace/finance/supplier-invoices/'
      path: '/finance/supplier-invoices'
      fullPath: '/finance/supplier-invoices/'
      preLoaderRoute: typeof WorkspaceFinanceSupplierInvoicesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/flights_/book/$offerId': {
      id: '/_workspace/flights_/book/$offerId'
      path: '/flights/book/$offerId'
      fullPath: '/flights/book/$offerId'
      preLoaderRoute: typeof WorkspaceFlightsBookOfferIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/supplier-invoices/$id': {
      id: '/_workspace/finance/supplier-invoices/$id'
      path: '/finance/supplier-invoices/$id'
      fullPath: '/finance/supplier-invoices/$id'
      preLoaderRoute: typeof WorkspaceFinanceSupplierInvoicesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop_/confirmation/$bookingId': {
      id: '/(storefront)/shop_/confirmation/$bookingId'
      path: '/shop/confirmation/$bookingId'
      fullPath: '/shop/confirmation/$bookingId'
      preLoaderRoute: typeof storefrontShopConfirmationBookingIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/_workspace/catalog_/journey/$entityModule/$entityId': {
      id: '/_workspace/catalog_/journey/$entityModule/$entityId'
      path: '/catalog/journey/$entityModule/$entityId'
      fullPath: '/catalog/journey/$entityModule/$entityId'
      preLoaderRoute: typeof WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop_/products/$entityModule/$entityId': {
      id: '/(storefront)/shop_/products/$entityModule/$entityId'
      path: '/shop/products/$entityModule/$entityId'
      fullPath: '/shop/products/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopProductsEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/book/$entityModule/$entityId': {
      id: '/(storefront)/shop_/book/$entityModule/$entityId'
      path: '/shop/book/$entityModule/$entityId'
      fullPath: '/shop/book/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopBookEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface storefrontRouteRouteChildren {
  storefrontShopRoute: typeof storefrontShopRoute
  storefrontShopComposerRoute: typeof storefrontShopComposerRoute
  storefrontShopConfirmationBookingIdRoute: typeof storefrontShopConfirmationBookingIdRoute
  storefrontShopBookEntityModuleEntityIdRoute: typeof storefrontShopBookEntityModuleEntityIdRoute
  storefrontShopProductsEntityModuleEntityIdRoute: typeof storefrontShopProductsEntityModuleEntityIdRoute
}

const storefrontRouteRouteChildren: storefrontRouteRouteChildren = {
  storefrontShopRoute: storefrontShopRoute,
  storefrontShopComposerRoute: storefrontShopComposerRoute,
  storefrontShopConfirmationBookingIdRoute:
    storefrontShopConfirmationBookingIdRoute,
  storefrontShopBookEntityModuleEntityIdRoute:
    storefrontShopBookEntityModuleEntityIdRoute,
  storefrontShopProductsEntityModuleEntityIdRoute:
    storefrontShopProductsEntityModuleEntityIdRoute,
}

const storefrontRouteRouteWithChildren = storefrontRouteRoute._addFileChildren(
  storefrontRouteRouteChildren,
)

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsApiTokensRoute: typeof WorkspaceSettingsApiTokensRoute
  WorkspaceSettingsChannelsRoute: typeof WorkspaceSettingsChannelsRoute
  WorkspaceSettingsCostCategoriesRoute: typeof WorkspaceSettingsCostCategoriesRoute
  WorkspaceSettingsOperatorRoute: typeof WorkspaceSettingsOperatorRoute
  WorkspaceSettingsPriceCatalogsRoute: typeof WorkspaceSettingsPriceCatalogsRoute
  WorkspaceSettingsPricingCategoriesRoute: typeof WorkspaceSettingsPricingCategoriesRoute
  WorkspaceSettingsProductTagsRoute: typeof WorkspaceSettingsProductTagsRoute
  WorkspaceSettingsProductTypesRoute: typeof WorkspaceSettingsProductTypesRoute
  WorkspaceSettingsTaxesRoute: typeof WorkspaceSettingsTaxesRoute
  WorkspaceSettingsTeamRoute: typeof WorkspaceSettingsTeamRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsApiTokensRoute: WorkspaceSettingsApiTokensRoute,
    WorkspaceSettingsChannelsRoute: WorkspaceSettingsChannelsRoute,
    WorkspaceSettingsCostCategoriesRoute: WorkspaceSettingsCostCategoriesRoute,
    WorkspaceSettingsOperatorRoute: WorkspaceSettingsOperatorRoute,
    WorkspaceSettingsPriceCatalogsRoute: WorkspaceSettingsPriceCatalogsRoute,
    WorkspaceSettingsPricingCategoriesRoute:
      WorkspaceSettingsPricingCategoriesRoute,
    WorkspaceSettingsProductTagsRoute: WorkspaceSettingsProductTagsRoute,
    WorkspaceSettingsProductTypesRoute: WorkspaceSettingsProductTypesRoute,
    WorkspaceSettingsTaxesRoute: WorkspaceSettingsTaxesRoute,
    WorkspaceSettingsTeamRoute: WorkspaceSettingsTeamRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceChannelSyncRoute: typeof WorkspaceChannelSyncRoute
  WorkspaceFlightsRoute: typeof WorkspaceFlightsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceBookingsNewRoute: typeof WorkspaceBookingsNewRoute
  WorkspaceBookingsComposeRoute: typeof WorkspaceBookingsComposeRoute
  WorkspaceCatalogIndexRoute: typeof WorkspaceCatalogIndexRoute
  WorkspaceFinanceIndexRoute: typeof WorkspaceFinanceIndexRoute
  WorkspaceLegalIndexRoute: typeof WorkspaceLegalIndexRoute
  WorkspaceNotificationsIndexRoute: typeof WorkspaceNotificationsIndexRoute
  WorkspaceFinanceSupplierInvoicesIdRoute: typeof WorkspaceFinanceSupplierInvoicesIdRoute
  WorkspaceFlightsBookOfferIdRoute: typeof WorkspaceFlightsBookOfferIdRoute
  WorkspaceFinanceSupplierInvoicesIndexRoute: typeof WorkspaceFinanceSupplierInvoicesIndexRoute
  WorkspaceCatalogJourneyEntityModuleEntityIdRoute: typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceChannelSyncRoute: WorkspaceChannelSyncRoute,
  WorkspaceFlightsRoute: WorkspaceFlightsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceBookingsNewRoute: WorkspaceBookingsNewRoute,
  WorkspaceBookingsComposeRoute: WorkspaceBookingsComposeRoute,
  WorkspaceCatalogIndexRoute: WorkspaceCatalogIndexRoute,
  WorkspaceFinanceIndexRoute: WorkspaceFinanceIndexRoute,
  WorkspaceLegalIndexRoute: WorkspaceLegalIndexRoute,
  WorkspaceNotificationsIndexRoute: WorkspaceNotificationsIndexRoute,
  WorkspaceFinanceSupplierInvoicesIdRoute:
    WorkspaceFinanceSupplierInvoicesIdRoute,
  WorkspaceFlightsBookOfferIdRoute: WorkspaceFlightsBookOfferIdRoute,
  WorkspaceFinanceSupplierInvoicesIndexRoute:
    WorkspaceFinanceSupplierInvoicesIndexRoute,
  WorkspaceCatalogJourneyEntityModuleEntityIdRoute:
    WorkspaceCatalogJourneyEntityModuleEntityIdRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  storefrontRouteRoute: storefrontRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  PayRoute: PayRoute,
  AccountantTokenRoute: AccountantTokenRoute,
  PaySessionIdRoute: PaySessionIdRoute,
  ProposalQuoteVersionIdRoute: ProposalQuoteVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
