/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRouteImport } from './routes/pay'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as storefrontRouteRouteImport } from './routes/(storefront)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as PaySessionIdRouteImport } from './routes/pay_.$sessionId'
import { Route as WorkspaceFlightsRouteImport } from './routes/_workspace/flights'
import { Route as WorkspaceChannelSyncRouteImport } from './routes/_workspace/channel-sync'
import { Route as WorkspaceCatalogRouteImport } from './routes/_workspace/catalog'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as storefrontShopRouteImport } from './routes/(storefront)/shop'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceSuppliersIndexRouteImport } from './routes/_workspace/suppliers/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceResourcesIndexRouteImport } from './routes/_workspace/resources/index'
import { Route as WorkspacePromotionsIndexRouteImport } from './routes/_workspace/promotions/index'
import { Route as WorkspaceProductsIndexRouteImport } from './routes/_workspace/products/index'
import { Route as WorkspacePeopleIndexRouteImport } from './routes/_workspace/people/index'
import { Route as WorkspaceOrganizationsIndexRouteImport } from './routes/_workspace/organizations/index'
import { Route as WorkspaceNotificationsIndexRouteImport } from './routes/_workspace/notifications/index'
import { Route as WorkspaceLegalIndexRouteImport } from './routes/_workspace/legal/index'
import { Route as WorkspaceFinanceIndexRouteImport } from './routes/_workspace/finance/index'
import { Route as WorkspaceBookingsIndexRouteImport } from './routes/_workspace/bookings/index'
import { Route as WorkspaceAvailabilityIndexRouteImport } from './routes/_workspace/availability/index'
import { Route as WorkspaceActionLedgerIndexRouteImport } from './routes/_workspace/action-ledger/index'
import { Route as WorkspaceSuppliersIdRouteImport } from './routes/_workspace/suppliers/$id'
import { Route as WorkspaceSettingsTeamRouteImport } from './routes/_workspace/settings/team'
import { Route as WorkspaceSettingsTaxesRouteImport } from './routes/_workspace/settings/taxes'
import { Route as WorkspaceSettingsProductTypesRouteImport } from './routes/_workspace/settings/product-types'
import { Route as WorkspaceSettingsProductTagsRouteImport } from './routes/_workspace/settings/product-tags'
import { Route as WorkspaceSettingsPricingCategoriesRouteImport } from './routes/_workspace/settings/pricing-categories'
import { Route as WorkspaceSettingsPriceCatalogsRouteImport } from './routes/_workspace/settings/price-catalogs'
import { Route as WorkspaceSettingsOperatorRouteImport } from './routes/_workspace/settings/operator'
import { Route as WorkspaceSettingsChannelsRouteImport } from './routes/_workspace/settings/channels'
import { Route as WorkspaceSettingsApiTokensRouteImport } from './routes/_workspace/settings/api-tokens'
import { Route as WorkspaceResourcesIdRouteImport } from './routes/_workspace/resources/$id'
import { Route as WorkspaceProductsCategoriesRouteImport } from './routes/_workspace/products/categories'
import { Route as WorkspaceProductsIdRouteImport } from './routes/_workspace/products/$id'
import { Route as WorkspacePeopleIdRouteImport } from './routes/_workspace/people/$id'
import { Route as WorkspaceOrganizationsIdRouteImport } from './routes/_workspace/organizations/$id'
import { Route as WorkspaceNotificationsSettingsRouteImport } from './routes/_workspace/notifications/settings'
import { Route as WorkspaceNotificationsReminderRunsRouteImport } from './routes/_workspace/notifications/reminder-runs'
import { Route as WorkspaceNotificationsPreviewRouteImport } from './routes/_workspace/notifications/preview'
import { Route as WorkspaceNotificationsDeliveriesRouteImport } from './routes/_workspace/notifications/deliveries'
import { Route as WorkspaceBookingsIdRouteImport } from './routes/_workspace/bookings/$id'
import { Route as WorkspaceAvailabilityIdRouteImport } from './routes/_workspace/availability/$id'
import { Route as WorkspaceActionLedgerApprovalsRouteImport } from './routes/_workspace/action-ledger/approvals'
import { Route as WorkspaceNotificationsTemplatesIndexRouteImport } from './routes/_workspace/notifications/templates/index'
import { Route as WorkspaceNotificationsReminderRulesIndexRouteImport } from './routes/_workspace/notifications/reminder-rules/index'
import { Route as WorkspaceLegalTemplatesIndexRouteImport } from './routes/_workspace/legal/templates/index'
import { Route as WorkspaceLegalPoliciesIndexRouteImport } from './routes/_workspace/legal/policies/index'
import { Route as WorkspaceLegalNumberSeriesIndexRouteImport } from './routes/_workspace/legal/number-series/index'
import { Route as WorkspaceLegalContractsIndexRouteImport } from './routes/_workspace/legal/contracts/index'
import { Route as WorkspaceFinancePaymentsIndexRouteImport } from './routes/_workspace/finance/payments/index'
import { Route as WorkspaceFinanceInvoicesIndexRouteImport } from './routes/_workspace/finance/invoices/index'
import { Route as WorkspaceResourcesPoolsIdRouteImport } from './routes/_workspace/resources/pools/$id'
import { Route as WorkspaceResourcesAssignmentsIdRouteImport } from './routes/_workspace/resources/assignments/$id'
import { Route as WorkspaceResourcesAllocationsIdRouteImport } from './routes/_workspace/resources/allocations/$id'
import { Route as WorkspaceNotificationsTemplatesIdRouteImport } from './routes/_workspace/notifications/templates/$id'
import { Route as WorkspaceNotificationsReminderRulesIdRouteImport } from './routes/_workspace/notifications/reminder-rules/$id'
import { Route as WorkspaceLegalTemplatesIdRouteImport } from './routes/_workspace/legal/templates/$id'
import { Route as WorkspaceLegalPoliciesIdRouteImport } from './routes/_workspace/legal/policies/$id'
import { Route as WorkspaceLegalContractsIdRouteImport } from './routes/_workspace/legal/contracts/$id'
import { Route as WorkspaceFlightsBookOfferIdRouteImport } from './routes/_workspace/flights_.book.$offerId'
import { Route as WorkspaceFinancePaymentsIdRouteImport } from './routes/_workspace/finance/payments/$id'
import { Route as WorkspaceFinanceInvoicesIdRouteImport } from './routes/_workspace/finance/invoices/$id'
import { Route as WorkspaceAvailabilityStartTimesIdRouteImport } from './routes/_workspace/availability/start-times/$id'
import { Route as WorkspaceAvailabilityRulesIdRouteImport } from './routes/_workspace/availability/rules/$id'
import { Route as storefrontShopConfirmationBookingIdRouteImport } from './routes/(storefront)/shop_.confirmation.$bookingId'
import { Route as WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport } from './routes/_workspace/catalog_.journey.$entityModule.$entityId'
import { Route as WorkspaceCatalogBookEntityModuleEntityIdRouteImport } from './routes/_workspace/catalog_.book.$entityModule.$entityId'
import { Route as storefrontShopProductsEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.products.$entityModule.$entityId'
import { Route as storefrontShopBookEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.book.$entityModule.$entityId'

const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontRouteRoute = storefrontRouteRouteImport.update({
  id: '/(storefront)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const PaySessionIdRoute = PaySessionIdRouteImport.update({
  id: '/pay_/$sessionId',
  path: '/pay/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceFlightsRoute = WorkspaceFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceChannelSyncRoute = WorkspaceChannelSyncRouteImport.update({
  id: '/channel-sync',
  path: '/channel-sync',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceCatalogRoute = WorkspaceCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const storefrontShopRoute = storefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSuppliersIndexRoute = WorkspaceSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceResourcesIndexRoute = WorkspaceResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePromotionsIndexRoute =
  WorkspacePromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProductsIndexRoute = WorkspaceProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIndexRoute = WorkspacePeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIndexRoute =
  WorkspaceOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsIndexRoute =
  WorkspaceNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalIndexRoute = WorkspaceLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceFinanceIndexRoute = WorkspaceFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingsIndexRoute = WorkspaceBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIndexRoute =
  WorkspaceAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceActionLedgerIndexRoute =
  WorkspaceActionLedgerIndexRouteImport.update({
    id: '/action-ledger/',
    path: '/action-ledger/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSuppliersIdRoute = WorkspaceSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsTeamRoute = WorkspaceSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsTaxesRoute = WorkspaceSettingsTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsProductTypesRoute =
  WorkspaceSettingsProductTypesRouteImport.update({
    id: '/product-types',
    path: '/product-types',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsProductTagsRoute =
  WorkspaceSettingsProductTagsRouteImport.update({
    id: '/product-tags',
    path: '/product-tags',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCategoriesRoute =
  WorkspaceSettingsPricingCategoriesRouteImport.update({
    id: '/pricing-categories',
    path: '/pricing-categories',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPriceCatalogsRoute =
  WorkspaceSettingsPriceCatalogsRouteImport.update({
    id: '/price-catalogs',
    path: '/price-catalogs',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsOperatorRoute =
  WorkspaceSettingsOperatorRouteImport.update({
    id: '/operator',
    path: '/operator',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsChannelsRoute =
  WorkspaceSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsApiTokensRoute =
  WorkspaceSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceResourcesIdRoute = WorkspaceResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsCategoriesRoute =
  WorkspaceProductsCategoriesRouteImport.update({
    id: '/products/categories',
    path: '/products/categories',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProductsIdRoute = WorkspaceProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIdRoute = WorkspacePeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIdRoute =
  WorkspaceOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsSettingsRoute =
  WorkspaceNotificationsSettingsRouteImport.update({
    id: '/notifications/settings',
    path: '/notifications/settings',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsReminderRunsRoute =
  WorkspaceNotificationsReminderRunsRouteImport.update({
    id: '/notifications/reminder-runs',
    path: '/notifications/reminder-runs',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsPreviewRoute =
  WorkspaceNotificationsPreviewRouteImport.update({
    id: '/notifications/preview',
    path: '/notifications/preview',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsDeliveriesRoute =
  WorkspaceNotificationsDeliveriesRouteImport.update({
    id: '/notifications/deliveries',
    path: '/notifications/deliveries',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceBookingsIdRoute = WorkspaceBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIdRoute = WorkspaceAvailabilityIdRouteImport.update({
  id: '/availability/$id',
  path: '/availability/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceActionLedgerApprovalsRoute =
  WorkspaceActionLedgerApprovalsRouteImport.update({
    id: '/action-ledger/approvals',
    path: '/action-ledger/approvals',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsTemplatesIndexRoute =
  WorkspaceNotificationsTemplatesIndexRouteImport.update({
    id: '/notifications/templates/',
    path: '/notifications/templates/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsReminderRulesIndexRoute =
  WorkspaceNotificationsReminderRulesIndexRouteImport.update({
    id: '/notifications/reminder-rules/',
    path: '/notifications/reminder-rules/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalTemplatesIndexRoute =
  WorkspaceLegalTemplatesIndexRouteImport.update({
    id: '/legal/templates/',
    path: '/legal/templates/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalPoliciesIndexRoute =
  WorkspaceLegalPoliciesIndexRouteImport.update({
    id: '/legal/policies/',
    path: '/legal/policies/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalNumberSeriesIndexRoute =
  WorkspaceLegalNumberSeriesIndexRouteImport.update({
    id: '/legal/number-series/',
    path: '/legal/number-series/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalContractsIndexRoute =
  WorkspaceLegalContractsIndexRouteImport.update({
    id: '/legal/contracts/',
    path: '/legal/contracts/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinancePaymentsIndexRoute =
  WorkspaceFinancePaymentsIndexRouteImport.update({
    id: '/finance/payments/',
    path: '/finance/payments/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceInvoicesIndexRoute =
  WorkspaceFinanceInvoicesIndexRouteImport.update({
    id: '/finance/invoices/',
    path: '/finance/invoices/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesPoolsIdRoute =
  WorkspaceResourcesPoolsIdRouteImport.update({
    id: '/resources/pools/$id',
    path: '/resources/pools/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAssignmentsIdRoute =
  WorkspaceResourcesAssignmentsIdRouteImport.update({
    id: '/resources/assignments/$id',
    path: '/resources/assignments/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAllocationsIdRoute =
  WorkspaceResourcesAllocationsIdRouteImport.update({
    id: '/resources/allocations/$id',
    path: '/resources/allocations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsTemplatesIdRoute =
  WorkspaceNotificationsTemplatesIdRouteImport.update({
    id: '/notifications/templates/$id',
    path: '/notifications/templates/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsReminderRulesIdRoute =
  WorkspaceNotificationsReminderRulesIdRouteImport.update({
    id: '/notifications/reminder-rules/$id',
    path: '/notifications/reminder-rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalTemplatesIdRoute =
  WorkspaceLegalTemplatesIdRouteImport.update({
    id: '/legal/templates/$id',
    path: '/legal/templates/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalPoliciesIdRoute =
  WorkspaceLegalPoliciesIdRouteImport.update({
    id: '/legal/policies/$id',
    path: '/legal/policies/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalContractsIdRoute =
  WorkspaceLegalContractsIdRouteImport.update({
    id: '/legal/contracts/$id',
    path: '/legal/contracts/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFlightsBookOfferIdRoute =
  WorkspaceFlightsBookOfferIdRouteImport.update({
    id: '/flights_/book/$offerId',
    path: '/flights/book/$offerId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinancePaymentsIdRoute =
  WorkspaceFinancePaymentsIdRouteImport.update({
    id: '/finance/payments/$id',
    path: '/finance/payments/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceInvoicesIdRoute =
  WorkspaceFinanceInvoicesIdRouteImport.update({
    id: '/finance/invoices/$id',
    path: '/finance/invoices/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityStartTimesIdRoute =
  WorkspaceAvailabilityStartTimesIdRouteImport.update({
    id: '/availability/start-times/$id',
    path: '/availability/start-times/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityRulesIdRoute =
  WorkspaceAvailabilityRulesIdRouteImport.update({
    id: '/availability/rules/$id',
    path: '/availability/rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const storefrontShopConfirmationBookingIdRoute =
  storefrontShopConfirmationBookingIdRouteImport.update({
    id: '/shop_/confirmation/$bookingId',
    path: '/shop/confirmation/$bookingId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const WorkspaceCatalogJourneyEntityModuleEntityIdRoute =
  WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport.update({
    id: '/catalog_/journey/$entityModule/$entityId',
    path: '/catalog/journey/$entityModule/$entityId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceCatalogBookEntityModuleEntityIdRoute =
  WorkspaceCatalogBookEntityModuleEntityIdRouteImport.update({
    id: '/catalog_/book/$entityModule/$entityId',
    path: '/catalog/book/$entityModule/$entityId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const storefrontShopProductsEntityModuleEntityIdRoute =
  storefrontShopProductsEntityModuleEntityIdRouteImport.update({
    id: '/shop_/products/$entityModule/$entityId',
    path: '/shop/products/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const storefrontShopBookEntityModuleEntityIdRoute =
  storefrontShopBookEntityModuleEntityIdRouteImport.update({
    id: '/shop_/book/$entityModule/$entityId',
    path: '/shop/book/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/pay': typeof PayRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/account': typeof WorkspaceAccountRoute
  '/catalog': typeof WorkspaceCatalogRoute
  '/channel-sync': typeof WorkspaceChannelSyncRoute
  '/flights': typeof WorkspaceFlightsRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/action-ledger/approvals': typeof WorkspaceActionLedgerApprovalsRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/notifications/preview': typeof WorkspaceNotificationsPreviewRoute
  '/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/notifications/settings': typeof WorkspaceNotificationsSettingsRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/action-ledger/': typeof WorkspaceActionLedgerIndexRoute
  '/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/bookings/': typeof WorkspaceBookingsIndexRoute
  '/finance/': typeof WorkspaceFinanceIndexRoute
  '/legal/': typeof WorkspaceLegalIndexRoute
  '/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/people/': typeof WorkspacePeopleIndexRoute
  '/products/': typeof WorkspaceProductsIndexRoute
  '/promotions/': typeof WorkspacePromotionsIndexRoute
  '/resources/': typeof WorkspaceResourcesIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/finance/payments/$id': typeof WorkspaceFinancePaymentsIdRoute
  '/flights/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/legal/templates/$id': typeof WorkspaceLegalTemplatesIdRoute
  '/notifications/reminder-rules/$id': typeof WorkspaceNotificationsReminderRulesIdRoute
  '/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/finance/invoices/': typeof WorkspaceFinanceInvoicesIndexRoute
  '/finance/payments/': typeof WorkspaceFinancePaymentsIndexRoute
  '/legal/contracts/': typeof WorkspaceLegalContractsIndexRoute
  '/legal/number-series/': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/legal/policies/': typeof WorkspaceLegalPoliciesIndexRoute
  '/legal/templates/': typeof WorkspaceLegalTemplatesIndexRoute
  '/notifications/reminder-rules/': typeof WorkspaceNotificationsReminderRulesIndexRoute
  '/notifications/templates/': typeof WorkspaceNotificationsTemplatesIndexRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/catalog/book/$entityModule/$entityId': typeof WorkspaceCatalogBookEntityModuleEntityIdRoute
  '/catalog/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRoutesByTo {
  '/pay': typeof PayRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/account': typeof WorkspaceAccountRoute
  '/catalog': typeof WorkspaceCatalogRoute
  '/channel-sync': typeof WorkspaceChannelSyncRoute
  '/flights': typeof WorkspaceFlightsRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/': typeof WorkspaceIndexRoute
  '/action-ledger/approvals': typeof WorkspaceActionLedgerApprovalsRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/notifications/preview': typeof WorkspaceNotificationsPreviewRoute
  '/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/notifications/settings': typeof WorkspaceNotificationsSettingsRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/action-ledger': typeof WorkspaceActionLedgerIndexRoute
  '/availability': typeof WorkspaceAvailabilityIndexRoute
  '/bookings': typeof WorkspaceBookingsIndexRoute
  '/finance': typeof WorkspaceFinanceIndexRoute
  '/legal': typeof WorkspaceLegalIndexRoute
  '/notifications': typeof WorkspaceNotificationsIndexRoute
  '/organizations': typeof WorkspaceOrganizationsIndexRoute
  '/people': typeof WorkspacePeopleIndexRoute
  '/products': typeof WorkspaceProductsIndexRoute
  '/promotions': typeof WorkspacePromotionsIndexRoute
  '/resources': typeof WorkspaceResourcesIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/suppliers': typeof WorkspaceSuppliersIndexRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/finance/payments/$id': typeof WorkspaceFinancePaymentsIdRoute
  '/flights/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/legal/templates/$id': typeof WorkspaceLegalTemplatesIdRoute
  '/notifications/reminder-rules/$id': typeof WorkspaceNotificationsReminderRulesIdRoute
  '/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/finance/invoices': typeof WorkspaceFinanceInvoicesIndexRoute
  '/finance/payments': typeof WorkspaceFinancePaymentsIndexRoute
  '/legal/contracts': typeof WorkspaceLegalContractsIndexRoute
  '/legal/number-series': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/legal/policies': typeof WorkspaceLegalPoliciesIndexRoute
  '/legal/templates': typeof WorkspaceLegalTemplatesIndexRoute
  '/notifications/reminder-rules': typeof WorkspaceNotificationsReminderRulesIndexRoute
  '/notifications/templates': typeof WorkspaceNotificationsTemplatesIndexRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/catalog/book/$entityModule/$entityId': typeof WorkspaceCatalogBookEntityModuleEntityIdRoute
  '/catalog/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(storefront)': typeof storefrontRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/pay': typeof PayRoute
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(storefront)/shop': typeof storefrontShopRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/catalog': typeof WorkspaceCatalogRoute
  '/_workspace/channel-sync': typeof WorkspaceChannelSyncRoute
  '/_workspace/flights': typeof WorkspaceFlightsRoute
  '/pay_/$sessionId': typeof PaySessionIdRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/action-ledger/approvals': typeof WorkspaceActionLedgerApprovalsRoute
  '/_workspace/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/_workspace/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/_workspace/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/_workspace/notifications/preview': typeof WorkspaceNotificationsPreviewRoute
  '/_workspace/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/_workspace/notifications/settings': typeof WorkspaceNotificationsSettingsRoute
  '/_workspace/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/_workspace/people/$id': typeof WorkspacePeopleIdRoute
  '/_workspace/products/$id': typeof WorkspaceProductsIdRoute
  '/_workspace/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/_workspace/resources/$id': typeof WorkspaceResourcesIdRoute
  '/_workspace/settings/api-tokens': typeof WorkspaceSettingsApiTokensRoute
  '/_workspace/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/_workspace/settings/operator': typeof WorkspaceSettingsOperatorRoute
  '/_workspace/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/_workspace/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/_workspace/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/_workspace/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/_workspace/settings/taxes': typeof WorkspaceSettingsTaxesRoute
  '/_workspace/settings/team': typeof WorkspaceSettingsTeamRoute
  '/_workspace/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/_workspace/action-ledger/': typeof WorkspaceActionLedgerIndexRoute
  '/_workspace/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/_workspace/bookings/': typeof WorkspaceBookingsIndexRoute
  '/_workspace/finance/': typeof WorkspaceFinanceIndexRoute
  '/_workspace/legal/': typeof WorkspaceLegalIndexRoute
  '/_workspace/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/_workspace/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/_workspace/people/': typeof WorkspacePeopleIndexRoute
  '/_workspace/products/': typeof WorkspaceProductsIndexRoute
  '/_workspace/promotions/': typeof WorkspacePromotionsIndexRoute
  '/_workspace/resources/': typeof WorkspaceResourcesIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/_workspace/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/(storefront)/shop_/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/_workspace/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/_workspace/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/_workspace/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/_workspace/finance/payments/$id': typeof WorkspaceFinancePaymentsIdRoute
  '/_workspace/flights_/book/$offerId': typeof WorkspaceFlightsBookOfferIdRoute
  '/_workspace/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/_workspace/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/_workspace/legal/templates/$id': typeof WorkspaceLegalTemplatesIdRoute
  '/_workspace/notifications/reminder-rules/$id': typeof WorkspaceNotificationsReminderRulesIdRoute
  '/_workspace/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/_workspace/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/_workspace/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/_workspace/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/_workspace/finance/invoices/': typeof WorkspaceFinanceInvoicesIndexRoute
  '/_workspace/finance/payments/': typeof WorkspaceFinancePaymentsIndexRoute
  '/_workspace/legal/contracts/': typeof WorkspaceLegalContractsIndexRoute
  '/_workspace/legal/number-series/': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/_workspace/legal/policies/': typeof WorkspaceLegalPoliciesIndexRoute
  '/_workspace/legal/templates/': typeof WorkspaceLegalTemplatesIndexRoute
  '/_workspace/notifications/reminder-rules/': typeof WorkspaceNotificationsReminderRulesIndexRoute
  '/_workspace/notifications/templates/': typeof WorkspaceNotificationsTemplatesIndexRoute
  '/(storefront)/shop_/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/(storefront)/shop_/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
  '/_workspace/catalog_/book/$entityModule/$entityId': typeof WorkspaceCatalogBookEntityModuleEntityIdRoute
  '/_workspace/catalog_/journey/$entityModule/$entityId': typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pay'
    | '/settings'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/account'
    | '/catalog'
    | '/channel-sync'
    | '/flights'
    | '/pay/$sessionId'
    | '/action-ledger/approvals'
    | '/availability/$id'
    | '/bookings/$id'
    | '/notifications/deliveries'
    | '/notifications/preview'
    | '/notifications/reminder-runs'
    | '/notifications/settings'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/products/categories'
    | '/resources/$id'
    | '/settings/api-tokens'
    | '/settings/channels'
    | '/settings/operator'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/settings/taxes'
    | '/settings/team'
    | '/suppliers/$id'
    | '/action-ledger/'
    | '/availability/'
    | '/bookings/'
    | '/finance/'
    | '/legal/'
    | '/notifications/'
    | '/organizations/'
    | '/people/'
    | '/products/'
    | '/promotions/'
    | '/resources/'
    | '/settings/'
    | '/suppliers/'
    | '/shop/confirmation/$bookingId'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/finance/invoices/$id'
    | '/finance/payments/$id'
    | '/flights/book/$offerId'
    | '/legal/contracts/$id'
    | '/legal/policies/$id'
    | '/legal/templates/$id'
    | '/notifications/reminder-rules/$id'
    | '/notifications/templates/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/finance/invoices/'
    | '/finance/payments/'
    | '/legal/contracts/'
    | '/legal/number-series/'
    | '/legal/policies/'
    | '/legal/templates/'
    | '/notifications/reminder-rules/'
    | '/notifications/templates/'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
    | '/catalog/book/$entityModule/$entityId'
    | '/catalog/journey/$entityModule/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pay'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/account'
    | '/catalog'
    | '/channel-sync'
    | '/flights'
    | '/pay/$sessionId'
    | '/'
    | '/action-ledger/approvals'
    | '/availability/$id'
    | '/bookings/$id'
    | '/notifications/deliveries'
    | '/notifications/preview'
    | '/notifications/reminder-runs'
    | '/notifications/settings'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/products/categories'
    | '/resources/$id'
    | '/settings/api-tokens'
    | '/settings/channels'
    | '/settings/operator'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/settings/taxes'
    | '/settings/team'
    | '/suppliers/$id'
    | '/action-ledger'
    | '/availability'
    | '/bookings'
    | '/finance'
    | '/legal'
    | '/notifications'
    | '/organizations'
    | '/people'
    | '/products'
    | '/promotions'
    | '/resources'
    | '/settings'
    | '/suppliers'
    | '/shop/confirmation/$bookingId'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/finance/invoices/$id'
    | '/finance/payments/$id'
    | '/flights/book/$offerId'
    | '/legal/contracts/$id'
    | '/legal/policies/$id'
    | '/legal/templates/$id'
    | '/notifications/reminder-rules/$id'
    | '/notifications/templates/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/finance/invoices'
    | '/finance/payments'
    | '/legal/contracts'
    | '/legal/number-series'
    | '/legal/policies'
    | '/legal/templates'
    | '/notifications/reminder-rules'
    | '/notifications/templates'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
    | '/catalog/book/$entityModule/$entityId'
    | '/catalog/journey/$entityModule/$entityId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(storefront)'
    | '/_workspace'
    | '/pay'
    | '/_workspace/settings'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(storefront)/shop'
    | '/_workspace/account'
    | '/_workspace/catalog'
    | '/_workspace/channel-sync'
    | '/_workspace/flights'
    | '/pay_/$sessionId'
    | '/_workspace/'
    | '/_workspace/action-ledger/approvals'
    | '/_workspace/availability/$id'
    | '/_workspace/bookings/$id'
    | '/_workspace/notifications/deliveries'
    | '/_workspace/notifications/preview'
    | '/_workspace/notifications/reminder-runs'
    | '/_workspace/notifications/settings'
    | '/_workspace/organizations/$id'
    | '/_workspace/people/$id'
    | '/_workspace/products/$id'
    | '/_workspace/products/categories'
    | '/_workspace/resources/$id'
    | '/_workspace/settings/api-tokens'
    | '/_workspace/settings/channels'
    | '/_workspace/settings/operator'
    | '/_workspace/settings/price-catalogs'
    | '/_workspace/settings/pricing-categories'
    | '/_workspace/settings/product-tags'
    | '/_workspace/settings/product-types'
    | '/_workspace/settings/taxes'
    | '/_workspace/settings/team'
    | '/_workspace/suppliers/$id'
    | '/_workspace/action-ledger/'
    | '/_workspace/availability/'
    | '/_workspace/bookings/'
    | '/_workspace/finance/'
    | '/_workspace/legal/'
    | '/_workspace/notifications/'
    | '/_workspace/organizations/'
    | '/_workspace/people/'
    | '/_workspace/products/'
    | '/_workspace/promotions/'
    | '/_workspace/resources/'
    | '/_workspace/settings/'
    | '/_workspace/suppliers/'
    | '/(storefront)/shop_/confirmation/$bookingId'
    | '/_workspace/availability/rules/$id'
    | '/_workspace/availability/start-times/$id'
    | '/_workspace/finance/invoices/$id'
    | '/_workspace/finance/payments/$id'
    | '/_workspace/flights_/book/$offerId'
    | '/_workspace/legal/contracts/$id'
    | '/_workspace/legal/policies/$id'
    | '/_workspace/legal/templates/$id'
    | '/_workspace/notifications/reminder-rules/$id'
    | '/_workspace/notifications/templates/$id'
    | '/_workspace/resources/allocations/$id'
    | '/_workspace/resources/assignments/$id'
    | '/_workspace/resources/pools/$id'
    | '/_workspace/finance/invoices/'
    | '/_workspace/finance/payments/'
    | '/_workspace/legal/contracts/'
    | '/_workspace/legal/number-series/'
    | '/_workspace/legal/policies/'
    | '/_workspace/legal/templates/'
    | '/_workspace/notifications/reminder-rules/'
    | '/_workspace/notifications/templates/'
    | '/(storefront)/shop_/book/$entityModule/$entityId'
    | '/(storefront)/shop_/products/$entityModule/$entityId'
    | '/_workspace/catalog_/book/$entityModule/$entityId'
    | '/_workspace/catalog_/journey/$entityModule/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  storefrontRouteRoute: typeof storefrontRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  PayRoute: typeof PayRoute
  PaySessionIdRoute: typeof PaySessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)': {
      id: '/(storefront)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/pay_/$sessionId': {
      id: '/pay_/$sessionId'
      path: '/pay/$sessionId'
      fullPath: '/pay/$sessionId'
      preLoaderRoute: typeof PaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/flights': {
      id: '/_workspace/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof WorkspaceFlightsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/channel-sync': {
      id: '/_workspace/channel-sync'
      path: '/channel-sync'
      fullPath: '/channel-sync'
      preLoaderRoute: typeof WorkspaceChannelSyncRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/catalog': {
      id: '/_workspace/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof WorkspaceCatalogRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop': {
      id: '/(storefront)/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof storefrontShopRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/': {
      id: '/_workspace/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof WorkspaceSuppliersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/': {
      id: '/_workspace/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof WorkspaceResourcesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/promotions/': {
      id: '/_workspace/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof WorkspacePromotionsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/': {
      id: '/_workspace/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof WorkspaceProductsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/': {
      id: '/_workspace/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof WorkspacePeopleIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/': {
      id: '/_workspace/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof WorkspaceOrganizationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/': {
      id: '/_workspace/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof WorkspaceNotificationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/': {
      id: '/_workspace/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof WorkspaceLegalIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/': {
      id: '/_workspace/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof WorkspaceFinanceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/': {
      id: '/_workspace/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof WorkspaceBookingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/': {
      id: '/_workspace/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof WorkspaceAvailabilityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/action-ledger/': {
      id: '/_workspace/action-ledger/'
      path: '/action-ledger'
      fullPath: '/action-ledger/'
      preLoaderRoute: typeof WorkspaceActionLedgerIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/$id': {
      id: '/_workspace/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof WorkspaceSuppliersIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/team': {
      id: '/_workspace/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof WorkspaceSettingsTeamRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/taxes': {
      id: '/_workspace/settings/taxes'
      path: '/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof WorkspaceSettingsTaxesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/product-types': {
      id: '/_workspace/settings/product-types'
      path: '/product-types'
      fullPath: '/settings/product-types'
      preLoaderRoute: typeof WorkspaceSettingsProductTypesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/product-tags': {
      id: '/_workspace/settings/product-tags'
      path: '/product-tags'
      fullPath: '/settings/product-tags'
      preLoaderRoute: typeof WorkspaceSettingsProductTagsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing-categories': {
      id: '/_workspace/settings/pricing-categories'
      path: '/pricing-categories'
      fullPath: '/settings/pricing-categories'
      preLoaderRoute: typeof WorkspaceSettingsPricingCategoriesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/price-catalogs': {
      id: '/_workspace/settings/price-catalogs'
      path: '/price-catalogs'
      fullPath: '/settings/price-catalogs'
      preLoaderRoute: typeof WorkspaceSettingsPriceCatalogsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/operator': {
      id: '/_workspace/settings/operator'
      path: '/operator'
      fullPath: '/settings/operator'
      preLoaderRoute: typeof WorkspaceSettingsOperatorRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/channels': {
      id: '/_workspace/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof WorkspaceSettingsChannelsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/api-tokens': {
      id: '/_workspace/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof WorkspaceSettingsApiTokensRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/$id': {
      id: '/_workspace/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof WorkspaceResourcesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/categories': {
      id: '/_workspace/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof WorkspaceProductsCategoriesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/$id': {
      id: '/_workspace/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof WorkspaceProductsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/$id': {
      id: '/_workspace/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof WorkspacePeopleIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/$id': {
      id: '/_workspace/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof WorkspaceOrganizationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/settings': {
      id: '/_workspace/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof WorkspaceNotificationsSettingsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/reminder-runs': {
      id: '/_workspace/notifications/reminder-runs'
      path: '/notifications/reminder-runs'
      fullPath: '/notifications/reminder-runs'
      preLoaderRoute: typeof WorkspaceNotificationsReminderRunsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/preview': {
      id: '/_workspace/notifications/preview'
      path: '/notifications/preview'
      fullPath: '/notifications/preview'
      preLoaderRoute: typeof WorkspaceNotificationsPreviewRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/deliveries': {
      id: '/_workspace/notifications/deliveries'
      path: '/notifications/deliveries'
      fullPath: '/notifications/deliveries'
      preLoaderRoute: typeof WorkspaceNotificationsDeliveriesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/$id': {
      id: '/_workspace/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof WorkspaceBookingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/$id': {
      id: '/_workspace/availability/$id'
      path: '/availability/$id'
      fullPath: '/availability/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/action-ledger/approvals': {
      id: '/_workspace/action-ledger/approvals'
      path: '/action-ledger/approvals'
      fullPath: '/action-ledger/approvals'
      preLoaderRoute: typeof WorkspaceActionLedgerApprovalsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/templates/': {
      id: '/_workspace/notifications/templates/'
      path: '/notifications/templates'
      fullPath: '/notifications/templates/'
      preLoaderRoute: typeof WorkspaceNotificationsTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/reminder-rules/': {
      id: '/_workspace/notifications/reminder-rules/'
      path: '/notifications/reminder-rules'
      fullPath: '/notifications/reminder-rules/'
      preLoaderRoute: typeof WorkspaceNotificationsReminderRulesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/templates/': {
      id: '/_workspace/legal/templates/'
      path: '/legal/templates'
      fullPath: '/legal/templates/'
      preLoaderRoute: typeof WorkspaceLegalTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/policies/': {
      id: '/_workspace/legal/policies/'
      path: '/legal/policies'
      fullPath: '/legal/policies/'
      preLoaderRoute: typeof WorkspaceLegalPoliciesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/number-series/': {
      id: '/_workspace/legal/number-series/'
      path: '/legal/number-series'
      fullPath: '/legal/number-series/'
      preLoaderRoute: typeof WorkspaceLegalNumberSeriesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/contracts/': {
      id: '/_workspace/legal/contracts/'
      path: '/legal/contracts'
      fullPath: '/legal/contracts/'
      preLoaderRoute: typeof WorkspaceLegalContractsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/payments/': {
      id: '/_workspace/finance/payments/'
      path: '/finance/payments'
      fullPath: '/finance/payments/'
      preLoaderRoute: typeof WorkspaceFinancePaymentsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/invoices/': {
      id: '/_workspace/finance/invoices/'
      path: '/finance/invoices'
      fullPath: '/finance/invoices/'
      preLoaderRoute: typeof WorkspaceFinanceInvoicesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/pools/$id': {
      id: '/_workspace/resources/pools/$id'
      path: '/resources/pools/$id'
      fullPath: '/resources/pools/$id'
      preLoaderRoute: typeof WorkspaceResourcesPoolsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/assignments/$id': {
      id: '/_workspace/resources/assignments/$id'
      path: '/resources/assignments/$id'
      fullPath: '/resources/assignments/$id'
      preLoaderRoute: typeof WorkspaceResourcesAssignmentsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/allocations/$id': {
      id: '/_workspace/resources/allocations/$id'
      path: '/resources/allocations/$id'
      fullPath: '/resources/allocations/$id'
      preLoaderRoute: typeof WorkspaceResourcesAllocationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/templates/$id': {
      id: '/_workspace/notifications/templates/$id'
      path: '/notifications/templates/$id'
      fullPath: '/notifications/templates/$id'
      preLoaderRoute: typeof WorkspaceNotificationsTemplatesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/reminder-rules/$id': {
      id: '/_workspace/notifications/reminder-rules/$id'
      path: '/notifications/reminder-rules/$id'
      fullPath: '/notifications/reminder-rules/$id'
      preLoaderRoute: typeof WorkspaceNotificationsReminderRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/templates/$id': {
      id: '/_workspace/legal/templates/$id'
      path: '/legal/templates/$id'
      fullPath: '/legal/templates/$id'
      preLoaderRoute: typeof WorkspaceLegalTemplatesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/policies/$id': {
      id: '/_workspace/legal/policies/$id'
      path: '/legal/policies/$id'
      fullPath: '/legal/policies/$id'
      preLoaderRoute: typeof WorkspaceLegalPoliciesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/contracts/$id': {
      id: '/_workspace/legal/contracts/$id'
      path: '/legal/contracts/$id'
      fullPath: '/legal/contracts/$id'
      preLoaderRoute: typeof WorkspaceLegalContractsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/flights_/book/$offerId': {
      id: '/_workspace/flights_/book/$offerId'
      path: '/flights/book/$offerId'
      fullPath: '/flights/book/$offerId'
      preLoaderRoute: typeof WorkspaceFlightsBookOfferIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/payments/$id': {
      id: '/_workspace/finance/payments/$id'
      path: '/finance/payments/$id'
      fullPath: '/finance/payments/$id'
      preLoaderRoute: typeof WorkspaceFinancePaymentsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/invoices/$id': {
      id: '/_workspace/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof WorkspaceFinanceInvoicesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/start-times/$id': {
      id: '/_workspace/availability/start-times/$id'
      path: '/availability/start-times/$id'
      fullPath: '/availability/start-times/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityStartTimesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/rules/$id': {
      id: '/_workspace/availability/rules/$id'
      path: '/availability/rules/$id'
      fullPath: '/availability/rules/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop_/confirmation/$bookingId': {
      id: '/(storefront)/shop_/confirmation/$bookingId'
      path: '/shop/confirmation/$bookingId'
      fullPath: '/shop/confirmation/$bookingId'
      preLoaderRoute: typeof storefrontShopConfirmationBookingIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/_workspace/catalog_/journey/$entityModule/$entityId': {
      id: '/_workspace/catalog_/journey/$entityModule/$entityId'
      path: '/catalog/journey/$entityModule/$entityId'
      fullPath: '/catalog/journey/$entityModule/$entityId'
      preLoaderRoute: typeof WorkspaceCatalogJourneyEntityModuleEntityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/catalog_/book/$entityModule/$entityId': {
      id: '/_workspace/catalog_/book/$entityModule/$entityId'
      path: '/catalog/book/$entityModule/$entityId'
      fullPath: '/catalog/book/$entityModule/$entityId'
      preLoaderRoute: typeof WorkspaceCatalogBookEntityModuleEntityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(storefront)/shop_/products/$entityModule/$entityId': {
      id: '/(storefront)/shop_/products/$entityModule/$entityId'
      path: '/shop/products/$entityModule/$entityId'
      fullPath: '/shop/products/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopProductsEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/book/$entityModule/$entityId': {
      id: '/(storefront)/shop_/book/$entityModule/$entityId'
      path: '/shop/book/$entityModule/$entityId'
      fullPath: '/shop/book/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopBookEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface storefrontRouteRouteChildren {
  storefrontShopRoute: typeof storefrontShopRoute
  storefrontShopConfirmationBookingIdRoute: typeof storefrontShopConfirmationBookingIdRoute
  storefrontShopBookEntityModuleEntityIdRoute: typeof storefrontShopBookEntityModuleEntityIdRoute
  storefrontShopProductsEntityModuleEntityIdRoute: typeof storefrontShopProductsEntityModuleEntityIdRoute
}

const storefrontRouteRouteChildren: storefrontRouteRouteChildren = {
  storefrontShopRoute: storefrontShopRoute,
  storefrontShopConfirmationBookingIdRoute:
    storefrontShopConfirmationBookingIdRoute,
  storefrontShopBookEntityModuleEntityIdRoute:
    storefrontShopBookEntityModuleEntityIdRoute,
  storefrontShopProductsEntityModuleEntityIdRoute:
    storefrontShopProductsEntityModuleEntityIdRoute,
}

const storefrontRouteRouteWithChildren = storefrontRouteRoute._addFileChildren(
  storefrontRouteRouteChildren,
)

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsApiTokensRoute: typeof WorkspaceSettingsApiTokensRoute
  WorkspaceSettingsChannelsRoute: typeof WorkspaceSettingsChannelsRoute
  WorkspaceSettingsOperatorRoute: typeof WorkspaceSettingsOperatorRoute
  WorkspaceSettingsPriceCatalogsRoute: typeof WorkspaceSettingsPriceCatalogsRoute
  WorkspaceSettingsPricingCategoriesRoute: typeof WorkspaceSettingsPricingCategoriesRoute
  WorkspaceSettingsProductTagsRoute: typeof WorkspaceSettingsProductTagsRoute
  WorkspaceSettingsProductTypesRoute: typeof WorkspaceSettingsProductTypesRoute
  WorkspaceSettingsTaxesRoute: typeof WorkspaceSettingsTaxesRoute
  WorkspaceSettingsTeamRoute: typeof WorkspaceSettingsTeamRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsApiTokensRoute: WorkspaceSettingsApiTokensRoute,
    WorkspaceSettingsChannelsRoute: WorkspaceSettingsChannelsRoute,
    WorkspaceSettingsOperatorRoute: WorkspaceSettingsOperatorRoute,
    WorkspaceSettingsPriceCatalogsRoute: WorkspaceSettingsPriceCatalogsRoute,
    WorkspaceSettingsPricingCategoriesRoute:
      WorkspaceSettingsPricingCategoriesRoute,
    WorkspaceSettingsProductTagsRoute: WorkspaceSettingsProductTagsRoute,
    WorkspaceSettingsProductTypesRoute: WorkspaceSettingsProductTypesRoute,
    WorkspaceSettingsTaxesRoute: WorkspaceSettingsTaxesRoute,
    WorkspaceSettingsTeamRoute: WorkspaceSettingsTeamRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceCatalogRoute: typeof WorkspaceCatalogRoute
  WorkspaceChannelSyncRoute: typeof WorkspaceChannelSyncRoute
  WorkspaceFlightsRoute: typeof WorkspaceFlightsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceActionLedgerApprovalsRoute: typeof WorkspaceActionLedgerApprovalsRoute
  WorkspaceAvailabilityIdRoute: typeof WorkspaceAvailabilityIdRoute
  WorkspaceBookingsIdRoute: typeof WorkspaceBookingsIdRoute
  WorkspaceNotificationsDeliveriesRoute: typeof WorkspaceNotificationsDeliveriesRoute
  WorkspaceNotificationsPreviewRoute: typeof WorkspaceNotificationsPreviewRoute
  WorkspaceNotificationsReminderRunsRoute: typeof WorkspaceNotificationsReminderRunsRoute
  WorkspaceNotificationsSettingsRoute: typeof WorkspaceNotificationsSettingsRoute
  WorkspaceOrganizationsIdRoute: typeof WorkspaceOrganizationsIdRoute
  WorkspacePeopleIdRoute: typeof WorkspacePeopleIdRoute
  WorkspaceProductsIdRoute: typeof WorkspaceProductsIdRoute
  WorkspaceProductsCategoriesRoute: typeof WorkspaceProductsCategoriesRoute
  WorkspaceResourcesIdRoute: typeof WorkspaceResourcesIdRoute
  WorkspaceSuppliersIdRoute: typeof WorkspaceSuppliersIdRoute
  WorkspaceActionLedgerIndexRoute: typeof WorkspaceActionLedgerIndexRoute
  WorkspaceAvailabilityIndexRoute: typeof WorkspaceAvailabilityIndexRoute
  WorkspaceBookingsIndexRoute: typeof WorkspaceBookingsIndexRoute
  WorkspaceFinanceIndexRoute: typeof WorkspaceFinanceIndexRoute
  WorkspaceLegalIndexRoute: typeof WorkspaceLegalIndexRoute
  WorkspaceNotificationsIndexRoute: typeof WorkspaceNotificationsIndexRoute
  WorkspaceOrganizationsIndexRoute: typeof WorkspaceOrganizationsIndexRoute
  WorkspacePeopleIndexRoute: typeof WorkspacePeopleIndexRoute
  WorkspaceProductsIndexRoute: typeof WorkspaceProductsIndexRoute
  WorkspacePromotionsIndexRoute: typeof WorkspacePromotionsIndexRoute
  WorkspaceResourcesIndexRoute: typeof WorkspaceResourcesIndexRoute
  WorkspaceSuppliersIndexRoute: typeof WorkspaceSuppliersIndexRoute
  WorkspaceAvailabilityRulesIdRoute: typeof WorkspaceAvailabilityRulesIdRoute
  WorkspaceAvailabilityStartTimesIdRoute: typeof WorkspaceAvailabilityStartTimesIdRoute
  WorkspaceFinanceInvoicesIdRoute: typeof WorkspaceFinanceInvoicesIdRoute
  WorkspaceFinancePaymentsIdRoute: typeof WorkspaceFinancePaymentsIdRoute
  WorkspaceFlightsBookOfferIdRoute: typeof WorkspaceFlightsBookOfferIdRoute
  WorkspaceLegalContractsIdRoute: typeof WorkspaceLegalContractsIdRoute
  WorkspaceLegalPoliciesIdRoute: typeof WorkspaceLegalPoliciesIdRoute
  WorkspaceLegalTemplatesIdRoute: typeof WorkspaceLegalTemplatesIdRoute
  WorkspaceNotificationsReminderRulesIdRoute: typeof WorkspaceNotificationsReminderRulesIdRoute
  WorkspaceNotificationsTemplatesIdRoute: typeof WorkspaceNotificationsTemplatesIdRoute
  WorkspaceResourcesAllocationsIdRoute: typeof WorkspaceResourcesAllocationsIdRoute
  WorkspaceResourcesAssignmentsIdRoute: typeof WorkspaceResourcesAssignmentsIdRoute
  WorkspaceResourcesPoolsIdRoute: typeof WorkspaceResourcesPoolsIdRoute
  WorkspaceFinanceInvoicesIndexRoute: typeof WorkspaceFinanceInvoicesIndexRoute
  WorkspaceFinancePaymentsIndexRoute: typeof WorkspaceFinancePaymentsIndexRoute
  WorkspaceLegalContractsIndexRoute: typeof WorkspaceLegalContractsIndexRoute
  WorkspaceLegalNumberSeriesIndexRoute: typeof WorkspaceLegalNumberSeriesIndexRoute
  WorkspaceLegalPoliciesIndexRoute: typeof WorkspaceLegalPoliciesIndexRoute
  WorkspaceLegalTemplatesIndexRoute: typeof WorkspaceLegalTemplatesIndexRoute
  WorkspaceNotificationsReminderRulesIndexRoute: typeof WorkspaceNotificationsReminderRulesIndexRoute
  WorkspaceNotificationsTemplatesIndexRoute: typeof WorkspaceNotificationsTemplatesIndexRoute
  WorkspaceCatalogBookEntityModuleEntityIdRoute: typeof WorkspaceCatalogBookEntityModuleEntityIdRoute
  WorkspaceCatalogJourneyEntityModuleEntityIdRoute: typeof WorkspaceCatalogJourneyEntityModuleEntityIdRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceCatalogRoute: WorkspaceCatalogRoute,
  WorkspaceChannelSyncRoute: WorkspaceChannelSyncRoute,
  WorkspaceFlightsRoute: WorkspaceFlightsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceActionLedgerApprovalsRoute: WorkspaceActionLedgerApprovalsRoute,
  WorkspaceAvailabilityIdRoute: WorkspaceAvailabilityIdRoute,
  WorkspaceBookingsIdRoute: WorkspaceBookingsIdRoute,
  WorkspaceNotificationsDeliveriesRoute: WorkspaceNotificationsDeliveriesRoute,
  WorkspaceNotificationsPreviewRoute: WorkspaceNotificationsPreviewRoute,
  WorkspaceNotificationsReminderRunsRoute:
    WorkspaceNotificationsReminderRunsRoute,
  WorkspaceNotificationsSettingsRoute: WorkspaceNotificationsSettingsRoute,
  WorkspaceOrganizationsIdRoute: WorkspaceOrganizationsIdRoute,
  WorkspacePeopleIdRoute: WorkspacePeopleIdRoute,
  WorkspaceProductsIdRoute: WorkspaceProductsIdRoute,
  WorkspaceProductsCategoriesRoute: WorkspaceProductsCategoriesRoute,
  WorkspaceResourcesIdRoute: WorkspaceResourcesIdRoute,
  WorkspaceSuppliersIdRoute: WorkspaceSuppliersIdRoute,
  WorkspaceActionLedgerIndexRoute: WorkspaceActionLedgerIndexRoute,
  WorkspaceAvailabilityIndexRoute: WorkspaceAvailabilityIndexRoute,
  WorkspaceBookingsIndexRoute: WorkspaceBookingsIndexRoute,
  WorkspaceFinanceIndexRoute: WorkspaceFinanceIndexRoute,
  WorkspaceLegalIndexRoute: WorkspaceLegalIndexRoute,
  WorkspaceNotificationsIndexRoute: WorkspaceNotificationsIndexRoute,
  WorkspaceOrganizationsIndexRoute: WorkspaceOrganizationsIndexRoute,
  WorkspacePeopleIndexRoute: WorkspacePeopleIndexRoute,
  WorkspaceProductsIndexRoute: WorkspaceProductsIndexRoute,
  WorkspacePromotionsIndexRoute: WorkspacePromotionsIndexRoute,
  WorkspaceResourcesIndexRoute: WorkspaceResourcesIndexRoute,
  WorkspaceSuppliersIndexRoute: WorkspaceSuppliersIndexRoute,
  WorkspaceAvailabilityRulesIdRoute: WorkspaceAvailabilityRulesIdRoute,
  WorkspaceAvailabilityStartTimesIdRoute:
    WorkspaceAvailabilityStartTimesIdRoute,
  WorkspaceFinanceInvoicesIdRoute: WorkspaceFinanceInvoicesIdRoute,
  WorkspaceFinancePaymentsIdRoute: WorkspaceFinancePaymentsIdRoute,
  WorkspaceFlightsBookOfferIdRoute: WorkspaceFlightsBookOfferIdRoute,
  WorkspaceLegalContractsIdRoute: WorkspaceLegalContractsIdRoute,
  WorkspaceLegalPoliciesIdRoute: WorkspaceLegalPoliciesIdRoute,
  WorkspaceLegalTemplatesIdRoute: WorkspaceLegalTemplatesIdRoute,
  WorkspaceNotificationsReminderRulesIdRoute:
    WorkspaceNotificationsReminderRulesIdRoute,
  WorkspaceNotificationsTemplatesIdRoute:
    WorkspaceNotificationsTemplatesIdRoute,
  WorkspaceResourcesAllocationsIdRoute: WorkspaceResourcesAllocationsIdRoute,
  WorkspaceResourcesAssignmentsIdRoute: WorkspaceResourcesAssignmentsIdRoute,
  WorkspaceResourcesPoolsIdRoute: WorkspaceResourcesPoolsIdRoute,
  WorkspaceFinanceInvoicesIndexRoute: WorkspaceFinanceInvoicesIndexRoute,
  WorkspaceFinancePaymentsIndexRoute: WorkspaceFinancePaymentsIndexRoute,
  WorkspaceLegalContractsIndexRoute: WorkspaceLegalContractsIndexRoute,
  WorkspaceLegalNumberSeriesIndexRoute: WorkspaceLegalNumberSeriesIndexRoute,
  WorkspaceLegalPoliciesIndexRoute: WorkspaceLegalPoliciesIndexRoute,
  WorkspaceLegalTemplatesIndexRoute: WorkspaceLegalTemplatesIndexRoute,
  WorkspaceNotificationsReminderRulesIndexRoute:
    WorkspaceNotificationsReminderRulesIndexRoute,
  WorkspaceNotificationsTemplatesIndexRoute:
    WorkspaceNotificationsTemplatesIndexRoute,
  WorkspaceCatalogBookEntityModuleEntityIdRoute:
    WorkspaceCatalogBookEntityModuleEntityIdRoute,
  WorkspaceCatalogJourneyEntityModuleEntityIdRoute:
    WorkspaceCatalogJourneyEntityModuleEntityIdRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  storefrontRouteRoute: storefrontRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  PayRoute: PayRoute,
  PaySessionIdRoute: PaySessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
