CREATE TABLE "operator_settings" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"legal_name" text,
	"vat_id" text,
	"registration_number" text,
	"address" text,
	"phone" text,
	"email" text,
	"website" text,
	"iban" text,
	"bank" text,
	"license" text,
	"license_authority" text,
	"signatory_name" text,
	"signatory_role" text,
	"customer_payment_policy" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
