import type { VoyantGraphReportingDeclaration } from "@voyant-travel/core/project"

export const INQUIRY_ACTIVITY_DATASET_ID = "relationships.inquiry-activity"
export const INQUIRY_ACTIVITY_FIELDS = [
  {
    id: "createdAt",
    label: "Created at",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "status",
    label: "Status",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "kind",
    label: "Kind",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "source",
    label: "Source",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "locale",
    label: "Locale",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "priority",
    label: "Priority",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "ownerId",
    label: "Owner",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "teamId",
    label: "Team",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "firstResponseDueAt",
    label: "First response due",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "firstRespondedAt",
    label: "First responded at",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "qualifiedAt",
    label: "Qualified at",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "convertedAt",
    label: "Converted at",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "closedAt",
    label: "Closed at",
    role: "dimension",
    valueType: "datetime",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["minimum", "maximum"],
  },
  {
    id: "closeOutcome",
    label: "Close outcome",
    role: "dimension",
    valueType: "string",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["count", "countDistinct"],
  },
  {
    id: "conversionCount",
    label: "Conversions",
    description:
      "Count of durable inquiry conversion rows; never inferred from lifecycle status or target matching.",
    role: "measure",
    valueType: "integer",
    sensitivity: "internal",
    requiredScopes: [],
    aggregations: ["sum", "average", "minimum", "maximum"],
  },
] as const

export const relationshipsReportingDeclaration = {
  datasets: [
    {
      id: INQUIRY_ACTIVITY_DATASET_ID,
      version: 1,
      label: "Inquiry activity",
      description:
        "Inquiry operations and conversion facts. Conversion counts come only from durable conversion records.",
      descriptor: {
        grain: "One row per inquiry.",
        fields: INQUIRY_ACTIVITY_FIELDS,
        defaultLimit: 100,
        maximumLimit: 1_000,
        defaultDateField: "createdAt",
      },
      requiredScopes: ["crm:read"],
      runtime: {
        entry: "@voyant-travel/relationships/reporting",
        export: "inquiryActivityDataset",
      },
    },
  ],
  widgets: [
    {
      id: "relationships.widget.inquiry-total",
      version: 1,
      label: "Total inquiries",
      description: "Inquiry records matching the report filters.",
      datasetId: INQUIRY_ACTIVITY_DATASET_ID,
      datasetVersion: 1,
      query: {
        select: [{ kind: "aggregate", operation: "count", as: "totalInquiries" }],
        filters: [],
        groupBy: [],
        orderBy: [],
        limit: 1,
      },
      visualization: { type: "kpi", options: { value: "totalInquiries" } },
      defaultSize: { width: 3, height: 2 },
      minSize: { width: 2, height: 2 },
      maxSize: { width: 6, height: 4 },
    },
    {
      id: "relationships.widget.inquiry-conversions",
      version: 1,
      label: "Inquiry conversions",
      description: "Durable conversion records for matching inquiries.",
      datasetId: INQUIRY_ACTIVITY_DATASET_ID,
      datasetVersion: 1,
      query: {
        select: [
          { kind: "aggregate", operation: "sum", field: "conversionCount", as: "totalConversions" },
        ],
        filters: [],
        groupBy: [],
        orderBy: [],
        limit: 1,
      },
      visualization: { type: "kpi", options: { value: "totalConversions" } },
      defaultSize: { width: 3, height: 2 },
      minSize: { width: 2, height: 2 },
      maxSize: { width: 6, height: 4 },
    },
    {
      id: "relationships.widget.inquiry-status",
      version: 1,
      label: "Inquiries by status",
      description: "Current inquiry lifecycle distribution.",
      datasetId: INQUIRY_ACTIVITY_DATASET_ID,
      datasetVersion: 1,
      query: {
        select: [
          { kind: "field", field: "status" },
          { kind: "aggregate", operation: "count", as: "totalInquiries" },
        ],
        filters: [],
        groupBy: [{ field: "status" }],
        orderBy: [{ by: "totalInquiries", direction: "descending" }],
        limit: 20,
      },
      visualization: { type: "pie", options: { category: "status", value: "totalInquiries" } },
      defaultSize: { width: 6, height: 4 },
      minSize: { width: 4, height: 3 },
      maxSize: { width: 8, height: 8 },
    },
  ],
  templates: [
    {
      id: "relationships.template.inquiry-operations",
      version: 1,
      label: "Inquiry operations",
      description: "Inquiry volume, lifecycle, and authoritative conversions.",
      requirements: [
        { kind: "dataset", id: INQUIRY_ACTIVITY_DATASET_ID },
        { kind: "widget", id: "relationships.widget.inquiry-total" },
        { kind: "widget", id: "relationships.widget.inquiry-conversions" },
        { kind: "widget", id: "relationships.widget.inquiry-status" },
      ],
      widgets: [
        {
          id: "inquiry-total",
          widgetId: "relationships.widget.inquiry-total",
          widgetVersion: 1,
          layout: { x: 0, y: 0, width: 3, height: 2 },
        },
        {
          id: "inquiry-conversions",
          widgetId: "relationships.widget.inquiry-conversions",
          widgetVersion: 1,
          layout: { x: 3, y: 0, width: 3, height: 2 },
        },
        {
          id: "inquiry-status",
          widgetId: "relationships.widget.inquiry-status",
          widgetVersion: 1,
          layout: { x: 6, y: 0, width: 6, height: 4 },
        },
      ],
    },
  ],
} as const satisfies VoyantGraphReportingDeclaration
