/**
 * Emit Cloud Scheduler job definitions for the operator's scheduled work.
 *
 * The operator is a Node deployment (voyant#2966): cron triggers can't run on a
 * timer inside a Cloud Run process, so each graph-derived scheduled job becomes
 * a Cloud Scheduler job that POSTs
 * `/__voyant/scheduled?schedule=<id>&cron=<expr>` with the origin-trust header.
 * The stable schedule id is the dispatch key; the cron expression remains in
 * the URL during rollout so older runtimes can still dispatch the job.
 * This mirrors what `wrangler.jsonc` `triggers.crons` did on Workers.
 *
 * Usage:
 *   SCHEDULER_TARGET_URL=https://operator.example.run.app \
 *   ORIGIN_TRUST_SECRET=... \
 *   [SCHEDULER_TIME_ZONE=Etc/UTC] [SCHEDULER_JOB_PREFIX=operator] \
 *   [SCHEDULER_LOCATION=europe-west1] [SCHEDULER_OIDC_SERVICE_ACCOUNT=sa@proj.iam...] \
 *   pnpm --filter operator emit:cloud-scheduler
 *
 * Prints `gcloud scheduler jobs create http ...` commands to stdout — review,
 * then pipe to a shell or paste into your provisioning tooling. Re-running with
 * `create` fails on existing jobs; switch to `update` in your IaC as needed.
 */
import { loadDeploymentGraphArtifacts } from "../src/deployment-graph-artifacts.js"

function requireEnv(name: string): string {
  const value = process.env[name]
  if (!value) {
    console.error(`error: ${name} is required`)
    process.exit(1)
  }
  return value
}

const targetUrl = requireEnv("SCHEDULER_TARGET_URL").replace(/\/$/, "")
const trustSecret = requireEnv("ORIGIN_TRUST_SECRET")
const timeZone = process.env.SCHEDULER_TIME_ZONE ?? "Etc/UTC"
const jobPrefix = process.env.SCHEDULER_JOB_PREFIX ?? "operator"
const location = process.env.SCHEDULER_LOCATION
const oidcServiceAccount = process.env.SCHEDULER_OIDC_SERVICE_ACCOUNT
const deploymentGraphArtifacts = loadDeploymentGraphArtifacts()

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function schedulerJobName(id: string): string {
  return id
    .replace(/^@/, "")
    .replace(/[^A-Za-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
}

const lines: string[] = [
  "#!/usr/bin/env bash",
  "# Generated by scripts/emit-cloud-scheduler.ts — review before running.",
  "set -euo pipefail",
  "",
]

for (const job of deploymentGraphArtifacts.scheduledJobs) {
  const uri =
    `${targetUrl}${job.route}?schedule=${encodeURIComponent(job.id)}` +
    `&cron=${encodeURIComponent(job.cron)}`
  const args = [
    `gcloud scheduler jobs create http ${jobPrefix}-${schedulerJobName(job.id)}`,
    location ? `--location=${location}` : undefined,
    `--schedule=${shellQuote(job.cron)}`,
    `--time-zone=${shellQuote(timeZone)}`,
    `--uri=${shellQuote(uri)}`,
    "--http-method=POST",
    `--headers=${shellQuote(`x-voyant-origin-trust=${trustSecret}`)}`,
    oidcServiceAccount ? `--oidc-service-account-email=${oidcServiceAccount}` : undefined,
  ].filter((arg): arg is string => arg !== undefined)

  lines.push(`# ${job.description}`)
  lines.push(args.join(" \\\n  "))
  lines.push("")
}

process.stdout.write(`${lines.join("\n")}\n`)
