export {
  EXTRAS_CONTENT_SCHEMA_VERSION,
  type ExtraContent,
  type ExtraMediaItem,
  type ExtraOption,
  type ExtraPolicy,
  type ExtraSummary,
  extraContentSchema,
  extraMediaItemSchema,
  extraOptionSchema,
  extraPolicySchema,
  extraSummarySchema,
  mergeOverlaysIntoExtraContent,
  validateExtraContent,
} from "@voyantjs/inventory/extras"
