import type { Module } from "@voyant-travel/core"
import type { ApiModule } from "@voyant-travel/hono/module"

import { externalRefsApiModule } from "./external-refs/index.js"
import { distributionRoutes } from "./routes.js"
import { distributionService } from "./service.js"
import { suppliersApiModule } from "./suppliers/index.js"

export type { DistributionRoutes } from "./routes.js"

export const distributionModule: Module = {
  name: "distribution",
}

export const distributionApiModule: ApiModule = {
  module: distributionModule,
  adminRoutes: distributionRoutes,
}

export const distributionApiModules = [
  externalRefsApiModule,
  distributionApiModule,
  suppliersApiModule,
] as const

export * from "./booking-extension.js"
export {
  CHANNEL_PRESETS,
  type ChannelPreset,
  type ChannelPresetIdentity,
  findChannelPreset,
  isPersistableChannelPresetKey,
} from "./channel-presets.js"
export * from "./channel-push/index.js"
export {
  classifyMappingUpdate,
  emitProductPublicationChanged,
  PRODUCT_PUBLICATION_CHANGED_EVENT,
  type ProductPublicationChangedEvent,
  type ProductPublicationOperation,
} from "./events.js"
export * from "./external-refs/index.js"
export type {
  DistributionCounterpartyEntityType,
  DistributionCounterpartyRecord,
  DistributionCounterpartyReference,
  DistributionCounterpartyRole,
  DistributionExternalReferenceInput,
  LinkExternalReferenceInput,
  LinkExternalReferenceOutcome,
  ReconcileCounterpartyActivityInput,
  ReconcileCounterpartyActivityOutcome,
  ResolveCounterpartyOutcome,
  RouteCounterpartyEventInput,
  RouteCounterpartyEventOutcome,
} from "./interface.js"
export {
  counterpartyEntityTypeToRole,
  counterpartyRoleToEntityType,
  linkExternalReference,
  reconcileCounterpartyActivity,
  resolveCounterparty,
  routeCounterpartyEvent,
} from "./interface.js"
export {
  type EnqueueGraphWebhookEventOptions,
  enqueueGraphWebhookEvent,
} from "./outbound-webhooks.js"
export * from "./publication-intent-subscribers.js"
export {
  type DistributionPublicationIntentWorkerDeps,
  type DistributionPublicationIntentWorkerRuntime,
  distributionPublicationIntentWorkerRuntimePort,
  drainPublicationReindexIntents,
  type PublicationIntentWorkerOptions,
  runDistributionPublicationIntentWorkerJob,
} from "./publication-intent-worker.js"
export {
  type PublicationChannelStatus,
  type PublicationDecision,
  type PublicationRuleInput,
  type ResolveEffectivePublicationInput,
  type ResolveEffectiveSourcePublicationInput,
  resolveEffectivePublication,
  resolveEffectiveSourcePublication,
} from "./publication-resolver.js"
export {
  type AcquireTokenAcquired,
  type AcquireTokenDenied,
  type AcquireTokenResult,
  acquireToken,
  type ChannelPushPriority,
  channelScopeKey,
  DEFAULT_PRIORITY_GATES,
  drainBucket,
  type RateLimitConfig,
} from "./rate-limit.js"
export type {
  Channel,
  ChannelBookingLink,
  ChannelCommissionRule,
  ChannelContactProjection,
  ChannelContract,
  ChannelInventoryAllotment,
  ChannelInventoryAllotmentTarget,
  ChannelInventoryReleaseExecution,
  ChannelInventoryReleaseRule,
  ChannelProductMapping,
  ChannelProductPublication,
  ChannelPublicationReindexIntent,
  ChannelReconciliationItem,
  ChannelReconciliationPolicy,
  ChannelReconciliationRun,
  ChannelReleaseSchedule,
  ChannelRemittanceException,
  ChannelSettlementApproval,
  ChannelSettlementItem,
  ChannelSettlementPolicy,
  ChannelSettlementRun,
  ChannelSourcePublication,
  ChannelSupplierPublication,
  ChannelWebhookEvent,
  NewChannel,
  NewChannelBookingLink,
  NewChannelCommissionRule,
  NewChannelContactProjection,
  NewChannelContract,
  NewChannelInventoryAllotment,
  NewChannelInventoryAllotmentTarget,
  NewChannelInventoryReleaseExecution,
  NewChannelInventoryReleaseRule,
  NewChannelProductMapping,
  NewChannelProductPublication,
  NewChannelPublicationReindexIntent,
  NewChannelReconciliationItem,
  NewChannelReconciliationPolicy,
  NewChannelReconciliationRun,
  NewChannelReleaseSchedule,
  NewChannelRemittanceException,
  NewChannelSettlementApproval,
  NewChannelSettlementItem,
  NewChannelSettlementPolicy,
  NewChannelSettlementRun,
  NewChannelSourcePublication,
  NewChannelSupplierPublication,
  NewChannelWebhookEvent,
} from "./schema.js"
export {
  channelBookingLinks,
  channelCommissionRules,
  channelContactProjections,
  channelContracts,
  channelInventoryAllotments,
  channelInventoryAllotmentTargets,
  channelInventoryReleaseExecutions,
  channelInventoryReleaseRules,
  channelProductMappings,
  channelProductPublications,
  channelPublicationReindexIntents,
  channelReconciliationItems,
  channelReconciliationPolicies,
  channelReconciliationPolicyFrequencyEnum,
  channelReconciliationRuns,
  channelReleaseScheduleKindEnum,
  channelReleaseSchedules,
  channelRemittanceExceptionStatusEnum,
  channelRemittanceExceptions,
  channelSettlementApprovalStatusEnum,
  channelSettlementApprovals,
  channelSettlementItems,
  channelSettlementPolicies,
  channelSettlementPolicyFrequencyEnum,
  channelSettlementRuns,
  channelSourcePublications,
  channelSupplierPublications,
  channels,
  channelWebhookEvents,
} from "./schema.js"
export {
  CHANNEL_SYSTEM_KEYS,
  type ChannelSystemKey,
  DIRECT_CHANNEL_SYSTEM_KEY,
} from "./schema-core.js"
export type {
  ChannelAvailabilityPushIntent,
  ChannelContentPushIntent,
  NewChannelAvailabilityPushIntent,
  NewChannelContentPushIntent,
} from "./schema-push-intents.js"
export {
  channelAvailabilityPushIntents,
  channelContentPushIntents,
} from "./schema-push-intents.js"
export { DuplicateChannelPresetError, SystemChannelProtectedError } from "./service/channels.js"
export * from "./suppliers/index.js"
export {
  channelBookingLinkListQuerySchema,
  channelCommissionRuleListQuerySchema,
  channelContractListQuerySchema,
  channelInventoryAllotmentListQuerySchema,
  channelInventoryAllotmentTargetListQuerySchema,
  channelInventoryReleaseExecutionListQuerySchema,
  channelInventoryReleaseRuleListQuerySchema,
  channelListQuerySchema,
  channelProductMappingListQuerySchema,
  channelProductPublicationListQuerySchema,
  channelPublicationDecisionSchema,
  channelPublicationReindexIntentKindSchema,
  channelPublicationReindexIntentSchema,
  channelPublicationReindexIntentStatusSchema,
  channelReconciliationItemListQuerySchema,
  channelReconciliationPolicyFrequencySchema,
  channelReconciliationPolicyListQuerySchema,
  channelReconciliationRunListQuerySchema,
  channelReleaseScheduleKindSchema,
  channelReleaseScheduleListQuerySchema,
  channelRemittanceExceptionListQuerySchema,
  channelRemittanceExceptionStatusSchema,
  channelSettlementApprovalListQuerySchema,
  channelSettlementApprovalStatusSchema,
  channelSettlementItemListQuerySchema,
  channelSettlementPolicyFrequencySchema,
  channelSettlementPolicyListQuerySchema,
  channelSettlementRunListQuerySchema,
  channelSourcePublicationListQuerySchema,
  channelSupplierPublicationListQuerySchema,
  channelWebhookEventListQuerySchema,
  effectivePublicationInputSchema,
  effectivePublicationReasonSchema,
  effectivePublicationResultSchema,
  effectiveSourcePublicationInputSchema,
  effectiveSourcePublicationReasonSchema,
  effectiveSourcePublicationResultSchema,
  insertChannelBookingLinkSchema,
  insertChannelCommissionRuleSchema,
  insertChannelContractSchema,
  insertChannelInventoryAllotmentSchema,
  insertChannelInventoryAllotmentTargetSchema,
  insertChannelInventoryReleaseExecutionSchema,
  insertChannelInventoryReleaseRuleSchema,
  insertChannelProductMappingSchema,
  insertChannelProductPublicationSchema,
  insertChannelReconciliationItemSchema,
  insertChannelReconciliationPolicySchema,
  insertChannelReconciliationRunSchema,
  insertChannelReleaseScheduleSchema,
  insertChannelRemittanceExceptionSchema,
  insertChannelSchema,
  insertChannelSettlementApprovalSchema,
  insertChannelSettlementItemSchema,
  insertChannelSettlementPolicySchema,
  insertChannelSettlementRunSchema,
  insertChannelSourcePublicationSchema,
  insertChannelSupplierPublicationSchema,
  insertChannelWebhookEventSchema,
  updateChannelBookingLinkSchema,
  updateChannelCommissionRuleSchema,
  updateChannelContractSchema,
  updateChannelInventoryAllotmentSchema,
  updateChannelInventoryAllotmentTargetSchema,
  updateChannelInventoryReleaseExecutionSchema,
  updateChannelInventoryReleaseRuleSchema,
  updateChannelProductMappingSchema,
  updateChannelProductPublicationSchema,
  updateChannelReconciliationItemSchema,
  updateChannelReconciliationPolicySchema,
  updateChannelReconciliationRunSchema,
  updateChannelReleaseScheduleSchema,
  updateChannelRemittanceExceptionSchema,
  updateChannelSchema,
  updateChannelSettlementApprovalSchema,
  updateChannelSettlementItemSchema,
  updateChannelSettlementPolicySchema,
  updateChannelSettlementRunSchema,
  updateChannelSourcePublicationSchema,
  updateChannelSupplierPublicationSchema,
  updateChannelWebhookEventSchema,
} from "./validation.js"
export {
  enqueueOutboundEnvelope,
  type OutboundEnvelopeInput,
  type OutboundEnvelopeResultInput,
  type PreparedEnvelope,
  prepareOutboundEnvelope,
  redactBodyPii,
  redactHeaders,
  redactStringPii,
} from "./webhook-deliveries.js"
export { createDistributionWebhookDeliveryWorker } from "./webhook-worker.js"
export { distributionService }
