// @ts-nocheck -- legacy seed fixture typing cleanup is tracked separately from demo data edits.
// agent-quality: file-size exception -- curated flight reference fixture data stays together for reproducible demo resets.
/**
 * Operator flights-reference seed helpers.
 *
 * Populates the IATA-keyed `reference_airlines` and `reference_airports`
 * tables exposed by `@voyantjs/flights/reference/local-postgres`. These two
 * tables back the in-deployment `LocalPostgresReferenceDataProvider`, so any
 * flight-search / hydration UI in the operator admin can resolve IATA codes
 * to human-readable carrier and airport metadata without a hosted dependency.
 *
 * The data set is deliberately curated rather than exhaustive: 30 carriers
 * spanning the three major alliances + a handful of large unaligned LCC and
 * Gulf operators, and 60 hub airports weighted toward Europe / North America
 * / Asia & the Middle East with a smaller tail in Africa, South America and
 * Oceania. ICAO codes, cities, timezones and lat/long are real values — the
 * UI will surface them and a human will spot bogus data.
 *
 * Both functions use `onConflictDoNothing()` keyed on the `iata_code` PK so
 * re-running is idempotent.
 */

import {
  referenceAircraft,
  referenceAirlines,
  referenceAirports,
} from "@voyantjs/flights/reference/local-postgres"
import type { drizzle } from "drizzle-orm/postgres-js"

type Db = ReturnType<typeof drizzle>

const KAYAK_LOGO = (iata: string) => `https://www.kayak.com/h/run/airline-logos/${iata}.png`

/**
 * Seed 30 major airlines spread across oneworld, Star Alliance, SkyTeam,
 * plus a handful of unaligned big names (Gulf carriers, LCCs, etc).
 */
export async function seedAirlines(db: Db): Promise<number> {
  const rows: Array<typeof referenceAirlines.$inferInsert> = [
    // ── oneworld ───────────────────────────────────────────────────────────
    {
      iataCode: "BA",
      icaoCode: "BAW",
      name: "British Airways",
      country: "GB",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("BA"),
    },
    {
      iataCode: "AA",
      icaoCode: "AAL",
      name: "American Airlines",
      country: "US",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("AA"),
    },
    {
      iataCode: "QR",
      icaoCode: "QTR",
      name: "Qatar Airways",
      country: "QA",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("QR"),
    },
    {
      iataCode: "CX",
      icaoCode: "CPA",
      name: "Cathay Pacific",
      country: "HK",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("CX"),
    },
    {
      iataCode: "JL",
      icaoCode: "JAL",
      name: "Japan Airlines",
      country: "JP",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("JL"),
    },
    {
      iataCode: "QF",
      icaoCode: "QFA",
      name: "Qantas",
      country: "AU",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("QF"),
    },
    {
      iataCode: "IB",
      icaoCode: "IBE",
      name: "Iberia",
      country: "ES",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("IB"),
    },
    {
      iataCode: "AY",
      icaoCode: "FIN",
      name: "Finnair",
      country: "FI",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("AY"),
    },
    {
      iataCode: "EI",
      icaoCode: "EIN",
      name: "Aer Lingus",
      country: "IE",
      alliance: "oneworld",
      logoUrl: KAYAK_LOGO("EI"),
    },

    // ── Star Alliance ──────────────────────────────────────────────────────
    {
      iataCode: "LH",
      icaoCode: "DLH",
      name: "Lufthansa",
      country: "DE",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("LH"),
    },
    {
      iataCode: "UA",
      icaoCode: "UAL",
      name: "United Airlines",
      country: "US",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("UA"),
    },
    {
      iataCode: "AC",
      icaoCode: "ACA",
      name: "Air Canada",
      country: "CA",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("AC"),
    },
    {
      iataCode: "NH",
      icaoCode: "ANA",
      name: "All Nippon Airways",
      country: "JP",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("NH"),
    },
    {
      iataCode: "SQ",
      icaoCode: "SIA",
      name: "Singapore Airlines",
      country: "SG",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("SQ"),
    },
    {
      iataCode: "TG",
      icaoCode: "THA",
      name: "Thai Airways International",
      country: "TH",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("TG"),
    },
    {
      iataCode: "TK",
      icaoCode: "THY",
      name: "Turkish Airlines",
      country: "TR",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("TK"),
    },
    {
      iataCode: "NZ",
      icaoCode: "ANZ",
      name: "Air New Zealand",
      country: "NZ",
      alliance: "star-alliance",
      logoUrl: KAYAK_LOGO("NZ"),
    },

    // ── SkyTeam ────────────────────────────────────────────────────────────
    {
      iataCode: "AF",
      icaoCode: "AFR",
      name: "Air France",
      country: "FR",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("AF"),
    },
    {
      iataCode: "KL",
      icaoCode: "KLM",
      name: "KLM Royal Dutch Airlines",
      country: "NL",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("KL"),
    },
    {
      iataCode: "DL",
      icaoCode: "DAL",
      name: "Delta Air Lines",
      country: "US",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("DL"),
    },
    {
      iataCode: "KE",
      icaoCode: "KAL",
      name: "Korean Air",
      country: "KR",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("KE"),
    },
    {
      iataCode: "AZ",
      icaoCode: "ITY",
      name: "ITA Airways",
      country: "IT",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("AZ"),
    },
    {
      iataCode: "VN",
      icaoCode: "HVN",
      name: "Vietnam Airlines",
      country: "VN",
      alliance: "skyteam",
      logoUrl: KAYAK_LOGO("VN"),
    },

    // ── Unaligned ──────────────────────────────────────────────────────────
    { iataCode: "EK", icaoCode: "UAE", name: "Emirates", country: "AE", logoUrl: KAYAK_LOGO("EK") },
    {
      iataCode: "EY",
      icaoCode: "ETD",
      name: "Etihad Airways",
      country: "AE",
      logoUrl: KAYAK_LOGO("EY"),
    },
    {
      iataCode: "B6",
      icaoCode: "JBU",
      name: "JetBlue Airways",
      country: "US",
      logoUrl: KAYAK_LOGO("B6"),
    },
    {
      iataCode: "VS",
      icaoCode: "VIR",
      name: "Virgin Atlantic",
      country: "GB",
      logoUrl: KAYAK_LOGO("VS"),
    },
    { iataCode: "SU", icaoCode: "AFL", name: "Aeroflot", country: "RU", logoUrl: KAYAK_LOGO("SU") },
    {
      iataCode: "SA",
      icaoCode: "SAA",
      name: "South African Airways",
      country: "ZA",
      logoUrl: KAYAK_LOGO("SA"),
    },
    { iataCode: "U2", icaoCode: "EZY", name: "easyJet", country: "GB", logoUrl: KAYAK_LOGO("U2") },
    { iataCode: "FR", icaoCode: "RYR", name: "Ryanair", country: "IE", logoUrl: KAYAK_LOGO("FR") },
  ]

  await db.insert(referenceAirlines).values(rows).onConflictDoNothing()
  return rows.length
}

/**
 * Seed 60 major hub airports. Distribution:
 *   Europe          25
 *   North America   15
 *   Asia / Middle East 15
 *   Africa / South America / Oceania 5
 */
export async function seedAirports(db: Db): Promise<number> {
  const rows: Array<typeof referenceAirports.$inferInsert> = [
    // ── Europe (25) ────────────────────────────────────────────────────────
    {
      iataCode: "LHR",
      icaoCode: "EGLL",
      name: "London Heathrow Airport",
      city: "London",
      country: "GB",
      timezone: "Europe/London",
      latitude: 51.4706,
      longitude: -0.4619,
    },
    {
      iataCode: "LGW",
      icaoCode: "EGKK",
      name: "London Gatwick Airport",
      city: "London",
      country: "GB",
      timezone: "Europe/London",
      latitude: 51.1481,
      longitude: -0.1903,
    },
    {
      iataCode: "STN",
      icaoCode: "EGSS",
      name: "London Stansted Airport",
      city: "London",
      country: "GB",
      timezone: "Europe/London",
      latitude: 51.885,
      longitude: 0.235,
    },
    {
      iataCode: "MAN",
      icaoCode: "EGCC",
      name: "Manchester Airport",
      city: "Manchester",
      country: "GB",
      timezone: "Europe/London",
      latitude: 53.3537,
      longitude: -2.275,
    },
    {
      iataCode: "EDI",
      icaoCode: "EGPH",
      name: "Edinburgh Airport",
      city: "Edinburgh",
      country: "GB",
      timezone: "Europe/London",
      latitude: 55.95,
      longitude: -3.3725,
    },
    {
      iataCode: "DUB",
      icaoCode: "EIDW",
      name: "Dublin Airport",
      city: "Dublin",
      country: "IE",
      timezone: "Europe/Dublin",
      latitude: 53.4213,
      longitude: -6.2701,
    },
    {
      iataCode: "CDG",
      icaoCode: "LFPG",
      name: "Paris Charles de Gaulle Airport",
      city: "Paris",
      country: "FR",
      timezone: "Europe/Paris",
      latitude: 49.0097,
      longitude: 2.5479,
    },
    {
      iataCode: "ORY",
      icaoCode: "LFPO",
      name: "Paris Orly Airport",
      city: "Paris",
      country: "FR",
      timezone: "Europe/Paris",
      latitude: 48.7233,
      longitude: 2.3794,
    },
    {
      iataCode: "AMS",
      icaoCode: "EHAM",
      name: "Amsterdam Schiphol Airport",
      city: "Amsterdam",
      country: "NL",
      timezone: "Europe/Amsterdam",
      latitude: 52.3105,
      longitude: 4.7683,
    },
    {
      iataCode: "BRU",
      icaoCode: "EBBR",
      name: "Brussels Airport",
      city: "Brussels",
      country: "BE",
      timezone: "Europe/Brussels",
      latitude: 50.9014,
      longitude: 4.4844,
    },
    {
      iataCode: "FRA",
      icaoCode: "EDDF",
      name: "Frankfurt Airport",
      city: "Frankfurt",
      country: "DE",
      timezone: "Europe/Berlin",
      latitude: 50.0379,
      longitude: 8.5622,
    },
    {
      iataCode: "MUC",
      icaoCode: "EDDM",
      name: "Munich Airport",
      city: "Munich",
      country: "DE",
      timezone: "Europe/Berlin",
      latitude: 48.3538,
      longitude: 11.7861,
    },
    {
      iataCode: "DUS",
      icaoCode: "EDDL",
      name: "Düsseldorf Airport",
      city: "Düsseldorf",
      country: "DE",
      timezone: "Europe/Berlin",
      latitude: 51.2895,
      longitude: 6.7668,
    },
    {
      iataCode: "ZRH",
      icaoCode: "LSZH",
      name: "Zurich Airport",
      city: "Zurich",
      country: "CH",
      timezone: "Europe/Zurich",
      latitude: 47.4647,
      longitude: 8.5492,
    },
    {
      iataCode: "GVA",
      icaoCode: "LSGG",
      name: "Geneva Airport",
      city: "Geneva",
      country: "CH",
      timezone: "Europe/Zurich",
      latitude: 46.2381,
      longitude: 6.1089,
    },
    {
      iataCode: "VIE",
      icaoCode: "LOWW",
      name: "Vienna International Airport",
      city: "Vienna",
      country: "AT",
      timezone: "Europe/Vienna",
      latitude: 48.1103,
      longitude: 16.5697,
    },
    {
      iataCode: "FCO",
      icaoCode: "LIRF",
      name: "Rome Fiumicino Airport",
      city: "Rome",
      country: "IT",
      timezone: "Europe/Rome",
      latitude: 41.8003,
      longitude: 12.2389,
    },
    {
      iataCode: "MXP",
      icaoCode: "LIMC",
      name: "Milan Malpensa Airport",
      city: "Milan",
      country: "IT",
      timezone: "Europe/Rome",
      latitude: 45.6306,
      longitude: 8.7281,
    },
    {
      iataCode: "MAD",
      icaoCode: "LEMD",
      name: "Madrid Barajas Airport",
      city: "Madrid",
      country: "ES",
      timezone: "Europe/Madrid",
      latitude: 40.4936,
      longitude: -3.5668,
    },
    {
      iataCode: "BCN",
      icaoCode: "LEBL",
      name: "Barcelona El Prat Airport",
      city: "Barcelona",
      country: "ES",
      timezone: "Europe/Madrid",
      latitude: 41.2974,
      longitude: 2.0833,
    },
    {
      iataCode: "LIS",
      icaoCode: "LPPT",
      name: "Lisbon Humberto Delgado Airport",
      city: "Lisbon",
      country: "PT",
      timezone: "Europe/Lisbon",
      latitude: 38.7813,
      longitude: -9.1359,
    },
    {
      iataCode: "CPH",
      icaoCode: "EKCH",
      name: "Copenhagen Airport",
      city: "Copenhagen",
      country: "DK",
      timezone: "Europe/Copenhagen",
      latitude: 55.6181,
      longitude: 12.6561,
    },
    {
      iataCode: "ARN",
      icaoCode: "ESSA",
      name: "Stockholm Arlanda Airport",
      city: "Stockholm",
      country: "SE",
      timezone: "Europe/Stockholm",
      latitude: 59.6519,
      longitude: 17.9186,
    },
    {
      iataCode: "OSL",
      icaoCode: "ENGM",
      name: "Oslo Gardermoen Airport",
      city: "Oslo",
      country: "NO",
      timezone: "Europe/Oslo",
      latitude: 60.1939,
      longitude: 11.1004,
    },
    {
      iataCode: "IST",
      icaoCode: "LTFM",
      name: "Istanbul Airport",
      city: "Istanbul",
      country: "TR",
      timezone: "Europe/Istanbul",
      latitude: 41.2753,
      longitude: 28.7519,
    },

    // ── North America (15) ─────────────────────────────────────────────────
    {
      iataCode: "JFK",
      icaoCode: "KJFK",
      name: "John F. Kennedy International Airport",
      city: "New York",
      country: "US",
      timezone: "America/New_York",
      latitude: 40.6413,
      longitude: -73.7781,
    },
    {
      iataCode: "LGA",
      icaoCode: "KLGA",
      name: "LaGuardia Airport",
      city: "New York",
      country: "US",
      timezone: "America/New_York",
      latitude: 40.7769,
      longitude: -73.874,
    },
    {
      iataCode: "EWR",
      icaoCode: "KEWR",
      name: "Newark Liberty International Airport",
      city: "Newark",
      country: "US",
      timezone: "America/New_York",
      latitude: 40.6895,
      longitude: -74.1745,
    },
    {
      iataCode: "BOS",
      icaoCode: "KBOS",
      name: "Boston Logan International Airport",
      city: "Boston",
      country: "US",
      timezone: "America/New_York",
      latitude: 42.3656,
      longitude: -71.0096,
    },
    {
      iataCode: "IAD",
      icaoCode: "KIAD",
      name: "Washington Dulles International Airport",
      city: "Washington",
      country: "US",
      timezone: "America/New_York",
      latitude: 38.9531,
      longitude: -77.4565,
    },
    {
      iataCode: "ATL",
      icaoCode: "KATL",
      name: "Hartsfield-Jackson Atlanta International Airport",
      city: "Atlanta",
      country: "US",
      timezone: "America/New_York",
      latitude: 33.6407,
      longitude: -84.4277,
    },
    {
      iataCode: "MIA",
      icaoCode: "KMIA",
      name: "Miami International Airport",
      city: "Miami",
      country: "US",
      timezone: "America/New_York",
      latitude: 25.7959,
      longitude: -80.2871,
    },
    {
      iataCode: "ORD",
      icaoCode: "KORD",
      name: "Chicago O'Hare International Airport",
      city: "Chicago",
      country: "US",
      timezone: "America/Chicago",
      latitude: 41.9742,
      longitude: -87.9073,
    },
    {
      iataCode: "DFW",
      icaoCode: "KDFW",
      name: "Dallas/Fort Worth International Airport",
      city: "Dallas",
      country: "US",
      timezone: "America/Chicago",
      latitude: 32.8998,
      longitude: -97.0403,
    },
    {
      iataCode: "DEN",
      icaoCode: "KDEN",
      name: "Denver International Airport",
      city: "Denver",
      country: "US",
      timezone: "America/Denver",
      latitude: 39.8561,
      longitude: -104.6737,
    },
    {
      iataCode: "LAX",
      icaoCode: "KLAX",
      name: "Los Angeles International Airport",
      city: "Los Angeles",
      country: "US",
      timezone: "America/Los_Angeles",
      latitude: 33.9416,
      longitude: -118.4085,
    },
    {
      iataCode: "SFO",
      icaoCode: "KSFO",
      name: "San Francisco International Airport",
      city: "San Francisco",
      country: "US",
      timezone: "America/Los_Angeles",
      latitude: 37.6213,
      longitude: -122.379,
    },
    {
      iataCode: "SEA",
      icaoCode: "KSEA",
      name: "Seattle-Tacoma International Airport",
      city: "Seattle",
      country: "US",
      timezone: "America/Los_Angeles",
      latitude: 47.4502,
      longitude: -122.3088,
    },
    {
      iataCode: "YYZ",
      icaoCode: "CYYZ",
      name: "Toronto Pearson International Airport",
      city: "Toronto",
      country: "CA",
      timezone: "America/Toronto",
      latitude: 43.6777,
      longitude: -79.6248,
    },
    {
      iataCode: "YVR",
      icaoCode: "CYVR",
      name: "Vancouver International Airport",
      city: "Vancouver",
      country: "CA",
      timezone: "America/Vancouver",
      latitude: 49.1939,
      longitude: -123.1844,
    },

    // ── Asia / Middle East (15) ────────────────────────────────────────────
    {
      iataCode: "DXB",
      icaoCode: "OMDB",
      name: "Dubai International Airport",
      city: "Dubai",
      country: "AE",
      timezone: "Asia/Dubai",
      latitude: 25.2532,
      longitude: 55.3657,
    },
    {
      iataCode: "DOH",
      icaoCode: "OTHH",
      name: "Hamad International Airport",
      city: "Doha",
      country: "QA",
      timezone: "Asia/Qatar",
      latitude: 25.2731,
      longitude: 51.608,
    },
    {
      iataCode: "AUH",
      icaoCode: "OMAA",
      name: "Abu Dhabi International Airport",
      city: "Abu Dhabi",
      country: "AE",
      timezone: "Asia/Dubai",
      latitude: 24.433,
      longitude: 54.6511,
    },
    {
      iataCode: "BKK",
      icaoCode: "VTBS",
      name: "Suvarnabhumi Airport",
      city: "Bangkok",
      country: "TH",
      timezone: "Asia/Bangkok",
      latitude: 13.69,
      longitude: 100.7501,
    },
    {
      iataCode: "SIN",
      icaoCode: "WSSS",
      name: "Singapore Changi Airport",
      city: "Singapore",
      country: "SG",
      timezone: "Asia/Singapore",
      latitude: 1.3644,
      longitude: 103.9915,
    },
    {
      iataCode: "HKG",
      icaoCode: "VHHH",
      name: "Hong Kong International Airport",
      city: "Hong Kong",
      country: "HK",
      timezone: "Asia/Hong_Kong",
      latitude: 22.308,
      longitude: 113.9185,
    },
    {
      iataCode: "NRT",
      icaoCode: "RJAA",
      name: "Narita International Airport",
      city: "Tokyo",
      country: "JP",
      timezone: "Asia/Tokyo",
      latitude: 35.772,
      longitude: 140.3929,
    },
    {
      iataCode: "HND",
      icaoCode: "RJTT",
      name: "Tokyo Haneda Airport",
      city: "Tokyo",
      country: "JP",
      timezone: "Asia/Tokyo",
      latitude: 35.5494,
      longitude: 139.7798,
    },
    {
      iataCode: "ICN",
      icaoCode: "RKSI",
      name: "Incheon International Airport",
      city: "Seoul",
      country: "KR",
      timezone: "Asia/Seoul",
      latitude: 37.4602,
      longitude: 126.4407,
    },
    {
      iataCode: "PVG",
      icaoCode: "ZSPD",
      name: "Shanghai Pudong International Airport",
      city: "Shanghai",
      country: "CN",
      timezone: "Asia/Shanghai",
      latitude: 31.1443,
      longitude: 121.8083,
    },
    {
      iataCode: "PEK",
      icaoCode: "ZBAA",
      name: "Beijing Capital International Airport",
      city: "Beijing",
      country: "CN",
      timezone: "Asia/Shanghai",
      latitude: 40.0801,
      longitude: 116.5846,
    },
    {
      iataCode: "KUL",
      icaoCode: "WMKK",
      name: "Kuala Lumpur International Airport",
      city: "Kuala Lumpur",
      country: "MY",
      timezone: "Asia/Kuala_Lumpur",
      latitude: 2.7456,
      longitude: 101.7099,
    },
    {
      iataCode: "DEL",
      icaoCode: "VIDP",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
      country: "IN",
      timezone: "Asia/Kolkata",
      latitude: 28.5562,
      longitude: 77.1,
    },
    {
      iataCode: "BOM",
      icaoCode: "VABB",
      name: "Chhatrapati Shivaji Maharaj International Airport",
      city: "Mumbai",
      country: "IN",
      timezone: "Asia/Kolkata",
      latitude: 19.0887,
      longitude: 72.8679,
    },
    {
      iataCode: "SYD",
      icaoCode: "YSSY",
      name: "Sydney Kingsford Smith Airport",
      city: "Sydney",
      country: "AU",
      timezone: "Australia/Sydney",
      latitude: -33.9399,
      longitude: 151.1753,
    },

    // ── Africa / South America / Oceania (5) ───────────────────────────────
    {
      iataCode: "CAI",
      icaoCode: "HECA",
      name: "Cairo International Airport",
      city: "Cairo",
      country: "EG",
      timezone: "Africa/Cairo",
      latitude: 30.1219,
      longitude: 31.4056,
    },
    {
      iataCode: "JNB",
      icaoCode: "FAOR",
      name: "O. R. Tambo International Airport",
      city: "Johannesburg",
      country: "ZA",
      timezone: "Africa/Johannesburg",
      latitude: -26.1392,
      longitude: 28.246,
    },
    {
      iataCode: "CPT",
      icaoCode: "FACT",
      name: "Cape Town International Airport",
      city: "Cape Town",
      country: "ZA",
      timezone: "Africa/Johannesburg",
      latitude: -33.9648,
      longitude: 18.6017,
    },
    {
      iataCode: "GRU",
      icaoCode: "SBGR",
      name: "São Paulo–Guarulhos International Airport",
      city: "São Paulo",
      country: "BR",
      timezone: "America/Sao_Paulo",
      latitude: -23.4356,
      longitude: -46.4731,
    },
    {
      iataCode: "EZE",
      icaoCode: "SAEZ",
      name: "Ministro Pistarini International Airport",
      city: "Buenos Aires",
      country: "AR",
      timezone: "America/Argentina/Buenos_Aires",
      latitude: -34.8222,
      longitude: -58.5358,
    },
  ]

  await db.insert(referenceAirports).values(rows).onConflictDoNothing()
  return rows.length
}

/**
 * Seed ~25 common IATA aircraft type codes. Used to hydrate the segment
 * "Aircraft" line in the offer detail sheet (e.g. "738" → "Boeing 737-800").
 * Covers the workhorses most demo offers will reference plus a handful of
 * widebody types for long-haul itineraries.
 */
export async function seedAircraft(db: Db): Promise<number> {
  const rows: Array<typeof referenceAircraft.$inferInsert> = [
    // ── Boeing narrowbody ──────────────────────────────────────────────────
    {
      iataCode: "738",
      icaoCode: "B738",
      name: "Boeing 737-800",
      manufacturer: "Boeing",
      typicalSeats: 189,
    },
    {
      iataCode: "739",
      icaoCode: "B739",
      name: "Boeing 737-900",
      manufacturer: "Boeing",
      typicalSeats: 215,
    },
    {
      iataCode: "73H",
      icaoCode: "B38M",
      name: "Boeing 737 MAX 8",
      manufacturer: "Boeing",
      typicalSeats: 178,
    },
    {
      iataCode: "7M9",
      icaoCode: "B39M",
      name: "Boeing 737 MAX 9",
      manufacturer: "Boeing",
      typicalSeats: 193,
    },

    // ── Airbus narrowbody ──────────────────────────────────────────────────
    {
      iataCode: "319",
      icaoCode: "A319",
      name: "Airbus A319",
      manufacturer: "Airbus",
      typicalSeats: 144,
    },
    {
      iataCode: "320",
      icaoCode: "A320",
      name: "Airbus A320",
      manufacturer: "Airbus",
      typicalSeats: 180,
    },
    {
      iataCode: "321",
      icaoCode: "A321",
      name: "Airbus A321",
      manufacturer: "Airbus",
      typicalSeats: 220,
    },
    {
      iataCode: "32A",
      icaoCode: "A20N",
      name: "Airbus A320neo",
      manufacturer: "Airbus",
      typicalSeats: 186,
    },
    {
      iataCode: "32Q",
      icaoCode: "A21N",
      name: "Airbus A321neo",
      manufacturer: "Airbus",
      typicalSeats: 232,
    },

    // ── Boeing widebody ────────────────────────────────────────────────────
    {
      iataCode: "763",
      icaoCode: "B763",
      name: "Boeing 767-300",
      manufacturer: "Boeing",
      typicalSeats: 269,
    },
    {
      iataCode: "772",
      icaoCode: "B772",
      name: "Boeing 777-200",
      manufacturer: "Boeing",
      typicalSeats: 314,
    },
    {
      iataCode: "77L",
      icaoCode: "B77L",
      name: "Boeing 777-200LR",
      manufacturer: "Boeing",
      typicalSeats: 317,
    },
    {
      iataCode: "77W",
      icaoCode: "B77W",
      name: "Boeing 777-300ER",
      manufacturer: "Boeing",
      typicalSeats: 396,
    },
    {
      iataCode: "778",
      icaoCode: "B778",
      name: "Boeing 777-8",
      manufacturer: "Boeing",
      typicalSeats: 384,
    },
    {
      iataCode: "779",
      icaoCode: "B779",
      name: "Boeing 777-9",
      manufacturer: "Boeing",
      typicalSeats: 426,
    },
    {
      iataCode: "788",
      icaoCode: "B788",
      name: "Boeing 787-8 Dreamliner",
      manufacturer: "Boeing",
      typicalSeats: 242,
    },
    {
      iataCode: "789",
      icaoCode: "B789",
      name: "Boeing 787-9 Dreamliner",
      manufacturer: "Boeing",
      typicalSeats: 290,
    },
    {
      iataCode: "78J",
      icaoCode: "B78X",
      name: "Boeing 787-10 Dreamliner",
      manufacturer: "Boeing",
      typicalSeats: 330,
    },
    {
      iataCode: "744",
      icaoCode: "B744",
      name: "Boeing 747-400",
      manufacturer: "Boeing",
      typicalSeats: 416,
    },
    {
      iataCode: "748",
      icaoCode: "B748",
      name: "Boeing 747-8",
      manufacturer: "Boeing",
      typicalSeats: 467,
    },

    // ── Airbus widebody ────────────────────────────────────────────────────
    {
      iataCode: "333",
      icaoCode: "A333",
      name: "Airbus A330-300",
      manufacturer: "Airbus",
      typicalSeats: 277,
    },
    {
      iataCode: "339",
      icaoCode: "A339",
      name: "Airbus A330-900neo",
      manufacturer: "Airbus",
      typicalSeats: 287,
    },
    {
      iataCode: "359",
      icaoCode: "A359",
      name: "Airbus A350-900",
      manufacturer: "Airbus",
      typicalSeats: 325,
    },
    {
      iataCode: "351",
      icaoCode: "A35K",
      name: "Airbus A350-1000",
      manufacturer: "Airbus",
      typicalSeats: 369,
    },
    {
      iataCode: "388",
      icaoCode: "A388",
      name: "Airbus A380-800",
      manufacturer: "Airbus",
      typicalSeats: 525,
    },

    // ── Regional ───────────────────────────────────────────────────────────
    {
      iataCode: "E90",
      icaoCode: "E190",
      name: "Embraer E190",
      manufacturer: "Embraer",
      typicalSeats: 100,
    },
    {
      iataCode: "E95",
      icaoCode: "E195",
      name: "Embraer E195",
      manufacturer: "Embraer",
      typicalSeats: 124,
    },
  ]

  await db.insert(referenceAircraft).values(rows).onConflictDoNothing()
  return rows.length
}
