/**
 * Catalog plane field policy for `packages/charters`.
 *
 * The charters vertical models luxury yacht-style products: per-suite or
 * whole-yacht booking, MYBA contracts, APA (Advance Provisioning Allowance)
 * as a first-class concern. See `docs/architecture/charters-module.md` for
 * the vertical's design.
 *
 * Scope of this file:
 *   - The root `charter_products` table (from `schema-core.ts`).
 *   - Provenance + identity fields the catalog plane needs to track.
 *
 * Out of scope (deferred to follow-up adoption passes):
 *   - `charter_voyages` — own lifecycle (sales status), own query surface.
 *   - `charter_yachts` — vessel reference data; cross-module link target.
 *   - `charter_suites` — selectable variant axis with own micro-registry.
 *   - `charter_schedule_days` — composite list (mixed-class leaves).
 */

import { defineFieldPolicy, type FieldPolicyInput } from "@voyant-travel/catalog/contract"

const CHARTER_FIELD_POLICY: FieldPolicyInput[] = [
  // ── Source pointer / provenance ─────────────────────────────────────────
  {
    path: "source.kind",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "source.ref",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "seller.operator_id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },

  // ── Identity / lifecycle ────────────────────────────────────────────────
  {
    path: "id",
    class: "managed",
    merge: "source-only",
    drift: "critical",
    reindex: "none",
    snapshot: "on-book",
    query: "first-class-table",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "slug",
    class: "managed",
    merge: "source-only",
    drift: "high",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "createdAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "static",
  },
  {
    path: "updatedAt",
    class: "managed",
    merge: "source-only",
    drift: "none",
    reindex: "none",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "externalRefs",
    class: "managed",
    merge: "source-only",
    drift: "medium",
    reindex: "none",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Merchandisable / marketing ──────────────────────────────────────────
  {
    path: "name",
    class: "merchandisable",
    merge: "replace",
    drift: "medium",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "description",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "blob-only",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "shortDescription",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry-locale",
    snapshot: "on-book",
    query: "indexed-column",
    localized: true,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "heroImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "thumbnailUrl",
    class: "merchandisable",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "mapImageUrl",
    class: "merchandisable",
    merge: "replace",
    drift: "low",
    reindex: "entry",
    snapshot: "on-book",
    query: "blob-only",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "marketing",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Structural / facet-affecting ───────────────────────────────────────
  {
    path: "status",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "lineSupplierId",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "defaultYachtId",
    class: "structural",
    merge: "source-only",
    drift: "medium",
    reindex: "entry",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // Same TODO as products / cruises — split into marketing_regions +
    // facet_regions per architecture §7.1.
    path: "regions[]",
    class: "structural",
    merge: "additive-set",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "ops",
    overrideFriction: "confirm",
    sourceFreshness: "sync",
  },
  {
    path: "themes[]",
    class: "structural",
    merge: "additive-set",
    drift: "medium",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "ops",
    overrideFriction: "confirm",
    sourceFreshness: "sync",
  },
  {
    path: "defaultBookingModes[]",
    class: "structural",
    merge: "source-only",
    drift: "high",
    reindex: "facet-affecting",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Charter-specific managed fields ────────────────────────────────────
  {
    // Soft FK to legal.contractTemplates — managed reference, captured at
    // booking time so refunds / disputes can read the contract template
    // that was in force.
    path: "defaultMybaTemplateId",
    class: "managed",
    merge: "source-only",
    drift: "high",
    reindex: "none",
    snapshot: "on-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    // APA % — operationally-tunable but legally-sensitive. Override allowed
    // (per-product) but with confirm-friction and audit trail.
    path: "defaultApaPercent",
    class: "managed",
    merge: "source-only",
    drift: "high",
    reindex: "none",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },

  // ── Volatile-indexed (browse-time approximations) ──────────────────────
  {
    path: "lowestPriceCachedAmount",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "lowestPriceCachedCurrency",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "entry",
    snapshot: "on-quote-and-book",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "earliestVoyageCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
  {
    path: "latestVoyageCached",
    class: "volatile-indexed",
    merge: "source-only",
    drift: "low",
    reindex: "facet-affecting",
    snapshot: "never",
    query: "indexed-column",
    localized: false,
    visibility: ["staff", "customer", "partner"],
    editRole: "none",
    overrideFriction: "none",
    sourceFreshness: "sync",
  },
]

export const charterCatalogPolicy = defineFieldPolicy(CHARTER_FIELD_POLICY)

export { CHARTER_FIELD_POLICY }
