/**
 * The framework-shipped standard-profile migration bundle (D.1). Loads this
 * package's `migrations/` folder as the `framework` collector source (priority
 * 0 — applied before the deployment's own migrations).
 *
 * Generated by `scripts/generate-framework-migration-bundle.mjs` from the
 * standard-profile aggregate schema. See `docs/architecture/migration-collector-d1.md`.
 */

import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type { MigrationSource } from "./collector.js"
import { loadMigrationFolder } from "./load-folder.js"

/** Absolute path to the shipped bundle folder (resolved relative to this module). */
export function frameworkBundleDir(): string {
  // src/bundle.ts → package root → migrations/  (dist/bundle.js → package root → migrations/)
  return join(dirname(fileURLToPath(import.meta.url)), "..", "migrations")
}

/**
 * The framework bundle as a collector source. `priority: 0` so it applies
 * before deployment migrations (their link tables FK into framework tables).
 */
export async function loadFrameworkBundleSource(
  dir: string = frameworkBundleDir(),
): Promise<MigrationSource> {
  return {
    name: "framework",
    priority: 0,
    migrations: await loadMigrationFolder(dir),
  }
}
