/**
 * The baseline cutline (ADR: docs/architecture/migration-collector-d2.md,
 * Decision 5): per package source, the migration tags the retired framework
 * bundle already materialised. On an existing D.1 database the D.2 collector
 * IMPORT-BASELINES these (records without executing) instead of running their
 * SQL. Backed by the committed `cutline.generated.json`, regenerated by
 * `scripts/d2/generate-cutline.mjs`.
 */
import { readFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"

/** package-source name -> the migration tags the bundle materialised. */
export type Cutline = Record<string, string[]>

/** Load the committed cutline manifest. Resolves relative to this module, so it
 *  works both from the workspace source and the published `dist/`. */
export async function loadCutline(): Promise<Cutline> {
  const path = fileURLToPath(new URL("../cutline.generated.json", import.meta.url))
  const raw = await readFile(path, "utf8")
  return (JSON.parse(raw) as { cutline: Cutline }).cutline
}
