/**
 * All entity prefixes for the Voyant platform.
 *
 * Convention:
 *   - Root entities: first N chars of the entity name, shortest unambiguous (2-4 chars).
 *     Examples: prod (product), book (booking), inv (invoice), pers (person), org (organization).
 *   - Child entities: 2-char module code + 2-char child suffix from the child entity's first chars.
 *     Examples: bk+it = bkit (booking_item), ch+co = chco (channel_contract).
 *   - All lowercase alphanumeric, max 4 chars.
 *   - Prefer guessable over clever — a developer should be able to guess the prefix from the entity name.
 */
export const PREFIXES = {
  // --- IAM ---
  user_profiles: "usrp",
  user_invitations: "uinv",
  connection_secrets: "secr",

  // --- INFRA ---
  webhook_subscriptions: "hksub",
  webhook_deliveries: "whde",
  rate_limit_buckets: "rlbk",
  public_document_delivery_grants: "pddg",
  domains: "dom",
  email_domain_records: "emdr",
  idempotency_keys: "ikey",
  event_outbox: "evob",
  write_intents: "wint",
  action_ledger_entries: "alge",
  action_ledger_payloads: "algp",
  action_delegations: "aldg",
  action_mutation_details: "almd",
  action_sensitive_read_details: "alsr",
  action_approvals: "alap",

  // --- VOYANT MODULES ---
  communication_log: "clog",
  customer_signals: "csig",
  notification_templates: "ntpl",
  notification_deliveries: "ntdl",
  notification_reminder_rules: "ntrl",
  notification_reminder_runs: "ntrn",
  notification_reminder_rule_stages: "ntrs",
  notification_reminder_stage_channels: "ntsc",
  notification_settings: "nset",
  person_notes: "pnot",
  organization_notes: "onot",
  segments: "seg",
  segment_members: "segm",
  suppliers: "supp",
  supplier_services: "ssvc",
  supplier_rates: "srat",
  supplier_notes: "snot",
  supplier_availability: "sava",
  supplier_contracts: "scon",
  products: "prod",
  product_options: "popt",
  option_units: "ount",
  product_activation_settings: "pras",
  product_ticket_settings: "prts",
  product_visibility_settings: "prvs",
  product_capabilities: "prcp",
  product_delivery_formats: "prdf",
  product_translations: "prtr",
  product_option_translations: "potr",
  option_unit_translations: "outr",
  product_itineraries: "piti",
  product_itinerary_translations: "pitr",
  product_days: "pday",
  product_day_services: "pdse",
  product_day_translations: "pdtr",
  product_day_service_translations: "pdsr",
  product_versions: "pver",
  product_notes: "prnt",
  bookings: "book",
  booking_travelers: "bkpt",
  booking_participants: "bkpt",
  booking_items: "bkit",
  booking_allocations: "bkac",
  booking_fulfillments: "bkfl",
  booking_redemption_events: "bkrd",
  booking_item_travelers: "bkip",
  booking_item_participants: "bkip",
  booking_staff_assignments: "bkstf",
  booking_passengers: "bkps",
  booking_supplier_statuses: "bkss",
  booking_activity_log: "bkal",
  booking_pii_access_log: "bkpl",
  booking_notes: "bnot",
  booking_documents: "bdoc",
  booking_groups: "bkgr",
  booking_group_members: "bkgm",
  booking_session_states: "bkst",
  availability_rules: "avrl",
  availability_start_times: "avst",
  availability_slots: "avsl",
  availability_closeouts: "avcl",
  allocation_resources: "alrs",
  allocation_audit_log: "alal",
  product_option_resource_templates: "port",
  availability_pickup_points: "avpp",
  availability_slot_pickups: "avsp",
  product_meeting_configs: "pmcf",
  pickup_groups: "pkgr",
  pickup_locations: "pklo",
  location_pickup_times: "lpkt",
  custom_pickup_areas: "cpka",
  organizations: "org",
  people: "pers",
  person_documents: "pdoc",
  person_relationships: "prel",
  pipelines: "pipe",
  stages: "stg",
  quotes: "quot",
  quote_participants: "qprt",
  quote_products: "qprd",
  quote_versions: "qver",
  quote_version_lines: "qtln",
  quote_media: "qmed",
  activities: "act",
  activity_links: "actl",
  activity_participants: "actp",
  custom_field_definitions: "cfdf",
  apps: "app",
  app_redirect_uris: "apru",
  app_credentials: "apcr",
  app_releases: "aprl",
  app_release_artifacts: "apra",
  app_release_localizations: "aplc",
  person_payment_methods: "pmth",
  invoices: "inv",
  payment_instruments: "pmin",
  travel_credits: "vch",
  travel_credit_redemptions: "vchr",
  payment_sessions: "pmss",
  payment_authorizations: "pmaz",
  payment_captures: "pmcp",
  booking_payment_schedules: "bkpy",
  booking_guarantees: "bkgu",
  booking_item_tax_lines: "bitx",
  booking_item_commissions: "bcom",
  invoice_line_items: "inli",
  payments: "pay",
  credit_notes: "crn",
  credit_note_line_items: "cnli",
  supplier_payments: "spay",
  // Accounts payable — supplier invoices the operator receives, their lines,
  // and the allocations that attribute each cost to a departure / product /
  // booking / traveller (per docs/architecture/supplier-invoices-profitability.md §5).
  supplier_invoices: "sinv",
  supplier_invoice_lines: "sinl",
  supplier_cost_allocations: "sial",
  supplier_invoice_attachments: "sina",
  cost_categories: "ccat",
  finance_notes: "fnot",
  resources: "res",
  resource_pools: "repl",
  resource_pool_members: "repm",
  resource_requirements: "rerq",
  resource_slot_assignments: "resa",
  resource_closeouts: "recl",
  ground_operators: "gopr",
  ground_vehicles: "gveh",
  ground_drivers: "gdrv",
  ground_transfer_preferences: "gtpr",
  ground_dispatches: "gdsp",
  ground_execution_events: "gexe",
  ground_dispatch_assignments: "gdas",
  ground_dispatch_legs: "gdlg",
  ground_dispatch_passengers: "gdps",
  ground_driver_shifts: "gdsh",
  ground_service_incidents: "gsin",
  ground_dispatch_checkpoints: "gdcp",
  channels: "chan",
  channel_contracts: "chco",
  channel_commission_rules: "chcr",
  channel_product_mappings: "chpm",
  channel_booking_links: "chbl",
  channel_webhook_events: "chwe",
  channel_inventory_allotments: "chia",
  channel_inventory_allotment_targets: "chat",
  channel_inventory_release_rules: "chir",
  channel_settlement_runs: "chsr",
  channel_settlement_items: "chsi",
  channel_reconciliation_runs: "chrr",
  channel_reconciliation_items: "chri",
  channel_inventory_release_executions: "chrx",
  channel_settlement_policies: "chsp",
  channel_reconciliation_policies: "chrp",
  channel_release_schedules: "chrs",
  channel_remittance_exceptions: "chre",
  channel_settlement_approvals: "chap",
  channel_availability_push_intents: "cavi",
  channel_content_push_intents: "ccpi",
  facilities: "fac",
  facility_contacts: "fcon",
  facility_features: "ffea",
  facility_operation_schedules: "fops",
  function_spaces: "fnsp",
  function_space_capacities: "fnsc",
  space_blocks: "spbl",
  space_block_slots: "spsl",
  space_block_pickups: "sppu",
  properties: "prop",
  property_groups: "pgrp",
  property_group_members: "pgpm",
  room_types: "hrmt",
  room_type_bed_configs: "hrbc",
  room_units: "hrun",
  meal_plans: "hmlp",
  rate_plans: "hrpl",
  rate_plan_room_types: "hrrt",
  rate_plan_daily_rates: "hrdr",
  stay_rules: "hstr",
  room_inventory: "hriv",
  room_type_daily_inventory: "hrdi",
  rate_plan_inventory_overrides: "hrio",
  stay_booking_items: "hsbi",
  stay_daily_rates: "hsdr",
  room_type_rates: "hrtr",
  room_blocks: "hrbl",
  room_block_nights: "hrbn",
  room_block_pickups: "hrbp",
  room_unit_status_events: "hrse",
  maintenance_blocks: "hmbl",
  housekeeping_tasks: "hhkt",
  stay_operations: "hsop",
  stay_checkpoints: "hscp",
  stay_service_posts: "hssp",
  stay_folios: "hsfo",
  stay_folio_lines: "hsfl",
  identity_contact_points: "idcp",
  identity_addresses: "idad",
  identity_named_contacts: "idnc",
  markets: "mkt",
  market_locales: "mklo",
  market_currencies: "mkcu",
  fx_rate_sets: "fxrs",
  exchange_rates: "fxrt",
  pricing_categories: "prcg",
  pricing_category_dependencies: "prcd",
  cancellation_policies: "ccpo",
  cancellation_policy_rules: "ccpr",
  price_catalogs: "prca",
  price_schedules: "prsc",
  option_price_rules: "oprr",
  option_unit_price_rules: "oupr",
  option_start_time_rules: "ostr",
  option_unit_tiers: "outi",
  pickup_price_rules: "pkpr",
  dropoff_price_rules: "drpr",
  extra_price_rules: "expr",
  departure_price_overrides: "dpov",
  product_extras: "pxtr",
  option_extra_configs: "oexc",
  booking_extras: "bkex",
  extra_participant_selections: "exps",
  product_contact_requirements: "pcre",
  product_booking_questions: "pbqq",
  option_booking_questions: "obqq",
  booking_question_options: "bqop",
  booking_question_unit_triggers: "bqut",
  booking_question_option_triggers: "bqot",
  booking_question_extra_triggers: "bqet",
  booking_answers: "bqan",
  storefront_verification_challenges: "svch",
  offers: "ofr",
  offer_contact_assignments: "ofca",
  offer_participants: "ofpt",
  offer_staff_assignments: "ofsa",
  offer_items: "ofit",
  offer_item_participants: "ofip",
  orders: "ord",
  order_contact_assignments: "orca",
  order_participants: "orpt",
  order_staff_assignments: "orsa",
  order_items: "orit",
  order_item_participants: "orip",
  order_terms: "ortm",
  transaction_pii_access_log: "tpal",
  market_price_catalogs: "mkpc",
  market_product_rules: "mkpr",
  market_channel_rules: "mkcr",
  external_refs: "exrf",
  sellability_snapshots: "sels",
  sellability_snapshot_items: "sesi",
  sellability_policies: "slpo",
  sellability_policy_results: "slpr",
  offer_refresh_runs: "ofrr",
  offer_expiration_events: "ofee",
  sellability_explanations: "slex",

  // --- CONTRACTS ---
  contracts: "cont",
  contract_templates: "ctpl",
  contract_template_versions: "ctpv",
  contract_signatures: "ctsi",
  contract_number_series: "ctns",
  contract_attachments: "ctat",

  // --- POLICIES ---
  policies: "pol",
  policy_versions: "plvr",
  policy_rules: "plrl",
  policy_assignments: "plas",
  policy_acceptances: "plac",

  // --- FINANCE (invoicing extensions) ---
  invoice_number_series: "invs",
  invoice_templates: "invt",
  invoice_renditions: "invr",
  invoice_attachments: "inat",
  tax_regimes: "txrg",
  invoice_external_refs: "iner",

  // --- PRODUCT MEDIA ---
  product_media: "pmed",
  product_features: "pftr",
  product_faqs: "pfaq",
  product_locations: "ploc",

  // --- PRODUCT TAXONOMY ---
  product_types: "ptyp",
  product_categories: "pctg",
  product_category_translations: "pctr",
  product_tags: "ptag",
  product_tag_translations: "pttr",
  destinations: "dest",
  destination_translations: "dtrn",
  product_destinations: "pdst",

  // --- BOOKING EXTENSIONS ---
  booking_product_details: "bkpd",
  booking_item_product_details: "bipd",
  booking_crm_details: "bkcd",
  booking_transaction_details: "bktd",
  booking_distribution_details: "bkdd",
  booking_traveler_travel_details: "bptd",
  booking_participant_travel_details: "bptd",

  // --- CRUISES ---
  cruises: "cru",
  cruise_voyage_groups: "crvg",
  cruise_voyage_group_segments: "crvs",
  cruise_sailings: "crsl",
  cruise_ships: "crsh",
  cruise_decks: "crdk",
  cruise_cabin_categories: "crcc",
  cruise_cabins: "crcb",
  cruise_prices: "crpx",
  cruise_price_components: "crpc",
  cruise_days: "crdy",
  cruise_sailing_days: "crsd",
  cruise_media: "crme",
  cruise_inclusions: "crin",
  cruise_search_index: "crsi",
  cruise_enrichment_programs: "crep",

  // --- CHARTERS ---
  charter_products: "chrt",
  charter_voyages: "chrv",
  charter_yachts: "chry",
  charter_suites: "chst",
  charter_schedule_days: "chrd",

  // --- CATALOG (cross-vertical infrastructure) ---
  catalog_overlay: "ovly",
  booking_catalog_snapshot: "bcsn",
  catalog_drift_event: "cdrf",
  catalog_quotes: "cquo",
  catalog_sourced_entries: "cse",
  catalog_content_drift_event: "cnde",
  catalog_demo_inventory: "cdmi",
  catalog_demo_orders: "cdmo",
  // Resumable session-bound draft for the unified booking journey.
  // Per docs/architecture/booking-journey-architecture.md §5.7 +
  // §12.10 (chose option B: ship as a sibling table to
  // booking_session_states).
  booking_drafts: "bdrf",

  // --- TRAVEL COMPOSER ---
  trip_envelopes: "trip",
  trip_components: "trcp",
  trip_component_events: "trce",
  trip_snapshots: "trsn",
  trip_reservation_plans: "trpl",
  trip_requirements: "trrq",
  trip_candidates: "trcd",

  // --- FINANCE (extensions for journey tax computation) ---
  // Per booking-journey-architecture §9. The classes are the per-
  // product treatment decision; tax_regimes remains the
  // jurisdictional rate catalog and is unchanged.
  tax_classes: "txcl",
  tax_policy_profiles: "txpp",
  tax_policy_rules: "txpr",
  // Per-product per-occupancy rate tier table for non-cruise
  // verticals. Cruises keep their specialized cruise_prices table.
  product_pax_pricing_tiers: "ppt",

  // --- AVAILABILITY (extension for booking-journey holds) ---
  // Soft holds against availability_slots tied to booking_drafts.
  // Per booking-journey-architecture §5.7 + §6 — the doc proposes
  // bookingAllocations for owned holds, but those require a
  // booking_id FK and journey holds are pre-booking. A dedicated
  // table is the cleanest fit.
  availability_holds: "avhd",

  // Workflow runs — observability for in-process workflows (the
  // catalog-checkout finalize spine, follow-up scheduled jobs, etc).
  // Lives outside the durable @voyant-travel/workflows orchestrator so
  // edge-compatible templates can record runs without spinning up
  // a separate Node process.
  workflow_runs: "wfrn",
  workflow_run_steps: "wfrs",
  // --- Operator-starter-local settings ---
  operator_settings: "opset",
  operator_profile: "oppf",
  operator_payment_instructions: "opin",
  operator_payment_defaults: "opdp",
  booking_tax_settings: "btxs",

  // --- PROMOTIONS (per docs/architecture/promotions-architecture.md §4.4) ---
  // promotional_offer_products is a join table (no `id` column).
  promotional_offers: "pofr",
  promotional_offer_redemptions: "pofx",
  // Boundary-scheduler watermark — single-row table, but typed for
  // registry completeness. Per §9.2 of the promotions architecture doc.
  promotional_offer_scheduler_state: "pofs",

  // --- MICE (group programs) — see RFC voyant#1489 ---
  // The group-program spine (operator-local). Room blocks live in
  // accommodations (room_blocks/hrbl above); this is the umbrella record.
  mice_programs: "prog",
  mice_program_sessions: "mpss",
  mice_session_inclusions: "mssi",
  mice_program_delegates: "mpdl",
  mice_delegate_session_enrollments: "mdse",
  mice_rooming_assignments: "mrma",
  mice_rooming_assignment_delegates: "mrad",
  mice_rfps: "mrfp",
  mice_rfp_invitations: "mrfi",
  mice_bids: "mbid",
  mice_bid_lines: "mbln",
  mice_bid_evaluations: "mbev",
  booking_mice_details: "bkmd",
} as const

export type PrefixKey = keyof typeof PREFIXES
export type PrefixValue = (typeof PREFIXES)[PrefixKey]
