import { canonicalJson, type ResolvedVoyantDeploymentGraph } from "./deployment-graph.js"
import type { VoyantProjectDeploymentMode } from "./profile.js"

export const VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION = "voyant.deployment-artifacts.v1" as const
export const VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID = "@voyant-travel/framework#runtime.node" as const

export type VoyantDeploymentRuntimeEntryKind = "managed-profile-node"

export interface VoyantDeploymentRuntimeEntryArtifact {
  id: string
  target: string
  file: string
  graphHash: string
  kind: VoyantDeploymentRuntimeEntryKind
  profileSnapshot: string
}

export interface VoyantDeploymentMigrationSourceArtifact {
  packageName: string
  schema: string
}

export interface VoyantDeploymentArtifactManifest {
  schemaVersion: typeof VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION
  graphHash: string
  graph: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildDeploymentArtifactManifestInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources?: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildManagedNodeRuntimeEntryArtifactInput {
  graph: ResolvedVoyantDeploymentGraph
  file: string
  profileSnapshot: string
  id?: string
}

export interface BuildManagedNodeRuntimeEntryInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  profileSnapshotPath: string
  command?: string
}

export function buildDeploymentGraphJson(graph: ResolvedVoyantDeploymentGraph): string {
  return `${JSON.stringify(JSON.parse(canonicalJson(graph)), null, 2)}\n`
}

export function buildDeploymentArtifactManifest(
  input: BuildDeploymentArtifactManifestInput,
): VoyantDeploymentArtifactManifest {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  for (const entry of input.runtimeEntries) {
    assertRelativeArtifactPath(entry.file, `runtime entry "${entry.id}" file`)
    assertRelativeArtifactPath(entry.profileSnapshot, `runtime entry "${entry.id}" profileSnapshot`)
    if (entry.graphHash !== input.graph.contentHash) {
      throw new Error(
        `runtime entry "${entry.id}" graphHash must match ${input.graph.contentHash}, got ${entry.graphHash}`,
      )
    }
  }

  return {
    schemaVersion: VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION,
    graphHash: input.graph.contentHash,
    graph: input.graphArtifactPath,
    runtimeEntries: [...input.runtimeEntries].sort((left, right) =>
      left.id.localeCompare(right.id),
    ),
    migrationSources: normalizeMigrationSources(input.migrationSources ?? []),
  }
}

export function buildManagedNodeRuntimeEntryArtifact(
  input: BuildManagedNodeRuntimeEntryArtifactInput,
): VoyantDeploymentRuntimeEntryArtifact {
  assertRelativeArtifactPath(input.file, "file")
  assertRelativeArtifactPath(input.profileSnapshot, "profileSnapshot")
  return {
    id: input.id ?? VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID,
    target: input.graph.deployment.target ?? "node",
    file: input.file,
    graphHash: input.graph.contentHash,
    kind: "managed-profile-node",
    profileSnapshot: input.profileSnapshot,
  }
}

export function buildManagedNodeRuntimeEntry(input: BuildManagedNodeRuntimeEntryInput): string {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  assertRelativeArtifactPath(input.profileSnapshotPath, "profileSnapshotPath")

  const command = input.command ?? "voyant deployment graph emit"
  return `// GENERATED by ${command} - do not edit.
// Recreate after changing the managed profile, package lockfile, or graph resolver.

import { fileURLToPath, pathToFileURL } from "node:url"

export const GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION = ${quote(input.graph.schemaVersion)} as const
export const GENERATED_DEPLOYMENT_GRAPH_HASH = ${quote(input.graph.contentHash)} as const
export const GENERATED_DEPLOYMENT_GRAPH_TARGET = ${quote(input.graph.deployment.target)} as const
export const GENERATED_DEPLOYMENT_GRAPH_MODE = ${quote(input.graph.deployment.mode)} as const
export const GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH = ${quote(input.graphArtifactPath)} as const
export const GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH = ${quote(input.profileSnapshotPath)} as const

export const GENERATED_DEPLOYMENT_GRAPH_MODULE_IDS = ${formatConstArray(
    input.graph.modules.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PLUGIN_IDS = ${formatConstArray(
    input.graph.plugins.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PACKAGE_NAMES = ${formatConstArray(
    input.graph.packageRecords.map((record) => record.packageName),
  )}

export function resolveGeneratedProfileSnapshotPath(): string {
  const fromEnv = process.env.MANAGED_PROFILE_SNAPSHOT?.trim()
  if (fromEnv) return fromEnv
  return fileURLToPath(new URL(GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH, import.meta.url))
}

const isMainModule = import.meta.url === pathToFileURL(process.argv[1] ?? "").href
if (isMainModule) {
  const { startManagedProfileRuntime } = await import("@voyant-travel/framework/managed-runtime")
  const handle = await startManagedProfileRuntime({
    profileSnapshotPath: resolveGeneratedProfileSnapshotPath(),
  })
  console.info(
    \`[managed-runtime] Node runtime listening on :\${handle.port} (\${GENERATED_DEPLOYMENT_GRAPH_HASH})\`,
  )
}
`
}

function formatConstArray(values: readonly string[]): string {
  if (values.length === 0) return "[] as const"
  return `[\n${values.map((value) => `  ${quote(value)},`).join("\n")}\n] as const`
}

function quote(value: string | VoyantProjectDeploymentMode | undefined): string {
  return JSON.stringify(value ?? null)
}

function normalizeMigrationSources(
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[],
): VoyantDeploymentMigrationSourceArtifact[] {
  return migrationSources.map((source) => {
    assertRelativeArtifactPath(source.schema, `migration source "${source.packageName}" schema`)
    return { packageName: source.packageName, schema: source.schema }
  })
}

function assertRelativeArtifactPath(value: string, label: string): void {
  if (value.startsWith("/") || /^[a-zA-Z]:[\\/]/.test(value)) {
    throw new Error(`${label} must be a relative path, got ${value}`)
  }
  if (value.includes("\\")) {
    throw new Error(`${label} must use POSIX separators, got ${value}`)
  }
}
