import {
  canonicalJson,
  packageNameFromSpecifier,
  type ResolvedVoyantDeploymentGraph,
  type ResolvedVoyantGraphUnit,
} from "./deployment-graph.js"
import { PROVIDER_ROLES, type VoyantProjectDeploymentMode } from "./profile.js"

export {
  type CreateVoyantGraphRuntimeInput,
  createVoyantGraphRuntime,
  VOYANT_GRAPH_RUNTIME_LOAD_ERROR_CODES,
  type VoyantGraphRuntime,
  VoyantGraphRuntimeLoadError,
  type VoyantGraphRuntimeLoadErrorCode,
  type VoyantGraphRuntimeRouteDefinition,
  type VoyantGraphRuntimeRouteLoader,
  type VoyantGraphRuntimeUnitDefinition,
  type VoyantGraphRuntimeUnitLoader,
} from "./runtime-lowering.js"

export const VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION = "voyant.deployment-artifacts.v1" as const
export const VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID = "@voyant-travel/framework#runtime.node" as const

export type VoyantDeploymentRuntimeEntryKind = "managed-profile-node"

export interface VoyantDeploymentRuntimeEntryArtifact {
  id: string
  target: string
  file: string
  graphHash: string
  kind: VoyantDeploymentRuntimeEntryKind
  profileSnapshot: string
}

export interface VoyantDeploymentMigrationSourceArtifact {
  packageName: string
  schema: string
}

export interface VoyantDeploymentArtifactManifest {
  schemaVersion: typeof VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION
  graphHash: string
  graph: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildDeploymentArtifactManifestInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources?: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildManagedNodeRuntimeEntryArtifactInput {
  graph: ResolvedVoyantDeploymentGraph
  file: string
  profileSnapshot: string
  id?: string
}

export interface BuildManagedNodeRuntimeEntryInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  profileSnapshotPath: string
  command?: string
}

export interface BuildGraphRuntimeModuleInput {
  graph: ResolvedVoyantDeploymentGraph
  command?: string
}

interface GeneratedRuntimeRouteDefinition {
  route: ResolvedVoyantGraphUnit["api"][number]
  importEntry: string
}

interface GeneratedRuntimeUnitDefinition {
  id: string
  kind: ResolvedVoyantGraphUnit["kind"]
  packageName: string
  order: number
  routes: GeneratedRuntimeRouteDefinition[]
}

export function buildDeploymentGraphJson(graph: ResolvedVoyantDeploymentGraph): string {
  return `${JSON.stringify(JSON.parse(canonicalJson(graph)), null, 2)}\n`
}

/**
 * Emit target-neutral lazy package loaders from the selected graph. Import
 * expressions stay in generated source and are never evaluated by resolution
 * or artifact generation.
 */
export function buildGraphRuntimeModule(input: BuildGraphRuntimeModuleInput): string {
  assertGraphRuntimeLowerable(input.graph)

  const modules = lowerRuntimeUnits(input.graph.modules, input.graph)
  const plugins = lowerRuntimeUnits(input.graph.plugins, input.graph)
  const entries = [
    ...new Set(
      [...modules, ...plugins].flatMap((unit) =>
        unit.routes.map((definition) => definition.importEntry),
      ),
    ),
  ].sort((left, right) => left.localeCompare(right))
  const command = input.command ?? "voyant deployment graph emit"

  return `// GENERATED by ${command} - do not edit.
// Package runtime bodies remain behind lazy imports selected by the resolved graph.

import {
  createVoyantGraphRuntime,
  type VoyantGraphRuntime,
} from "@voyant-travel/framework/deployment-artifacts"

export const GENERATED_GRAPH_RUNTIME_HASH = ${quote(input.graph.contentHash)} as const
export const GENERATED_GRAPH_RUNTIME_ENTRY_SPECIFIERS = ${formatConstArray(entries)}
export const GENERATED_GRAPH_RUNTIME_MODULE_IDS = ${formatConstArray(
    modules.map((unit) => unit.id),
  )}
export const GENERATED_GRAPH_RUNTIME_PLUGIN_IDS = ${formatConstArray(
    plugins.map((unit) => unit.id),
  )}

const GENERATED_GRAPH_RUNTIME_IMPORTERS = ${formatRuntimeImporters(entries)}

export function createGeneratedGraphRuntime(): VoyantGraphRuntime {
  return createVoyantGraphRuntime({
    graphHash: GENERATED_GRAPH_RUNTIME_HASH,
    entries: GENERATED_GRAPH_RUNTIME_IMPORTERS,
    modules: ${formatGeneratedValue(modules, 4)},
    plugins: ${formatGeneratedValue(plugins, 4)},
  })
}
`
}

export function buildDeploymentArtifactManifest(
  input: BuildDeploymentArtifactManifestInput,
): VoyantDeploymentArtifactManifest {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  for (const entry of input.runtimeEntries) {
    assertRelativeArtifactPath(entry.file, `runtime entry "${entry.id}" file`)
    assertRelativeArtifactPath(entry.profileSnapshot, `runtime entry "${entry.id}" profileSnapshot`)
    if (entry.graphHash !== input.graph.contentHash) {
      throw new Error(
        `runtime entry "${entry.id}" graphHash must match ${input.graph.contentHash}, got ${entry.graphHash}`,
      )
    }
  }

  return {
    schemaVersion: VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION,
    graphHash: input.graph.contentHash,
    graph: input.graphArtifactPath,
    runtimeEntries: [...input.runtimeEntries].sort((left, right) =>
      left.id.localeCompare(right.id),
    ),
    migrationSources: normalizeMigrationSources(input.migrationSources ?? []),
  }
}

export function buildManagedNodeRuntimeEntryArtifact(
  input: BuildManagedNodeRuntimeEntryArtifactInput,
): VoyantDeploymentRuntimeEntryArtifact {
  assertRelativeArtifactPath(input.file, "file")
  assertRelativeArtifactPath(input.profileSnapshot, "profileSnapshot")
  return {
    id: input.id ?? VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID,
    target: input.graph.deployment.target ?? "node",
    file: input.file,
    graphHash: input.graph.contentHash,
    kind: "managed-profile-node",
    profileSnapshot: input.profileSnapshot,
  }
}

export function buildManagedNodeRuntimeEntry(input: BuildManagedNodeRuntimeEntryInput): string {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  assertRelativeArtifactPath(input.profileSnapshotPath, "profileSnapshotPath")

  const command = input.command ?? "voyant deployment graph emit"
  return `// GENERATED by ${command} - do not edit.
// Recreate after changing the managed profile, package lockfile, or graph resolver.
// Compatibility boundary: managed profile boot remains snapshot-manifest based;
// self-host operator composition consumes the separate generated graph runtime module.

import { readFileSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"

import type { VoyantGraphDeploymentRequirements } from "@voyant-travel/framework/deployment-graph"
import type { ManagedProfileRuntimeDeployment } from "@voyant-travel/framework/managed-runtime"

export const GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION = ${quote(input.graph.schemaVersion)} as const
export const GENERATED_DEPLOYMENT_GRAPH_HASH = ${quote(input.graph.contentHash)} as const
export const GENERATED_DEPLOYMENT_GRAPH_TARGET = ${quote(input.graph.deployment.target)} as const
export const GENERATED_DEPLOYMENT_GRAPH_MODE = ${quote(input.graph.deployment.mode)} as const
export const GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH = ${quote(input.graphArtifactPath)} as const
export const GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH = ${quote(input.profileSnapshotPath)} as const

export const GENERATED_DEPLOYMENT_GRAPH_MODULE_IDS = ${formatConstArray(
    input.graph.modules.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PLUGIN_IDS = ${formatConstArray(
    input.graph.plugins.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PACKAGE_NAMES = ${formatConstArray(
    input.graph.packageRecords.map((record) => record.packageName),
  )}

export function resolveGeneratedProfileSnapshotPath(): string {
  const fromEnv = process.env.MANAGED_PROFILE_SNAPSHOT?.trim()
  if (fromEnv) return fromEnv
  return fileURLToPath(new URL(GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH, import.meta.url))
}

export function assertGeneratedDeploymentGraphArtifact(): void {
  const graph = readGeneratedDeploymentGraph()
  if (graph.schemaVersion !== GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION) {
    throw new Error(
      \`Generated deployment graph schemaVersion \${String(
        graph.schemaVersion,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION}\`,
    )
  }
  if (graph.contentHash !== GENERATED_DEPLOYMENT_GRAPH_HASH) {
    throw new Error(
      \`Generated deployment graph contentHash \${String(
        graph.contentHash,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_HASH}\`,
    )
  }
  if (graph.deployment?.target !== GENERATED_DEPLOYMENT_GRAPH_TARGET) {
    throw new Error(
      \`Generated deployment graph target \${String(
        graph.deployment?.target,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_TARGET}\`,
    )
  }
  if (graph.deployment?.mode !== GENERATED_DEPLOYMENT_GRAPH_MODE) {
    throw new Error(
      \`Generated deployment graph mode \${String(
        graph.deployment?.mode,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_MODE}\`,
    )
  }
  const errorDiagnostics = Array.isArray(graph.diagnostics)
    ? graph.diagnostics.filter(isErrorDiagnostic)
    : []
  if (errorDiagnostics.length > 0) {
    throw new Error(
      \`Generated deployment graph contains \${errorDiagnostics.length} error diagnostic(s):\\n\${errorDiagnostics
        .map(formatGeneratedDiagnostic)
        .join("\\n")}\`,
    )
  }
}

export function resolveGeneratedDeploymentRequirements(): VoyantGraphDeploymentRequirements {
  const requirements = readGeneratedDeploymentGraph().requirements
  if (!requirements || typeof requirements !== "object" || Array.isArray(requirements)) {
    throw new Error("Generated deployment graph requirements are missing or invalid")
  }
  const candidate = requirements as { resources?: unknown }
  if (!Array.isArray(candidate.resources)) {
    throw new Error("Generated deployment graph requirements.resources must be an array")
  }
  return candidate as VoyantGraphDeploymentRequirements
}

export function resolveGeneratedRuntimeDeployment(): ManagedProfileRuntimeDeployment {
  const deployment = readGeneratedDeploymentGraph().deployment
  if (!deployment || typeof deployment !== "object" || Array.isArray(deployment)) {
    throw new Error("Generated deployment graph deployment is missing or invalid")
  }
  const candidate = deployment as { mode?: unknown; providers?: unknown }
  if (
    candidate.mode !== "local" &&
    candidate.mode !== "managed-cloud" &&
    candidate.mode !== "self-hosted"
  ) {
    throw new Error("Generated deployment graph deployment.mode is invalid")
  }
  if (!isGeneratedRecord(candidate.providers)) {
    throw new Error("Generated deployment graph deployment.providers is missing or invalid")
  }
  const providers: ManagedProfileRuntimeDeployment["providers"] = ${formatRuntimeDeploymentProviders()}
  return {
    mode: candidate.mode,
    providers,
  }
}

function requireGeneratedDeploymentProvider<
  Role extends keyof ManagedProfileRuntimeDeployment["providers"],
>(
  providers: Record<string, unknown>,
  role: Role,
): ManagedProfileRuntimeDeployment["providers"][Role] {
  const provider = providers[role]
  if (typeof provider !== "string" || provider.trim().length === 0) {
    throw new Error(
      \`Generated deployment graph deployment.providers.\${role} must be a non-empty string\`,
    )
  }
  return provider as ManagedProfileRuntimeDeployment["providers"][Role]
}

function isGeneratedRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value)
}

function readGeneratedDeploymentGraph(): {
  schemaVersion?: unknown
  contentHash?: unknown
  deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
  requirements?: unknown
  diagnostics?: unknown
} {
  return JSON.parse(
    readFileSync(
      fileURLToPath(new URL(GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH, import.meta.url)),
      "utf8",
    ),
  ) as {
    schemaVersion?: unknown
    contentHash?: unknown
    deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
    requirements?: unknown
    diagnostics?: unknown
  }
}

const isMainModule = import.meta.url === pathToFileURL(process.argv[1] ?? "").href
if (isMainModule) {
  assertGeneratedDeploymentGraphArtifact()
  const { startManagedProfileRuntime } = await import("@voyant-travel/framework/managed-runtime")
  const handle = await startManagedProfileRuntime({
    profileSnapshotPath: resolveGeneratedProfileSnapshotPath(),
    deployment: resolveGeneratedRuntimeDeployment(),
    deploymentRequirements: resolveGeneratedDeploymentRequirements(),
  })
  console.info(
    \`[managed-runtime] Node runtime listening on :\${handle.port} (\${GENERATED_DEPLOYMENT_GRAPH_HASH})\`,
  )
}

function isErrorDiagnostic(value: unknown): boolean {
  if (!value || typeof value !== "object" || Array.isArray(value) || !("severity" in value)) {
    return false
  }
  return (value as { severity?: unknown }).severity === "error"
}

function formatGeneratedDiagnostic(value: unknown): string {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "- unknown diagnostic"
  const diagnostic = value as { code?: unknown; message?: unknown; source?: unknown; facet?: unknown }
  const context = [
    typeof diagnostic.source === "string" ? \`source=\${diagnostic.source}\` : undefined,
    typeof diagnostic.facet === "string" ? \`facet=\${diagnostic.facet}\` : undefined,
  ]
    .filter(Boolean)
    .join(", ")
  return \`- \${String(diagnostic.code ?? "UNKNOWN")}: \${String(diagnostic.message ?? "")}\${
    context ? \` (\${context})\` : ""
  }\`
}
`
}

function assertGraphRuntimeLowerable(graph: ResolvedVoyantDeploymentGraph): void {
  const errors = graph.diagnostics.filter((diagnostic) => diagnostic.severity === "error")
  if (errors.length === 0) return

  throw new Error(
    `buildGraphRuntimeModule: resolved graph contains ${errors.length} error diagnostic(s):\n${errors
      .map(
        (diagnostic) =>
          `- ${diagnostic.code}: ${diagnostic.message}${diagnostic.source ? ` (source=${diagnostic.source})` : ""}`,
      )
      .join("\n")}`,
  )
}

function lowerRuntimeUnits(
  units: readonly ResolvedVoyantGraphUnit[],
  graph: ResolvedVoyantDeploymentGraph,
): GeneratedRuntimeUnitDefinition[] {
  const admittedPackages = new Set(graph.packageRecords.map((record) => record.packageName))

  return units
    .flatMap((unit) => {
      const routes = unit.api
        .filter((route) => route.runtime !== undefined)
        .map((route) => {
          const runtime = route.runtime
          if (!runtime) {
            throw new Error(
              `buildGraphRuntimeModule: route "${route.id}" was selected for lowering without a runtime reference.`,
            )
          }
          const referencedPackage = runtime.entry.startsWith(".")
            ? unit.packageName
            : packageNameFromSpecifier(runtime.entry)
          if (!admittedPackages.has(referencedPackage)) {
            throw new Error(
              `buildGraphRuntimeModule: runtime entry "${runtime.entry}" for ${unit.id} route ${route.id} resolves to package "${referencedPackage}", which is not admitted by the graph.`,
            )
          }
          return {
            route,
            importEntry: lowerRuntimeImportEntry(unit, runtime.entry),
          }
        })
        .sort((left, right) => left.route.id.localeCompare(right.route.id))

      return [
        {
          id: unit.id,
          kind: unit.kind,
          packageName: unit.packageName,
          order: unit.order,
          routes,
        },
      ]
    })
    .sort((left, right) => left.order - right.order || left.id.localeCompare(right.id))
}

function lowerRuntimeImportEntry(unit: ResolvedVoyantGraphUnit, entry: string): string {
  if (!entry.startsWith(".")) return entry
  if (entry === "." || entry === "./") return unit.packageName
  if (!entry.startsWith("./") || entry.includes("\\")) {
    throw new Error(
      `buildGraphRuntimeModule: runtime entry "${entry}" for ${unit.id} must be an owner-relative "./" package export.`,
    )
  }

  const parts = entry.slice(2).split("/")
  if (parts.some((part) => part.length === 0 || part === "." || part === "..")) {
    throw new Error(
      `buildGraphRuntimeModule: runtime entry "${entry}" for ${unit.id} contains an invalid package export path.`,
    )
  }
  return `${unit.packageName}/${parts.join("/")}`
}

function formatRuntimeImporters(entries: readonly string[]): string {
  if (entries.length === 0) {
    return "{} satisfies Readonly<Record<string, () => Promise<unknown>>>"
  }
  return `{
${entries.map((entry) => `  ${quote(entry)}: () => import(${quote(entry)}),`).join("\n")}
} satisfies Readonly<Record<string, () => Promise<unknown>>>`
}

function formatGeneratedValue(value: unknown, continuationIndent: number): string {
  const formatted = JSON.stringify(JSON.parse(canonicalJson(value)), null, 2)
  return formatted.replaceAll("\n", `\n${" ".repeat(continuationIndent)}`)
}

function formatConstArray(values: readonly string[]): string {
  if (values.length === 0) return "[] as const"
  return `[\n${values.map((value) => `  ${quote(value)},`).join("\n")}\n] as const`
}

function formatRuntimeDeploymentProviders(): string {
  return `{\n${PROVIDER_ROLES.map(
    (role) =>
      `    ${role}: requireGeneratedDeploymentProvider(candidate.providers, ${quote(role)}),`,
  ).join("\n")}\n  }`
}

function quote(value: string | VoyantProjectDeploymentMode | undefined): string {
  return JSON.stringify(value ?? null)
}

function normalizeMigrationSources(
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[],
): VoyantDeploymentMigrationSourceArtifact[] {
  return migrationSources.map((source) => {
    assertRelativeArtifactPath(source.schema, `migration source "${source.packageName}" schema`)
    return { packageName: source.packageName, schema: source.schema }
  })
}

function assertRelativeArtifactPath(value: string, label: string): void {
  if (value.startsWith("/") || /^[a-zA-Z]:[\\/]/.test(value)) {
    throw new Error(`${label} must be a relative path, got ${value}`)
  }
  if (value.includes("\\")) {
    throw new Error(`${label} must use POSIX separators, got ${value}`)
  }
}
