import { canonicalJson, type ResolvedVoyantDeploymentGraph } from "./deployment-graph.js"
import { PROVIDER_ROLES, type VoyantProjectDeploymentMode } from "./profile.js"

export const VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION = "voyant.deployment-artifacts.v1" as const
export const VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID = "@voyant-travel/framework#runtime.node" as const

export type VoyantDeploymentRuntimeEntryKind = "managed-profile-node"

export interface VoyantDeploymentRuntimeEntryArtifact {
  id: string
  target: string
  file: string
  graphHash: string
  kind: VoyantDeploymentRuntimeEntryKind
  profileSnapshot: string
}

export interface VoyantDeploymentMigrationSourceArtifact {
  packageName: string
  schema: string
}

export interface VoyantDeploymentArtifactManifest {
  schemaVersion: typeof VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION
  graphHash: string
  graph: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildDeploymentArtifactManifestInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  runtimeEntries: readonly VoyantDeploymentRuntimeEntryArtifact[]
  migrationSources?: readonly VoyantDeploymentMigrationSourceArtifact[]
}

export interface BuildManagedNodeRuntimeEntryArtifactInput {
  graph: ResolvedVoyantDeploymentGraph
  file: string
  profileSnapshot: string
  id?: string
}

export interface BuildManagedNodeRuntimeEntryInput {
  graph: ResolvedVoyantDeploymentGraph
  graphArtifactPath: string
  profileSnapshotPath: string
  command?: string
}

export function buildDeploymentGraphJson(graph: ResolvedVoyantDeploymentGraph): string {
  return `${JSON.stringify(JSON.parse(canonicalJson(graph)), null, 2)}\n`
}

export function buildDeploymentArtifactManifest(
  input: BuildDeploymentArtifactManifestInput,
): VoyantDeploymentArtifactManifest {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  for (const entry of input.runtimeEntries) {
    assertRelativeArtifactPath(entry.file, `runtime entry "${entry.id}" file`)
    assertRelativeArtifactPath(entry.profileSnapshot, `runtime entry "${entry.id}" profileSnapshot`)
    if (entry.graphHash !== input.graph.contentHash) {
      throw new Error(
        `runtime entry "${entry.id}" graphHash must match ${input.graph.contentHash}, got ${entry.graphHash}`,
      )
    }
  }

  return {
    schemaVersion: VOYANT_DEPLOYMENT_ARTIFACTS_SCHEMA_VERSION,
    graphHash: input.graph.contentHash,
    graph: input.graphArtifactPath,
    runtimeEntries: [...input.runtimeEntries].sort((left, right) =>
      left.id.localeCompare(right.id),
    ),
    migrationSources: normalizeMigrationSources(input.migrationSources ?? []),
  }
}

export function buildManagedNodeRuntimeEntryArtifact(
  input: BuildManagedNodeRuntimeEntryArtifactInput,
): VoyantDeploymentRuntimeEntryArtifact {
  assertRelativeArtifactPath(input.file, "file")
  assertRelativeArtifactPath(input.profileSnapshot, "profileSnapshot")
  return {
    id: input.id ?? VOYANT_MANAGED_NODE_RUNTIME_ENTRY_ID,
    target: input.graph.deployment.target ?? "node",
    file: input.file,
    graphHash: input.graph.contentHash,
    kind: "managed-profile-node",
    profileSnapshot: input.profileSnapshot,
  }
}

export function buildManagedNodeRuntimeEntry(input: BuildManagedNodeRuntimeEntryInput): string {
  assertRelativeArtifactPath(input.graphArtifactPath, "graphArtifactPath")
  assertRelativeArtifactPath(input.profileSnapshotPath, "profileSnapshotPath")

  const command = input.command ?? "voyant deployment graph emit"
  return `// GENERATED by ${command} - do not edit.
// Recreate after changing the managed profile, package lockfile, or graph resolver.

import { readFileSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"

import type { VoyantGraphDeploymentRequirements } from "@voyant-travel/framework/deployment-graph"
import type { ManagedProfileRuntimeDeployment } from "@voyant-travel/framework/managed-runtime"

export const GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION = ${quote(input.graph.schemaVersion)} as const
export const GENERATED_DEPLOYMENT_GRAPH_HASH = ${quote(input.graph.contentHash)} as const
export const GENERATED_DEPLOYMENT_GRAPH_TARGET = ${quote(input.graph.deployment.target)} as const
export const GENERATED_DEPLOYMENT_GRAPH_MODE = ${quote(input.graph.deployment.mode)} as const
export const GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH = ${quote(input.graphArtifactPath)} as const
export const GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH = ${quote(input.profileSnapshotPath)} as const

export const GENERATED_DEPLOYMENT_GRAPH_MODULE_IDS = ${formatConstArray(
    input.graph.modules.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PLUGIN_IDS = ${formatConstArray(
    input.graph.plugins.map((unit) => unit.id),
  )}
export const GENERATED_DEPLOYMENT_GRAPH_PACKAGE_NAMES = ${formatConstArray(
    input.graph.packageRecords.map((record) => record.packageName),
  )}

export function resolveGeneratedProfileSnapshotPath(): string {
  const fromEnv = process.env.MANAGED_PROFILE_SNAPSHOT?.trim()
  if (fromEnv) return fromEnv
  return fileURLToPath(new URL(GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH, import.meta.url))
}

export function assertGeneratedDeploymentGraphArtifact(): void {
  const graph = readGeneratedDeploymentGraph()
  if (graph.schemaVersion !== GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION) {
    throw new Error(
      \`Generated deployment graph schemaVersion \${String(
        graph.schemaVersion,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION}\`,
    )
  }
  if (graph.contentHash !== GENERATED_DEPLOYMENT_GRAPH_HASH) {
    throw new Error(
      \`Generated deployment graph contentHash \${String(
        graph.contentHash,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_HASH}\`,
    )
  }
  if (graph.deployment?.target !== GENERATED_DEPLOYMENT_GRAPH_TARGET) {
    throw new Error(
      \`Generated deployment graph target \${String(
        graph.deployment?.target,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_TARGET}\`,
    )
  }
  if (graph.deployment?.mode !== GENERATED_DEPLOYMENT_GRAPH_MODE) {
    throw new Error(
      \`Generated deployment graph mode \${String(
        graph.deployment?.mode,
      )} does not match \${GENERATED_DEPLOYMENT_GRAPH_MODE}\`,
    )
  }
  const errorDiagnostics = Array.isArray(graph.diagnostics)
    ? graph.diagnostics.filter(isErrorDiagnostic)
    : []
  if (errorDiagnostics.length > 0) {
    throw new Error(
      \`Generated deployment graph contains \${errorDiagnostics.length} error diagnostic(s):\\n\${errorDiagnostics
        .map(formatGeneratedDiagnostic)
        .join("\\n")}\`,
    )
  }
}

export function resolveGeneratedDeploymentRequirements(): VoyantGraphDeploymentRequirements {
  const requirements = readGeneratedDeploymentGraph().requirements
  if (!requirements || typeof requirements !== "object" || Array.isArray(requirements)) {
    throw new Error("Generated deployment graph requirements are missing or invalid")
  }
  const candidate = requirements as { resources?: unknown }
  if (!Array.isArray(candidate.resources)) {
    throw new Error("Generated deployment graph requirements.resources must be an array")
  }
  return candidate as VoyantGraphDeploymentRequirements
}

export function resolveGeneratedRuntimeDeployment(): ManagedProfileRuntimeDeployment {
  const deployment = readGeneratedDeploymentGraph().deployment
  if (!deployment || typeof deployment !== "object" || Array.isArray(deployment)) {
    throw new Error("Generated deployment graph deployment is missing or invalid")
  }
  const candidate = deployment as { mode?: unknown; providers?: unknown }
  if (
    candidate.mode !== "local" &&
    candidate.mode !== "managed-cloud" &&
    candidate.mode !== "self-hosted"
  ) {
    throw new Error("Generated deployment graph deployment.mode is invalid")
  }
  if (!isGeneratedRecord(candidate.providers)) {
    throw new Error("Generated deployment graph deployment.providers is missing or invalid")
  }
  const providers: ManagedProfileRuntimeDeployment["providers"] = ${formatRuntimeDeploymentProviders()}
  return {
    mode: candidate.mode,
    providers,
  }
}

function requireGeneratedDeploymentProvider<
  Role extends keyof ManagedProfileRuntimeDeployment["providers"],
>(
  providers: Record<string, unknown>,
  role: Role,
): ManagedProfileRuntimeDeployment["providers"][Role] {
  const provider = providers[role]
  if (typeof provider !== "string" || provider.trim().length === 0) {
    throw new Error(
      \`Generated deployment graph deployment.providers.\${role} must be a non-empty string\`,
    )
  }
  return provider as ManagedProfileRuntimeDeployment["providers"][Role]
}

function isGeneratedRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value)
}

function readGeneratedDeploymentGraph(): {
  schemaVersion?: unknown
  contentHash?: unknown
  deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
  requirements?: unknown
  diagnostics?: unknown
} {
  return JSON.parse(
    readFileSync(
      fileURLToPath(new URL(GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH, import.meta.url)),
      "utf8",
    ),
  ) as {
    schemaVersion?: unknown
    contentHash?: unknown
    deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
    requirements?: unknown
    diagnostics?: unknown
  }
}

const isMainModule = import.meta.url === pathToFileURL(process.argv[1] ?? "").href
if (isMainModule) {
  assertGeneratedDeploymentGraphArtifact()
  const { startManagedProfileRuntime } = await import("@voyant-travel/framework/managed-runtime")
  const handle = await startManagedProfileRuntime({
    profileSnapshotPath: resolveGeneratedProfileSnapshotPath(),
    deployment: resolveGeneratedRuntimeDeployment(),
    deploymentRequirements: resolveGeneratedDeploymentRequirements(),
  })
  console.info(
    \`[managed-runtime] Node runtime listening on :\${handle.port} (\${GENERATED_DEPLOYMENT_GRAPH_HASH})\`,
  )
}

function isErrorDiagnostic(value: unknown): boolean {
  if (!value || typeof value !== "object" || Array.isArray(value) || !("severity" in value)) {
    return false
  }
  return (value as { severity?: unknown }).severity === "error"
}

function formatGeneratedDiagnostic(value: unknown): string {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "- unknown diagnostic"
  const diagnostic = value as { code?: unknown; message?: unknown; source?: unknown; facet?: unknown }
  const context = [
    typeof diagnostic.source === "string" ? \`source=\${diagnostic.source}\` : undefined,
    typeof diagnostic.facet === "string" ? \`facet=\${diagnostic.facet}\` : undefined,
  ]
    .filter(Boolean)
    .join(", ")
  return \`- \${String(diagnostic.code ?? "UNKNOWN")}: \${String(diagnostic.message ?? "")}\${
    context ? \` (\${context})\` : ""
  }\`
}
`
}

function formatConstArray(values: readonly string[]): string {
  if (values.length === 0) return "[] as const"
  return `[\n${values.map((value) => `  ${quote(value)},`).join("\n")}\n] as const`
}

function formatRuntimeDeploymentProviders(): string {
  return `{\n${PROVIDER_ROLES.map(
    (role) =>
      `    ${role}: requireGeneratedDeploymentProvider(candidate.providers, ${quote(role)}),`,
  ).join("\n")}\n  }`
}

function quote(value: string | VoyantProjectDeploymentMode | undefined): string {
  return JSON.stringify(value ?? null)
}

function normalizeMigrationSources(
  migrationSources: readonly VoyantDeploymentMigrationSourceArtifact[],
): VoyantDeploymentMigrationSourceArtifact[] {
  return migrationSources.map((source) => {
    assertRelativeArtifactPath(source.schema, `migration source "${source.packageName}" schema`)
    return { packageName: source.packageName, schema: source.schema }
  })
}

function assertRelativeArtifactPath(value: string, label: string): void {
  if (value.startsWith("/") || /^[a-zA-Z]:[\\/]/.test(value)) {
    throw new Error(`${label} must be a relative path, got ${value}`)
  }
  if (value.includes("\\")) {
    throw new Error(`${label} must use POSIX separators, got ${value}`)
  }
}
