// GENERATED by scripts/generate-framework-bom.mjs — do not edit.
// The runtime-module set this framework version pins (the BOM membership).
// Refresh with `node scripts/generate-framework-bom.mjs --emit`.

export const FRAMEWORK_RUNTIME_PACKAGES = [
  "@voyant-travel/action-ledger",
  "@voyant-travel/bookings",
  "@voyant-travel/catalog",
  "@voyant-travel/commerce",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/legal",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator-settings",
  "@voyant-travel/quotes",
  "@voyant-travel/relationships",
  "@voyant-travel/storefront",
  "@voyant-travel/trips",
] as const

export type FrameworkRuntimePackage = (typeof FRAMEWORK_RUNTIME_PACKAGES)[number]
