// GENERATED by voyant admin generate — do not edit.
// Recreate from the selected deployment graph:
//   voyant admin generate --graph deployment-graph.generated.json

import { createBookingsAdminExtension } from "@voyant-travel/bookings-react/admin"
import { createCatalogAdminExtension } from "@voyant-travel/catalog-react/admin"
import { createInventoryAdminExtension } from "@voyant-travel/inventory-react/admin"

/**
 * Admin extension factories keyed by module domain. Factories, not
 * instances — hosts call each with localized labels/icons before
 * registering the result.
 */
export const generatedAdminExtensionFactories = {
  bookings: createBookingsAdminExtension,
  catalog: createCatalogAdminExtension,
  inventory: createInventoryAdminExtension,
} as const
