// GENERATED by voyant admin generate --destinations — do not edit.
// Generated destination resolvers (packaged-admin RFC §4.7 endgame): every
// route contribution that declares a `destination:` annotation becomes a
// pure path-interpolation resolver here. The host's resolver map spreads
// this object FIRST and hand-writes only the genuinely custom resolvers
// (search-param construction, multi-route targets):
//   { ...generatedAdminDestinations, ...custom } satisfies AdminDestinationResolvers
// To eject the whole map, delete this header — the generator skips files
// without it. To override one key, re-declare it after the spread in the
// host map (later properties win); to unbind one, remove the
// contribution's `destination:` annotation and regenerate.
import type { AdminDestinationResolvers } from "@voyant-travel/admin"
// Type-only: bind the mounted admin entries' `AdminDestinations`
// augmentations into this module without pulling any runtime code into
// the chunk that imports the resolver map.
import type {} from "@voyant-travel/action-ledger-react/admin"
import type {} from "@voyant-travel/bookings-react/admin"
import type {} from "@voyant-travel/catalog-react/admin"
import type {} from "@voyant-travel/commerce-react/admin"
import type {} from "@voyant-travel/distribution-react/admin"
import type {} from "@voyant-travel/finance-react/admin"
import type {} from "@voyant-travel/flights-react/admin"
import type {} from "@voyant-travel/inventory-react/admin"
import type {} from "@voyant-travel/legal-react/admin"
import type {} from "@voyant-travel/mice-react/admin"
import type {} from "@voyant-travel/notifications-react/admin"
import type {} from "@voyant-travel/operations-react/admin"
import type {} from "@voyant-travel/quotes-react/admin"
import type {} from "@voyant-travel/relationships-react/admin"
import type {} from "@voyant-travel/trips-react/admin"

/** Resolvers for the route-backed subset of the declared destination keys. */
export const generatedAdminDestinations = {
  "availabilitySlot.detail": ({ slotId }) =>
    `/operations/availability/${encodeURIComponent(slotId)}`,
  "availabilitySlot.list": () => "/operations/availability",
  "availabilityStartTime.detail": ({ startTimeId }) =>
    `/operations/availability/start-times/${encodeURIComponent(startTimeId)}`,
  "booking.create": () => "/bookings/new",
  "booking.list": () => "/bookings",
  "contract.detail": ({ contractId }) => `/legal/contracts/${encodeURIComponent(contractId)}`,
  "contract.list": () => "/legal/contracts",
  "contractTemplate.detail": ({ templateId }) =>
    `/legal/templates/${encodeURIComponent(templateId)}`,
  "contractTemplate.list": () => "/legal/templates",
  "flight.orders": () => "/flights/orders",
  "flight.search": () => "/flights",
  "flightOrder.detail": ({ orderId }) => `/flights/orders/${encodeURIComponent(orderId)}`,
  "invoice.detail": ({ invoiceId }) => `/finance/invoices/${encodeURIComponent(invoiceId)}`,
  "invoice.list": () => "/finance/invoices",
  "mice.program.detail": ({ programId }) => `/mice/${encodeURIComponent(programId)}`,
  "mice.program.list": () => "/mice",
  "notificationReminderRule.detail": ({ ruleId }) =>
    `/notifications/reminder-rules/${encodeURIComponent(ruleId)}`,
  "notificationReminderRule.list": () => "/notifications/reminder-rules",
  "notificationTemplate.detail": ({ templateId }) =>
    `/notifications/templates/${encodeURIComponent(templateId)}`,
  "notificationTemplate.list": () => "/notifications/templates",
  "organization.detail": ({ organizationId }) =>
    `/organizations/${encodeURIComponent(organizationId)}`,
  "organization.list": () => "/organizations",
  "payment.detail": ({ paymentId }) => `/finance/payments/${encodeURIComponent(paymentId)}`,
  "payment.list": () => "/finance/payments",
  "person.detail": ({ personId }) => `/people/${encodeURIComponent(personId)}`,
  "person.list": () => "/people",
  "policy.detail": ({ policyId }) => `/legal/policies/${encodeURIComponent(policyId)}`,
  "policy.list": () => "/legal/policies",
  "product.detail": ({ productId }) => `/products/${encodeURIComponent(productId)}`,
  "product.list": () => "/products",
  "productCategory.list": () => "/products/categories",
  "quote.detail": ({ quoteId }) => `/quotes/${encodeURIComponent(quoteId)}`,
  "quote.list": () => "/quotes",
  "resource.detail": ({ resourceId }) => `/operations/resources/${encodeURIComponent(resourceId)}`,
  "resource.list": () => "/operations/resources",
  "resourceAllocation.detail": ({ allocationId }) =>
    `/operations/resources/allocations/${encodeURIComponent(allocationId)}`,
  "resourceAssignment.detail": ({ assignmentId }) =>
    `/operations/resources/assignments/${encodeURIComponent(assignmentId)}`,
  "resourcePool.detail": ({ poolId }) =>
    `/operations/resources/pools/${encodeURIComponent(poolId)}`,
  "supplier.detail": ({ supplierId }) => `/suppliers/${encodeURIComponent(supplierId)}`,
  "supplier.list": () => "/suppliers",
  "supplierInvoice.detail": ({ supplierInvoiceId }) =>
    `/finance/supplier-invoices/${encodeURIComponent(supplierInvoiceId)}`,
  "supplierInvoice.list": () => "/finance/supplier-invoices",
  "trip.detail": ({ tripId }) => `/trips/${encodeURIComponent(tripId)}`,
  "trip.list": () => "/trips",
} satisfies Partial<AdminDestinationResolvers>
