// GENERATED by pnpm --filter operator graph:emit - do not edit.
// Package runtime bodies remain behind lazy imports selected by the resolved graph.

import {
  createVoyantGraphRuntime,
  type VoyantGraphRuntime,
} from "@voyant-travel/framework/deployment-artifacts"

export const GENERATED_GRAPH_RUNTIME_HASH = "sha256:1fd8231cb66f4a892a8af62d26ef3c46b49690658b7c4c2dd2d84868074d25b0" as const
export const GENERATED_GRAPH_RUNTIME_ENTRY_SPECIFIERS = [
  "@voyant-travel/accommodations",
  "@voyant-travel/accommodations/routes-content",
  "@voyant-travel/action-ledger",
  "@voyant-travel/action-ledger/health",
  "@voyant-travel/bookings",
  "@voyant-travel/bookings/extensions/suppliers",
  "@voyant-travel/bookings/requirements",
  "@voyant-travel/catalog",
  "@voyant-travel/catalog/booking-engine",
  "@voyant-travel/catalog/offers",
  "@voyant-travel/charters",
  "@voyant-travel/commerce",
  "@voyant-travel/commerce/checkout",
  "@voyant-travel/cruises",
  "@voyant-travel/cruises/routes-content",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights/hono",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/inventory/authoring/extension",
  "@voyant-travel/inventory/booking-extension",
  "@voyant-travel/inventory/extras",
  "@voyant-travel/inventory/routes-brochure",
  "@voyant-travel/inventory/routes-content",
  "@voyant-travel/legal",
  "@voyant-travel/legal/contract-document-routes",
  "@voyant-travel/mice",
  "@voyant-travel/mice/booking-extension",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator-settings/hono-module",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/quotes",
  "@voyant-travel/quotes/booking-extension",
  "@voyant-travel/realtime",
  "@voyant-travel/relationships",
  "@voyant-travel/storage/routes",
  "@voyant-travel/storefront",
  "@voyant-travel/storefront/payment-link",
  "@voyant-travel/trips",
  "@voyant-travel/workflow-runs/hono-module",
] as const
export const GENERATED_GRAPH_RUNTIME_MODULE_IDS = [
  "@voyant-travel/accommodations",
  "@voyant-travel/action-ledger",
  "@voyant-travel/availability",
  "@voyant-travel/bookings",
  "@voyant-travel/bookings#requirements",
  "@voyant-travel/catalog",
  "@voyant-travel/catalog-authoring",
  "@voyant-travel/catalog#booking-engine",
  "@voyant-travel/charters",
  "@voyant-travel/commerce",
  "@voyant-travel/cruises",
  "@voyant-travel/db",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/inventory#extras",
  "@voyant-travel/legal",
  "@voyant-travel/legal#contract-document",
  "@voyant-travel/mice",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator-settings",
  "@voyant-travel/operator#invitations",
  "@voyant-travel/operator#mcp",
  "@voyant-travel/operator#team",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/quotes",
  "@voyant-travel/realtime",
  "@voyant-travel/relationships",
  "@voyant-travel/storage",
  "@voyant-travel/storefront",
  "@voyant-travel/storefront#payment-link",
  "@voyant-travel/trips",
  "@voyant-travel/workflow-runs",
] as const
export const GENERATED_GRAPH_RUNTIME_PLUGIN_IDS = [
  "@voyant-travel/accommodations#content-extension",
  "@voyant-travel/action-ledger#health-extension",
  "@voyant-travel/bookings#booking-supplier-extension",
  "@voyant-travel/catalog#offers-extension",
  "@voyant-travel/commerce#booking-maintenance-extension",
  "@voyant-travel/commerce#catalog-checkout-extension",
  "@voyant-travel/cruises#content-extension",
  "@voyant-travel/distribution#channel-push-extension",
  "@voyant-travel/distribution#extension",
  "@voyant-travel/finance#booking-schedule-extension",
  "@voyant-travel/finance#booking-tax-extension",
  "@voyant-travel/finance#bookings-create-extension",
  "@voyant-travel/inventory#authoring.extension",
  "@voyant-travel/inventory#booking-extension",
  "@voyant-travel/inventory#brochure-extension",
  "@voyant-travel/inventory#content-extension",
  "@voyant-travel/mice#booking-extension",
  "@voyant-travel/plugin-netopia",
  "@voyant-travel/quotes#booking-extension",
  "@voyant-travel/quotes#proposal-extension",
  "@voyant-travel/quotes#quote-version-snapshot-extension",
] as const

const GENERATED_GRAPH_RUNTIME_IMPORTERS = {
  "@voyant-travel/accommodations": () => import("@voyant-travel/accommodations"),
  "@voyant-travel/accommodations/routes-content": () => import("@voyant-travel/accommodations/routes-content"),
  "@voyant-travel/action-ledger": () => import("@voyant-travel/action-ledger"),
  "@voyant-travel/action-ledger/health": () => import("@voyant-travel/action-ledger/health"),
  "@voyant-travel/bookings": () => import("@voyant-travel/bookings"),
  "@voyant-travel/bookings/extensions/suppliers": () => import("@voyant-travel/bookings/extensions/suppliers"),
  "@voyant-travel/bookings/requirements": () => import("@voyant-travel/bookings/requirements"),
  "@voyant-travel/catalog": () => import("@voyant-travel/catalog"),
  "@voyant-travel/catalog/booking-engine": () => import("@voyant-travel/catalog/booking-engine"),
  "@voyant-travel/catalog/offers": () => import("@voyant-travel/catalog/offers"),
  "@voyant-travel/charters": () => import("@voyant-travel/charters"),
  "@voyant-travel/commerce": () => import("@voyant-travel/commerce"),
  "@voyant-travel/commerce/checkout": () => import("@voyant-travel/commerce/checkout"),
  "@voyant-travel/cruises": () => import("@voyant-travel/cruises"),
  "@voyant-travel/cruises/routes-content": () => import("@voyant-travel/cruises/routes-content"),
  "@voyant-travel/distribution": () => import("@voyant-travel/distribution"),
  "@voyant-travel/finance": () => import("@voyant-travel/finance"),
  "@voyant-travel/flights/hono": () => import("@voyant-travel/flights/hono"),
  "@voyant-travel/identity": () => import("@voyant-travel/identity"),
  "@voyant-travel/inventory": () => import("@voyant-travel/inventory"),
  "@voyant-travel/inventory/authoring/extension": () => import("@voyant-travel/inventory/authoring/extension"),
  "@voyant-travel/inventory/booking-extension": () => import("@voyant-travel/inventory/booking-extension"),
  "@voyant-travel/inventory/extras": () => import("@voyant-travel/inventory/extras"),
  "@voyant-travel/inventory/routes-brochure": () => import("@voyant-travel/inventory/routes-brochure"),
  "@voyant-travel/inventory/routes-content": () => import("@voyant-travel/inventory/routes-content"),
  "@voyant-travel/legal": () => import("@voyant-travel/legal"),
  "@voyant-travel/legal/contract-document-routes": () => import("@voyant-travel/legal/contract-document-routes"),
  "@voyant-travel/mice": () => import("@voyant-travel/mice"),
  "@voyant-travel/mice/booking-extension": () => import("@voyant-travel/mice/booking-extension"),
  "@voyant-travel/notifications": () => import("@voyant-travel/notifications"),
  "@voyant-travel/operations": () => import("@voyant-travel/operations"),
  "@voyant-travel/operator-settings/hono-module": () => import("@voyant-travel/operator-settings/hono-module"),
  "@voyant-travel/public-document-delivery": () => import("@voyant-travel/public-document-delivery"),
  "@voyant-travel/quotes": () => import("@voyant-travel/quotes"),
  "@voyant-travel/quotes/booking-extension": () => import("@voyant-travel/quotes/booking-extension"),
  "@voyant-travel/realtime": () => import("@voyant-travel/realtime"),
  "@voyant-travel/relationships": () => import("@voyant-travel/relationships"),
  "@voyant-travel/storage/routes": () => import("@voyant-travel/storage/routes"),
  "@voyant-travel/storefront": () => import("@voyant-travel/storefront"),
  "@voyant-travel/storefront/payment-link": () => import("@voyant-travel/storefront/payment-link"),
  "@voyant-travel/trips": () => import("@voyant-travel/trips"),
  "@voyant-travel/workflow-runs/hono-module": () => import("@voyant-travel/workflow-runs/hono-module"),
} satisfies Readonly<Record<string, () => Promise<unknown>>>

export function createGeneratedGraphRuntime(): VoyantGraphRuntime {
  return createVoyantGraphRuntime({
    graphHash: GENERATED_GRAPH_RUNTIME_HASH,
    entries: GENERATED_GRAPH_RUNTIME_IMPORTERS,
    modules: [
      {
        "id": "@voyant-travel/accommodations",
        "kind": "module",
        "order": 0,
        "packageName": "@voyant-travel/accommodations",
        "routes": [
          {
            "importEntry": "@voyant-travel/accommodations",
            "route": {
              "id": "@voyant-travel/accommodations#api",
              "mount": "accommodations",
              "runtime": {
                "entry": "@voyant-travel/accommodations",
                "export": "accommodationsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/action-ledger",
        "kind": "module",
        "order": 1,
        "packageName": "@voyant-travel/action-ledger",
        "routes": [
          {
            "importEntry": "@voyant-travel/action-ledger",
            "route": {
              "id": "@voyant-travel/action-ledger#api.admin",
              "mount": "action-ledger",
              "runtime": {
                "entry": "@voyant-travel/action-ledger",
                "export": "actionLedgerHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/availability",
        "kind": "module",
        "order": 2,
        "packageName": "@voyant-travel/availability",
        "routes": []
      },
      {
        "id": "@voyant-travel/bookings",
        "kind": "module",
        "order": 3,
        "packageName": "@voyant-travel/bookings",
        "routes": [
          {
            "importEntry": "@voyant-travel/bookings",
            "route": {
              "id": "@voyant-travel/bookings#api.admin",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/bookings",
                "export": "createBookingsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/bookings",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/bookings#api.public",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/bookings",
                "export": "createBookingsHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/bookings#requirements",
        "kind": "module",
        "order": 4,
        "packageName": "@voyant-travel/bookings",
        "routes": [
          {
            "importEntry": "@voyant-travel/bookings/requirements",
            "route": {
              "id": "@voyant-travel/bookings#requirements.api",
              "mount": "booking-requirements",
              "runtime": {
                "entry": "@voyant-travel/bookings/requirements",
                "export": "createBookingRequirementsHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/bookings/requirements",
            "route": {
              "id": "@voyant-travel/bookings#requirements.api.public",
              "mount": "booking-requirements",
              "runtime": {
                "entry": "@voyant-travel/bookings/requirements",
                "export": "createBookingRequirementsHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/catalog",
        "kind": "module",
        "order": 5,
        "packageName": "@voyant-travel/catalog",
        "routes": [
          {
            "importEntry": "@voyant-travel/catalog",
            "route": {
              "id": "@voyant-travel/catalog#api.admin",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/catalog",
                "export": "createCatalogSearchHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/catalog",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/catalog#api.public",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/catalog",
                "export": "createCatalogSearchHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/catalog-authoring",
        "kind": "module",
        "order": 6,
        "packageName": "@voyant-travel/catalog-authoring",
        "routes": []
      },
      {
        "id": "@voyant-travel/catalog#booking-engine",
        "kind": "module",
        "order": 7,
        "packageName": "@voyant-travel/catalog",
        "routes": [
          {
            "importEntry": "@voyant-travel/catalog/booking-engine",
            "route": {
              "id": "@voyant-travel/catalog#booking-engine.api.admin",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/catalog/booking-engine",
                "export": "createCatalogBookingEngineHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/catalog/booking-engine",
            "route": {
              "id": "@voyant-travel/catalog#booking-engine.api.public",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/catalog/booking-engine",
                "export": "createCatalogBookingEngineHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/charters",
        "kind": "module",
        "order": 8,
        "packageName": "@voyant-travel/charters",
        "routes": [
          {
            "importEntry": "@voyant-travel/charters",
            "route": {
              "id": "@voyant-travel/charters#api.admin",
              "mount": "charters",
              "runtime": {
                "entry": "@voyant-travel/charters",
                "export": "createChartersHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/charters",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/charters#api.public",
              "mount": "charters",
              "runtime": {
                "entry": "@voyant-travel/charters",
                "export": "createChartersHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/commerce",
        "kind": "module",
        "order": 9,
        "packageName": "@voyant-travel/commerce",
        "routes": [
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "id": "@voyant-travel/commerce#api.markets.admin",
              "mount": "markets",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "marketsHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/commerce#api.markets.public",
              "mount": "markets",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "marketsHonoModule"
              },
              "surface": "public"
            }
          },
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "id": "@voyant-travel/commerce#api.pricing.admin",
              "mount": "pricing",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "pricingHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "id": "@voyant-travel/commerce#api.pricing.public",
              "mount": "pricing",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "pricingHonoModule"
              },
              "surface": "public"
            }
          },
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "id": "@voyant-travel/commerce#api.promotions.admin",
              "mount": "promotions",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "promotionsHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/commerce",
            "route": {
              "id": "@voyant-travel/commerce#api.sellability.admin",
              "mount": "sellability",
              "runtime": {
                "entry": "@voyant-travel/commerce",
                "export": "sellabilityHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/cruises",
        "kind": "module",
        "order": 10,
        "packageName": "@voyant-travel/cruises",
        "routes": [
          {
            "importEntry": "@voyant-travel/cruises",
            "route": {
              "id": "@voyant-travel/cruises#api.admin",
              "mount": "cruises",
              "runtime": {
                "entry": "@voyant-travel/cruises",
                "export": "createCruisesHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/cruises",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/cruises#api.public",
              "mount": "cruises",
              "runtime": {
                "entry": "@voyant-travel/cruises",
                "export": "createCruisesHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/db",
        "kind": "module",
        "order": 11,
        "packageName": "@voyant-travel/db",
        "routes": []
      },
      {
        "id": "@voyant-travel/distribution",
        "kind": "module",
        "order": 12,
        "packageName": "@voyant-travel/distribution",
        "routes": [
          {
            "importEntry": "@voyant-travel/distribution",
            "route": {
              "id": "@voyant-travel/distribution#api",
              "mount": "distribution",
              "runtime": {
                "entry": "@voyant-travel/distribution",
                "export": "distributionHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/distribution",
            "route": {
              "id": "@voyant-travel/distribution#api.external-refs",
              "mount": "external-refs",
              "runtime": {
                "entry": "@voyant-travel/distribution",
                "export": "externalRefsHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/distribution",
            "route": {
              "id": "@voyant-travel/distribution#api.suppliers",
              "mount": "suppliers",
              "runtime": {
                "entry": "@voyant-travel/distribution",
                "export": "suppliersHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/finance",
        "kind": "module",
        "order": 13,
        "packageName": "@voyant-travel/finance",
        "routes": [
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "id": "@voyant-travel/finance#api.admin",
              "mount": "finance",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "createFinanceHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "anonymous": [
                "/bookings",
                "/collections",
                "/payment-sessions",
                "/accountant",
                "/vouchers"
              ],
              "id": "@voyant-travel/finance#api.public",
              "mount": "finance",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "createFinanceHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/flights",
        "kind": "module",
        "order": 14,
        "packageName": "@voyant-travel/flights",
        "routes": [
          {
            "importEntry": "@voyant-travel/flights/hono",
            "route": {
              "id": "@voyant-travel/flights#api",
              "mount": "flights",
              "runtime": {
                "entry": "@voyant-travel/flights/hono",
                "export": "createFlightsHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/identity",
        "kind": "module",
        "order": 15,
        "packageName": "@voyant-travel/identity",
        "routes": [
          {
            "importEntry": "@voyant-travel/identity",
            "route": {
              "id": "@voyant-travel/identity#api.admin",
              "mount": "identity",
              "runtime": {
                "entry": "@voyant-travel/identity",
                "export": "identityHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory",
        "kind": "module",
        "order": 16,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory",
            "route": {
              "id": "@voyant-travel/inventory#api.admin",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory",
                "export": "inventoryHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/inventory",
            "route": {
              "id": "@voyant-travel/inventory#api.public",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory",
                "export": "inventoryHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory#extras",
        "kind": "module",
        "order": 17,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory/extras",
            "route": {
              "id": "@voyant-travel/inventory#extras.api",
              "mount": "extras",
              "runtime": {
                "entry": "@voyant-travel/inventory/extras",
                "export": "inventoryExtrasHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/legal",
        "kind": "module",
        "order": 18,
        "packageName": "@voyant-travel/legal",
        "routes": [
          {
            "importEntry": "@voyant-travel/legal",
            "route": {
              "id": "@voyant-travel/legal#api.admin",
              "mount": "legal",
              "runtime": {
                "entry": "@voyant-travel/legal",
                "export": "createLegalHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/legal",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/legal#api.public",
              "mount": "legal",
              "runtime": {
                "entry": "@voyant-travel/legal",
                "export": "createLegalHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/legal#contract-document",
        "kind": "module",
        "order": 19,
        "packageName": "@voyant-travel/legal",
        "routes": [
          {
            "importEntry": "@voyant-travel/legal/contract-document-routes",
            "route": {
              "id": "@voyant-travel/legal#contract-document.api",
              "runtime": {
                "entry": "@voyant-travel/legal/contract-document-routes",
                "export": "createContractDocumentHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/mice",
        "kind": "module",
        "order": 20,
        "packageName": "@voyant-travel/mice",
        "routes": [
          {
            "importEntry": "@voyant-travel/mice",
            "route": {
              "id": "@voyant-travel/mice#api.admin",
              "mount": "mice",
              "runtime": {
                "entry": "@voyant-travel/mice",
                "export": "createMiceHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/notifications",
        "kind": "module",
        "order": 21,
        "packageName": "@voyant-travel/notifications",
        "routes": [
          {
            "importEntry": "@voyant-travel/notifications",
            "route": {
              "id": "@voyant-travel/notifications#api.admin",
              "mount": "notifications",
              "runtime": {
                "entry": "@voyant-travel/notifications",
                "export": "createNotificationsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/operations",
        "kind": "module",
        "order": 22,
        "packageName": "@voyant-travel/operations",
        "routes": [
          {
            "importEntry": "@voyant-travel/operations",
            "route": {
              "id": "@voyant-travel/operations#api.admin",
              "mount": "operations",
              "runtime": {
                "entry": "@voyant-travel/operations",
                "export": "operationsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/operator-settings",
        "kind": "module",
        "order": 23,
        "packageName": "@voyant-travel/operator-settings",
        "routes": [
          {
            "importEntry": "@voyant-travel/operator-settings/hono-module",
            "route": {
              "id": "@voyant-travel/operator-settings#api.admin",
              "mount": "settings",
              "runtime": {
                "entry": "@voyant-travel/operator-settings/hono-module",
                "export": "createOperatorSettingsHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/operator-settings/hono-module",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/operator-settings#api.public.operator-profile",
              "mount": "operator-profile",
              "runtime": {
                "entry": "@voyant-travel/operator-settings/hono-module",
                "export": "createOperatorSettingsHonoModule"
              },
              "surface": "public"
            }
          },
          {
            "importEntry": "@voyant-travel/operator-settings/hono-module",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/operator-settings#api.public.settings",
              "mount": "settings/operator",
              "runtime": {
                "entry": "@voyant-travel/operator-settings/hono-module",
                "export": "createOperatorSettingsHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/operator#invitations",
        "kind": "module",
        "order": 24,
        "packageName": "@voyant-travel/operator",
        "routes": []
      },
      {
        "id": "@voyant-travel/operator#mcp",
        "kind": "module",
        "order": 25,
        "packageName": "@voyant-travel/operator",
        "routes": []
      },
      {
        "id": "@voyant-travel/operator#team",
        "kind": "module",
        "order": 26,
        "packageName": "@voyant-travel/operator",
        "routes": []
      },
      {
        "id": "@voyant-travel/public-document-delivery",
        "kind": "module",
        "order": 27,
        "packageName": "@voyant-travel/public-document-delivery",
        "routes": [
          {
            "importEntry": "@voyant-travel/public-document-delivery",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/public-document-delivery#api.public",
              "mount": "documents",
              "runtime": {
                "entry": "@voyant-travel/public-document-delivery",
                "export": "createPublicDocumentDeliveryHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/quotes",
        "kind": "module",
        "order": 28,
        "packageName": "@voyant-travel/quotes",
        "routes": [
          {
            "importEntry": "@voyant-travel/quotes",
            "route": {
              "id": "@voyant-travel/quotes#api",
              "mount": "quotes",
              "runtime": {
                "entry": "@voyant-travel/quotes",
                "export": "createQuotesHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/realtime",
        "kind": "module",
        "order": 29,
        "packageName": "@voyant-travel/realtime",
        "routes": [
          {
            "importEntry": "@voyant-travel/realtime",
            "route": {
              "id": "@voyant-travel/realtime#api.admin",
              "mount": "realtime",
              "runtime": {
                "entry": "@voyant-travel/realtime",
                "export": "createRealtimeHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/realtime",
            "route": {
              "id": "@voyant-travel/realtime#api.public",
              "mount": "realtime",
              "runtime": {
                "entry": "@voyant-travel/realtime",
                "export": "createRealtimeHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/relationships",
        "kind": "module",
        "order": 30,
        "packageName": "@voyant-travel/relationships",
        "routes": [
          {
            "importEntry": "@voyant-travel/relationships",
            "route": {
              "id": "@voyant-travel/relationships#api.admin",
              "mount": "relationships",
              "runtime": {
                "entry": "@voyant-travel/relationships",
                "export": "createRelationshipsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/storage",
        "kind": "module",
        "order": 31,
        "packageName": "@voyant-travel/storage",
        "routes": [
          {
            "importEntry": "@voyant-travel/storage/routes",
            "route": {
              "id": "@voyant-travel/storage#api.admin.media",
              "mount": "media",
              "runtime": {
                "entry": "@voyant-travel/storage/routes",
                "export": "createMediaHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/storage/routes",
            "route": {
              "id": "@voyant-travel/storage#api.admin.uploads",
              "mount": "uploads",
              "runtime": {
                "entry": "@voyant-travel/storage/routes",
                "export": "createMediaHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/storage/routes",
            "route": {
              "id": "@voyant-travel/storage#api.admin.video-upload-ticket",
              "mount": "uploads/video",
              "runtime": {
                "entry": "@voyant-travel/storage/routes",
                "export": "createMediaHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/storefront",
        "kind": "module",
        "order": 32,
        "packageName": "@voyant-travel/storefront",
        "routes": [
          {
            "importEntry": "@voyant-travel/storefront",
            "route": {
              "id": "@voyant-travel/storefront#api.admin",
              "mount": "storefront",
              "runtime": {
                "entry": "@voyant-travel/storefront",
                "export": "createStorefrontHonoModule"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/storefront",
            "route": {
              "anonymous": [
                "/leads",
                "/newsletter",
                "/offers"
              ],
              "id": "@voyant-travel/storefront#api.public",
              "mount": "/",
              "runtime": {
                "entry": "@voyant-travel/storefront",
                "export": "createStorefrontHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/storefront#payment-link",
        "kind": "module",
        "order": 33,
        "packageName": "@voyant-travel/storefront",
        "routes": [
          {
            "importEntry": "@voyant-travel/storefront/payment-link",
            "route": {
              "anonymous": [
                "payment-link-config",
                "payment-link"
              ],
              "id": "@voyant-travel/storefront#payment-link.api",
              "runtime": {
                "entry": "@voyant-travel/storefront/payment-link",
                "export": "createPaymentLinkHonoModule"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/trips",
        "kind": "module",
        "order": 34,
        "packageName": "@voyant-travel/trips",
        "routes": [
          {
            "importEntry": "@voyant-travel/trips",
            "route": {
              "id": "@voyant-travel/trips#api.admin",
              "mount": "trips",
              "runtime": {
                "entry": "@voyant-travel/trips",
                "export": "createTripsHonoModule"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/trips",
            "route": {
              "id": "@voyant-travel/trips#api.public",
              "mount": "trips",
              "runtime": {
                "entry": "@voyant-travel/trips",
                "export": "createTripsHonoModule"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/workflow-runs",
        "kind": "module",
        "order": 35,
        "packageName": "@voyant-travel/workflow-runs",
        "routes": [
          {
            "importEntry": "@voyant-travel/workflow-runs/hono-module",
            "route": {
              "id": "@voyant-travel/workflow-runs#api.admin",
              "mount": "workflow-runs",
              "runtime": {
                "entry": "@voyant-travel/workflow-runs/hono-module",
                "export": "createWorkflowRunsHonoModule"
              },
              "surface": "admin"
            }
          }
        ]
      }
    ],
    plugins: [
      {
        "id": "@voyant-travel/accommodations#content-extension",
        "kind": "plugin",
        "order": 0,
        "packageName": "@voyant-travel/accommodations",
        "routes": [
          {
            "importEntry": "@voyant-travel/accommodations/routes-content",
            "route": {
              "id": "@voyant-travel/accommodations#content-extension.api.admin",
              "mount": "accommodations",
              "runtime": {
                "entry": "@voyant-travel/accommodations/routes-content",
                "export": "createAccommodationContentHonoExtension"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/accommodations/routes-content",
            "route": {
              "id": "@voyant-travel/accommodations#content-extension.api.public",
              "mount": "accommodations",
              "runtime": {
                "entry": "@voyant-travel/accommodations/routes-content",
                "export": "createAccommodationContentHonoExtension"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/action-ledger#health-extension",
        "kind": "plugin",
        "order": 1,
        "packageName": "@voyant-travel/action-ledger",
        "routes": [
          {
            "importEntry": "@voyant-travel/action-ledger/health",
            "route": {
              "id": "@voyant-travel/action-ledger#health-extension.api",
              "mount": "action-ledger",
              "runtime": {
                "entry": "@voyant-travel/action-ledger/health",
                "export": "createActionLedgerHealthHonoExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/bookings#booking-supplier-extension",
        "kind": "plugin",
        "order": 2,
        "packageName": "@voyant-travel/bookings",
        "routes": [
          {
            "importEntry": "@voyant-travel/bookings/extensions/suppliers",
            "route": {
              "id": "@voyant-travel/bookings#booking-supplier-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/bookings/extensions/suppliers",
                "export": "bookingsSupplierExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/catalog#offers-extension",
        "kind": "plugin",
        "order": 3,
        "packageName": "@voyant-travel/catalog",
        "routes": [
          {
            "importEntry": "@voyant-travel/catalog/offers",
            "route": {
              "id": "@voyant-travel/catalog#offers-extension.api",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/catalog/offers",
                "export": "createCatalogOffersHonoExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/commerce#booking-maintenance-extension",
        "kind": "plugin",
        "order": 4,
        "packageName": "@voyant-travel/commerce",
        "routes": [
          {
            "importEntry": "@voyant-travel/commerce/checkout",
            "route": {
              "id": "@voyant-travel/commerce#booking-maintenance-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/commerce/checkout",
                "export": "createBookingMaintenanceHonoExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/commerce#catalog-checkout-extension",
        "kind": "plugin",
        "order": 5,
        "packageName": "@voyant-travel/commerce",
        "routes": [
          {
            "importEntry": "@voyant-travel/commerce/checkout",
            "route": {
              "id": "@voyant-travel/commerce#catalog-checkout-extension.api",
              "mount": "catalog",
              "runtime": {
                "entry": "@voyant-travel/commerce/checkout",
                "export": "createCatalogCheckoutHonoExtension"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/cruises#content-extension",
        "kind": "plugin",
        "order": 6,
        "packageName": "@voyant-travel/cruises",
        "routes": [
          {
            "importEntry": "@voyant-travel/cruises/routes-content",
            "route": {
              "id": "@voyant-travel/cruises#content-extension.api.admin",
              "mount": "cruises",
              "runtime": {
                "entry": "@voyant-travel/cruises/routes-content",
                "export": "createCruiseContentHonoExtension"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/cruises/routes-content",
            "route": {
              "id": "@voyant-travel/cruises#content-extension.api.public",
              "mount": "cruises",
              "runtime": {
                "entry": "@voyant-travel/cruises/routes-content",
                "export": "createCruiseContentHonoExtension"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/distribution#channel-push-extension",
        "kind": "plugin",
        "order": 7,
        "packageName": "@voyant-travel/distribution",
        "routes": [
          {
            "importEntry": "@voyant-travel/distribution",
            "route": {
              "id": "@voyant-travel/distribution#channel-push-extension.api",
              "mount": "distribution",
              "runtime": {
                "entry": "@voyant-travel/distribution",
                "export": "createChannelPushExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/distribution#extension",
        "kind": "plugin",
        "order": 8,
        "packageName": "@voyant-travel/distribution",
        "routes": [
          {
            "importEntry": "@voyant-travel/distribution",
            "route": {
              "id": "@voyant-travel/distribution#extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/distribution",
                "export": "distributionBookingExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/finance#booking-schedule-extension",
        "kind": "plugin",
        "order": 9,
        "packageName": "@voyant-travel/finance",
        "routes": [
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "id": "@voyant-travel/finance#booking-schedule-extension.api.admin",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "createBookingScheduleHonoExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/finance#booking-schedule-extension.api.public",
              "mount": "payment-policy",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "createBookingScheduleHonoExtension"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/finance#booking-tax-extension",
        "kind": "plugin",
        "order": 10,
        "packageName": "@voyant-travel/finance",
        "routes": [
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "id": "@voyant-travel/finance#booking-tax-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "createBookingTaxHonoExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/finance#bookings-create-extension",
        "kind": "plugin",
        "order": 11,
        "packageName": "@voyant-travel/finance",
        "routes": [
          {
            "importEntry": "@voyant-travel/finance",
            "route": {
              "id": "@voyant-travel/finance#bookings-create-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/finance",
                "export": "bookingsCreateExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory#authoring.extension",
        "kind": "plugin",
        "order": 12,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory/authoring/extension",
            "route": {
              "id": "@voyant-travel/inventory#authoring.extension.api",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory/authoring/extension",
                "export": "inventoryAuthoringExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory#booking-extension",
        "kind": "plugin",
        "order": 13,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory/booking-extension",
            "route": {
              "id": "@voyant-travel/inventory#booking-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/inventory/booking-extension",
                "export": "productsBookingExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory#brochure-extension",
        "kind": "plugin",
        "order": 14,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory/routes-brochure",
            "route": {
              "id": "@voyant-travel/inventory#brochure-extension.api.admin",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory/routes-brochure",
                "export": "createProductBrochureHonoExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/inventory#content-extension",
        "kind": "plugin",
        "order": 15,
        "packageName": "@voyant-travel/inventory",
        "routes": [
          {
            "importEntry": "@voyant-travel/inventory/routes-content",
            "route": {
              "id": "@voyant-travel/inventory#content-extension.api.admin",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory/routes-content",
                "export": "createProductContentHonoExtension"
              },
              "surface": "admin"
            }
          },
          {
            "importEntry": "@voyant-travel/inventory/routes-content",
            "route": {
              "id": "@voyant-travel/inventory#content-extension.api.public",
              "mount": "products",
              "runtime": {
                "entry": "@voyant-travel/inventory/routes-content",
                "export": "createProductContentHonoExtension"
              },
              "surface": "public"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/mice#booking-extension",
        "kind": "plugin",
        "order": 16,
        "packageName": "@voyant-travel/mice",
        "routes": [
          {
            "importEntry": "@voyant-travel/mice/booking-extension",
            "route": {
              "id": "@voyant-travel/mice#booking-extension.api.admin",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/mice/booking-extension",
                "export": "miceBookingExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/plugin-netopia",
        "kind": "plugin",
        "order": 17,
        "packageName": "@voyant-travel/plugin-netopia",
        "routes": []
      },
      {
        "id": "@voyant-travel/quotes#booking-extension",
        "kind": "plugin",
        "order": 18,
        "packageName": "@voyant-travel/quotes",
        "routes": [
          {
            "importEntry": "@voyant-travel/quotes/booking-extension",
            "route": {
              "id": "@voyant-travel/quotes#booking-extension.api",
              "mount": "bookings",
              "runtime": {
                "entry": "@voyant-travel/quotes/booking-extension",
                "export": "quotesBookingExtension"
              },
              "surface": "admin"
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/quotes#proposal-extension",
        "kind": "plugin",
        "order": 19,
        "packageName": "@voyant-travel/quotes",
        "routes": [
          {
            "importEntry": "@voyant-travel/quotes",
            "route": {
              "id": "@voyant-travel/quotes#proposal-extension.api.admin",
              "mount": "quote-versions",
              "runtime": {
                "entry": "@voyant-travel/quotes",
                "export": "createQuoteProposalHonoExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          },
          {
            "importEntry": "@voyant-travel/quotes",
            "route": {
              "anonymous": true,
              "id": "@voyant-travel/quotes#proposal-extension.api.public",
              "mount": "proposals",
              "runtime": {
                "entry": "@voyant-travel/quotes",
                "export": "createQuoteProposalHonoExtension"
              },
              "surface": "public",
              "transactional": true
            }
          }
        ]
      },
      {
        "id": "@voyant-travel/quotes#quote-version-snapshot-extension",
        "kind": "plugin",
        "order": 20,
        "packageName": "@voyant-travel/quotes",
        "routes": [
          {
            "importEntry": "@voyant-travel/quotes",
            "route": {
              "id": "@voyant-travel/quotes#quote-version-snapshot-extension.api",
              "mount": "trips",
              "runtime": {
                "entry": "@voyant-travel/quotes",
                "export": "createQuoteVersionSnapshotHonoExtension"
              },
              "surface": "admin",
              "transactional": true
            }
          }
        ]
      }
    ],
  })
}
