/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRouteImport } from './routes/pay'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as storefrontRouteRouteImport } from './routes/(storefront)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as ProposalQuoteVersionIdRouteImport } from './routes/proposal.$quoteVersionId'
import { Route as PaySessionIdRouteImport } from './routes/pay_.$sessionId'
import { Route as AccountantTokenRouteImport } from './routes/accountant.$token'
import { Route as storefrontShopRouteImport } from './routes/(storefront)/shop'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as storefrontShopComposerRouteImport } from './routes/(storefront)/shop_.composer'
import { Route as storefrontShopAccountRouteImport } from './routes/(storefront)/shop_.account'
import { Route as storefrontShopConfirmationBookingIdRouteImport } from './routes/(storefront)/shop_.confirmation.$bookingId'
import { Route as storefrontShopAccountVerifyEmailRouteImport } from './routes/(storefront)/shop_.account.verify-email'
import { Route as storefrontShopAccountSignUpRouteImport } from './routes/(storefront)/shop_.account.sign-up'
import { Route as storefrontShopAccountSignInRouteImport } from './routes/(storefront)/shop_.account.sign-in'
import { Route as storefrontShopProductsEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.products.$entityModule.$entityId'
import { Route as storefrontShopBookEntityModuleEntityIdRouteImport } from './routes/(storefront)/shop_.book.$entityModule.$entityId'

const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontRouteRoute = storefrontRouteRouteImport.update({
  id: '/(storefront)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalQuoteVersionIdRoute = ProposalQuoteVersionIdRouteImport.update({
  id: '/proposal/$quoteVersionId',
  path: '/proposal/$quoteVersionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySessionIdRoute = PaySessionIdRouteImport.update({
  id: '/pay_/$sessionId',
  path: '/pay/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantTokenRoute = AccountantTokenRouteImport.update({
  id: '/accountant/$token',
  path: '/accountant/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontShopRoute = storefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const storefrontShopComposerRoute = storefrontShopComposerRouteImport.update({
  id: '/shop_/composer',
  path: '/shop/composer',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const storefrontShopAccountRoute = storefrontShopAccountRouteImport.update({
  id: '/shop_/account',
  path: '/shop/account',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const storefrontShopConfirmationBookingIdRoute =
  storefrontShopConfirmationBookingIdRouteImport.update({
    id: '/shop_/confirmation/$bookingId',
    path: '/shop/confirmation/$bookingId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const storefrontShopAccountVerifyEmailRoute =
  storefrontShopAccountVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => storefrontShopAccountRoute,
  } as any)
const storefrontShopAccountSignUpRoute =
  storefrontShopAccountSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => storefrontShopAccountRoute,
  } as any)
const storefrontShopAccountSignInRoute =
  storefrontShopAccountSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => storefrontShopAccountRoute,
  } as any)
const storefrontShopProductsEntityModuleEntityIdRoute =
  storefrontShopProductsEntityModuleEntityIdRouteImport.update({
    id: '/shop_/products/$entityModule/$entityId',
    path: '/shop/products/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)
const storefrontShopBookEntityModuleEntityIdRoute =
  storefrontShopBookEntityModuleEntityIdRouteImport.update({
    id: '/shop_/book/$entityModule/$entityId',
    path: '/shop/book/$entityModule/$entityId',
    getParentRoute: () => storefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceRouteRoute
  '/docs': typeof DocsRoute
  '/pay': typeof PayRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/shop/account': typeof storefrontShopAccountRouteWithChildren
  '/shop/composer': typeof storefrontShopComposerRoute
  '/shop/account/sign-in': typeof storefrontShopAccountSignInRoute
  '/shop/account/sign-up': typeof storefrontShopAccountSignUpRoute
  '/shop/account/verify-email': typeof storefrontShopAccountVerifyEmailRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceRouteRoute
  '/docs': typeof DocsRoute
  '/pay': typeof PayRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/shop': typeof storefrontShopRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/shop/account': typeof storefrontShopAccountRouteWithChildren
  '/shop/composer': typeof storefrontShopComposerRoute
  '/shop/account/sign-in': typeof storefrontShopAccountSignInRoute
  '/shop/account/sign-up': typeof storefrontShopAccountSignUpRoute
  '/shop/account/verify-email': typeof storefrontShopAccountVerifyEmailRoute
  '/shop/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/shop/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/shop/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(storefront)': typeof storefrontRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRoute
  '/docs': typeof DocsRoute
  '/pay': typeof PayRoute
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(storefront)/shop': typeof storefrontShopRoute
  '/accountant/$token': typeof AccountantTokenRoute
  '/pay_/$sessionId': typeof PaySessionIdRoute
  '/proposal/$quoteVersionId': typeof ProposalQuoteVersionIdRoute
  '/(storefront)/shop_/account': typeof storefrontShopAccountRouteWithChildren
  '/(storefront)/shop_/composer': typeof storefrontShopComposerRoute
  '/(storefront)/shop_/account/sign-in': typeof storefrontShopAccountSignInRoute
  '/(storefront)/shop_/account/sign-up': typeof storefrontShopAccountSignUpRoute
  '/(storefront)/shop_/account/verify-email': typeof storefrontShopAccountVerifyEmailRoute
  '/(storefront)/shop_/confirmation/$bookingId': typeof storefrontShopConfirmationBookingIdRoute
  '/(storefront)/shop_/book/$entityModule/$entityId': typeof storefrontShopBookEntityModuleEntityIdRoute
  '/(storefront)/shop_/products/$entityModule/$entityId': typeof storefrontShopProductsEntityModuleEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/pay'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/accountant/$token'
    | '/pay/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/shop/account'
    | '/shop/composer'
    | '/shop/account/sign-in'
    | '/shop/account/sign-up'
    | '/shop/account/verify-email'
    | '/shop/confirmation/$bookingId'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/pay'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/shop'
    | '/accountant/$token'
    | '/pay/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/shop/account'
    | '/shop/composer'
    | '/shop/account/sign-in'
    | '/shop/account/sign-up'
    | '/shop/account/verify-email'
    | '/shop/confirmation/$bookingId'
    | '/shop/book/$entityModule/$entityId'
    | '/shop/products/$entityModule/$entityId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(storefront)'
    | '/_workspace'
    | '/docs'
    | '/pay'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(storefront)/shop'
    | '/accountant/$token'
    | '/pay_/$sessionId'
    | '/proposal/$quoteVersionId'
    | '/(storefront)/shop_/account'
    | '/(storefront)/shop_/composer'
    | '/(storefront)/shop_/account/sign-in'
    | '/(storefront)/shop_/account/sign-up'
    | '/(storefront)/shop_/account/verify-email'
    | '/(storefront)/shop_/confirmation/$bookingId'
    | '/(storefront)/shop_/book/$entityModule/$entityId'
    | '/(storefront)/shop_/products/$entityModule/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  storefrontRouteRoute: typeof storefrontRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRoute
  DocsRoute: typeof DocsRoute
  PayRoute: typeof PayRoute
  AccountantTokenRoute: typeof AccountantTokenRoute
  PaySessionIdRoute: typeof PaySessionIdRoute
  ProposalQuoteVersionIdRoute: typeof ProposalQuoteVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)': {
      id: '/(storefront)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$quoteVersionId': {
      id: '/proposal/$quoteVersionId'
      path: '/proposal/$quoteVersionId'
      fullPath: '/proposal/$quoteVersionId'
      preLoaderRoute: typeof ProposalQuoteVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay_/$sessionId': {
      id: '/pay_/$sessionId'
      path: '/pay/$sessionId'
      fullPath: '/pay/$sessionId'
      preLoaderRoute: typeof PaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/$token': {
      id: '/accountant/$token'
      path: '/accountant/$token'
      fullPath: '/accountant/$token'
      preLoaderRoute: typeof AccountantTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)/shop': {
      id: '/(storefront)/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof storefrontShopRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(storefront)/shop_/composer': {
      id: '/(storefront)/shop_/composer'
      path: '/shop/composer'
      fullPath: '/shop/composer'
      preLoaderRoute: typeof storefrontShopComposerRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/account': {
      id: '/(storefront)/shop_/account'
      path: '/shop/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof storefrontShopAccountRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/confirmation/$bookingId': {
      id: '/(storefront)/shop_/confirmation/$bookingId'
      path: '/shop/confirmation/$bookingId'
      fullPath: '/shop/confirmation/$bookingId'
      preLoaderRoute: typeof storefrontShopConfirmationBookingIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/account/verify-email': {
      id: '/(storefront)/shop_/account/verify-email'
      path: '/verify-email'
      fullPath: '/shop/account/verify-email'
      preLoaderRoute: typeof storefrontShopAccountVerifyEmailRouteImport
      parentRoute: typeof storefrontShopAccountRoute
    }
    '/(storefront)/shop_/account/sign-up': {
      id: '/(storefront)/shop_/account/sign-up'
      path: '/sign-up'
      fullPath: '/shop/account/sign-up'
      preLoaderRoute: typeof storefrontShopAccountSignUpRouteImport
      parentRoute: typeof storefrontShopAccountRoute
    }
    '/(storefront)/shop_/account/sign-in': {
      id: '/(storefront)/shop_/account/sign-in'
      path: '/sign-in'
      fullPath: '/shop/account/sign-in'
      preLoaderRoute: typeof storefrontShopAccountSignInRouteImport
      parentRoute: typeof storefrontShopAccountRoute
    }
    '/(storefront)/shop_/products/$entityModule/$entityId': {
      id: '/(storefront)/shop_/products/$entityModule/$entityId'
      path: '/shop/products/$entityModule/$entityId'
      fullPath: '/shop/products/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopProductsEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/shop_/book/$entityModule/$entityId': {
      id: '/(storefront)/shop_/book/$entityModule/$entityId'
      path: '/shop/book/$entityModule/$entityId'
      fullPath: '/shop/book/$entityModule/$entityId'
      preLoaderRoute: typeof storefrontShopBookEntityModuleEntityIdRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface storefrontShopAccountRouteChildren {
  storefrontShopAccountSignInRoute: typeof storefrontShopAccountSignInRoute
  storefrontShopAccountSignUpRoute: typeof storefrontShopAccountSignUpRoute
  storefrontShopAccountVerifyEmailRoute: typeof storefrontShopAccountVerifyEmailRoute
}

const storefrontShopAccountRouteChildren: storefrontShopAccountRouteChildren = {
  storefrontShopAccountSignInRoute: storefrontShopAccountSignInRoute,
  storefrontShopAccountSignUpRoute: storefrontShopAccountSignUpRoute,
  storefrontShopAccountVerifyEmailRoute: storefrontShopAccountVerifyEmailRoute,
}

const storefrontShopAccountRouteWithChildren =
  storefrontShopAccountRoute._addFileChildren(
    storefrontShopAccountRouteChildren,
  )

interface storefrontRouteRouteChildren {
  storefrontShopRoute: typeof storefrontShopRoute
  storefrontShopAccountRoute: typeof storefrontShopAccountRouteWithChildren
  storefrontShopComposerRoute: typeof storefrontShopComposerRoute
  storefrontShopConfirmationBookingIdRoute: typeof storefrontShopConfirmationBookingIdRoute
  storefrontShopBookEntityModuleEntityIdRoute: typeof storefrontShopBookEntityModuleEntityIdRoute
  storefrontShopProductsEntityModuleEntityIdRoute: typeof storefrontShopProductsEntityModuleEntityIdRoute
}

const storefrontRouteRouteChildren: storefrontRouteRouteChildren = {
  storefrontShopRoute: storefrontShopRoute,
  storefrontShopAccountRoute: storefrontShopAccountRouteWithChildren,
  storefrontShopComposerRoute: storefrontShopComposerRoute,
  storefrontShopConfirmationBookingIdRoute:
    storefrontShopConfirmationBookingIdRoute,
  storefrontShopBookEntityModuleEntityIdRoute:
    storefrontShopBookEntityModuleEntityIdRoute,
  storefrontShopProductsEntityModuleEntityIdRoute:
    storefrontShopProductsEntityModuleEntityIdRoute,
}

const storefrontRouteRouteWithChildren = storefrontRouteRoute._addFileChildren(
  storefrontRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  storefrontRouteRoute: storefrontRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRoute,
  DocsRoute: DocsRoute,
  PayRoute: PayRoute,
  AccountantTokenRoute: AccountantTokenRoute,
  PaySessionIdRoute: PaySessionIdRoute,
  ProposalQuoteVersionIdRoute: ProposalQuoteVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>

    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
