// GENERATED by pnpm --filter operator graph:emit - do not edit.
// Recreate after changing the managed profile, package lockfile, or graph resolver.
// Compatibility boundary: managed profile boot remains snapshot-manifest based;
// self-host operator composition consumes the separate generated graph runtime module.

import { readFileSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"

import type { VoyantGraphDeploymentRequirements } from "@voyant-travel/framework/deployment-graph"
import type { ManagedProfileRuntimeDeployment } from "@voyant-travel/framework/managed-runtime"

export const GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION = "voyant.resolved-graph.v1" as const
export const GENERATED_DEPLOYMENT_GRAPH_HASH = "sha256:485c0519ec4b246a318c8db0f4012b0668060b859ca24ad9ac27f49734feac9d" as const
export const GENERATED_DEPLOYMENT_GRAPH_TARGET = "node" as const
export const GENERATED_DEPLOYMENT_GRAPH_MODE = "self-hosted" as const
export const GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH = "../deployment-graph.generated.json" as const
export const GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH = "../managed-profile.json" as const

export const GENERATED_DEPLOYMENT_GRAPH_MODULE_IDS = [
  "@voyant-travel/accommodations",
  "@voyant-travel/action-ledger",
  "@voyant-travel/availability",
  "@voyant-travel/bookings",
  "@voyant-travel/bookings#requirements",
  "@voyant-travel/catalog",
  "@voyant-travel/catalog-authoring",
  "@voyant-travel/catalog#booking-engine",
  "@voyant-travel/charters",
  "@voyant-travel/commerce",
  "@voyant-travel/cruises",
  "@voyant-travel/db",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/inventory#extras",
  "@voyant-travel/legal",
  "@voyant-travel/legal#contract-document",
  "@voyant-travel/mice",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator-settings",
  "@voyant-travel/operator#invitations",
  "@voyant-travel/operator#mcp",
  "@voyant-travel/operator#team",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/quotes",
  "@voyant-travel/realtime",
  "@voyant-travel/relationships",
  "@voyant-travel/storage",
  "@voyant-travel/storefront",
  "@voyant-travel/storefront#customer-portal",
  "@voyant-travel/storefront#payment-link",
  "@voyant-travel/storefront#verification",
  "@voyant-travel/trips",
  "@voyant-travel/workflow-runs",
] as const
export const GENERATED_DEPLOYMENT_GRAPH_PLUGIN_IDS = [
  "@voyant-travel/accommodations#content-extension",
  "@voyant-travel/action-ledger#health-extension",
  "@voyant-travel/bookings#booking-supplier-extension",
  "@voyant-travel/catalog#offers-extension",
  "@voyant-travel/commerce#booking-maintenance-extension",
  "@voyant-travel/commerce#catalog-checkout-extension",
  "@voyant-travel/cruises#content-extension",
  "@voyant-travel/distribution#channel-push-extension",
  "@voyant-travel/distribution#extension",
  "@voyant-travel/finance#booking-schedule-extension",
  "@voyant-travel/finance#booking-tax-extension",
  "@voyant-travel/finance#bookings-create-extension",
  "@voyant-travel/inventory#authoring.extension",
  "@voyant-travel/inventory#booking-extension",
  "@voyant-travel/inventory#brochure-extension",
  "@voyant-travel/inventory#content-extension",
  "@voyant-travel/mice#booking-extension",
  "@voyant-travel/plugin-netopia",
  "@voyant-travel/quotes#booking-extension",
  "@voyant-travel/quotes#proposal-extension",
  "@voyant-travel/quotes#quote-version-snapshot-extension",
] as const
export const GENERATED_DEPLOYMENT_GRAPH_PACKAGE_NAMES = [
  "@voyant-travel/accommodations",
  "@voyant-travel/action-ledger",
  "@voyant-travel/availability",
  "@voyant-travel/bookings",
  "@voyant-travel/catalog",
  "@voyant-travel/catalog-authoring",
  "@voyant-travel/charters",
  "@voyant-travel/commerce",
  "@voyant-travel/cruises",
  "@voyant-travel/db",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights",
  "@voyant-travel/framework",
  "@voyant-travel/framework-migrations",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/legal",
  "@voyant-travel/mice",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator",
  "@voyant-travel/operator-settings",
  "@voyant-travel/plugin-netopia",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/quotes",
  "@voyant-travel/realtime",
  "@voyant-travel/relationships",
  "@voyant-travel/storage",
  "@voyant-travel/storefront",
  "@voyant-travel/trips",
  "@voyant-travel/workflow-runs",
] as const

export function resolveGeneratedProfileSnapshotPath(): string {
  const fromEnv = process.env.MANAGED_PROFILE_SNAPSHOT?.trim()
  if (fromEnv) return fromEnv
  return fileURLToPath(new URL(GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH, import.meta.url))
}

export function assertGeneratedDeploymentGraphArtifact(): void {
  const graph = readGeneratedDeploymentGraph()
  if (graph.schemaVersion !== GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION) {
    throw new Error(
      `Generated deployment graph schemaVersion ${String(
        graph.schemaVersion,
      )} does not match ${GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION}`,
    )
  }
  if (graph.contentHash !== GENERATED_DEPLOYMENT_GRAPH_HASH) {
    throw new Error(
      `Generated deployment graph contentHash ${String(
        graph.contentHash,
      )} does not match ${GENERATED_DEPLOYMENT_GRAPH_HASH}`,
    )
  }
  if (graph.deployment?.target !== GENERATED_DEPLOYMENT_GRAPH_TARGET) {
    throw new Error(
      `Generated deployment graph target ${String(
        graph.deployment?.target,
      )} does not match ${GENERATED_DEPLOYMENT_GRAPH_TARGET}`,
    )
  }
  if (graph.deployment?.mode !== GENERATED_DEPLOYMENT_GRAPH_MODE) {
    throw new Error(
      `Generated deployment graph mode ${String(
        graph.deployment?.mode,
      )} does not match ${GENERATED_DEPLOYMENT_GRAPH_MODE}`,
    )
  }
  const errorDiagnostics = Array.isArray(graph.diagnostics)
    ? graph.diagnostics.filter(isErrorDiagnostic)
    : []
  if (errorDiagnostics.length > 0) {
    throw new Error(
      `Generated deployment graph contains ${errorDiagnostics.length} error diagnostic(s):\n${errorDiagnostics
        .map(formatGeneratedDiagnostic)
        .join("\n")}`,
    )
  }
}

export function resolveGeneratedDeploymentRequirements(): VoyantGraphDeploymentRequirements {
  const requirements = readGeneratedDeploymentGraph().requirements
  if (!requirements || typeof requirements !== "object" || Array.isArray(requirements)) {
    throw new Error("Generated deployment graph requirements are missing or invalid")
  }
  const candidate = requirements as { resources?: unknown }
  if (!Array.isArray(candidate.resources)) {
    throw new Error("Generated deployment graph requirements.resources must be an array")
  }
  return candidate as VoyantGraphDeploymentRequirements
}

export function resolveGeneratedRuntimeDeployment(): ManagedProfileRuntimeDeployment {
  const deployment = readGeneratedDeploymentGraph().deployment
  if (!deployment || typeof deployment !== "object" || Array.isArray(deployment)) {
    throw new Error("Generated deployment graph deployment is missing or invalid")
  }
  const candidate = deployment as { mode?: unknown; providers?: unknown }
  if (
    candidate.mode !== "local" &&
    candidate.mode !== "managed-cloud" &&
    candidate.mode !== "self-hosted"
  ) {
    throw new Error("Generated deployment graph deployment.mode is invalid")
  }
  if (!isGeneratedRecord(candidate.providers)) {
    throw new Error("Generated deployment graph deployment.providers is missing or invalid")
  }
  const providers: ManagedProfileRuntimeDeployment["providers"] = {
    database: requireGeneratedDeploymentProvider(candidate.providers, "database"),
    storage: requireGeneratedDeploymentProvider(candidate.providers, "storage"),
    cache: requireGeneratedDeploymentProvider(candidate.providers, "cache"),
    sharedState: requireGeneratedDeploymentProvider(candidate.providers, "sharedState"),
    rateLimit: requireGeneratedDeploymentProvider(candidate.providers, "rateLimit"),
    search: requireGeneratedDeploymentProvider(candidate.providers, "search"),
    email: requireGeneratedDeploymentProvider(candidate.providers, "email"),
    sms: requireGeneratedDeploymentProvider(candidate.providers, "sms"),
    auth: requireGeneratedDeploymentProvider(candidate.providers, "auth"),
    scheduledJobs: requireGeneratedDeploymentProvider(candidate.providers, "scheduledJobs"),
    workflows: requireGeneratedDeploymentProvider(candidate.providers, "workflows"),
  }
  return {
    mode: candidate.mode,
    providers,
  }
}

function requireGeneratedDeploymentProvider<
  Role extends keyof ManagedProfileRuntimeDeployment["providers"],
>(
  providers: Record<string, unknown>,
  role: Role,
): ManagedProfileRuntimeDeployment["providers"][Role] {
  const provider = providers[role]
  if (typeof provider !== "string" || provider.trim().length === 0) {
    throw new Error(
      `Generated deployment graph deployment.providers.${role} must be a non-empty string`,
    )
  }
  return provider as ManagedProfileRuntimeDeployment["providers"][Role]
}

function isGeneratedRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value)
}

function readGeneratedDeploymentGraph(): {
  schemaVersion?: unknown
  contentHash?: unknown
  deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
  requirements?: unknown
  diagnostics?: unknown
} {
  return JSON.parse(
    readFileSync(
      fileURLToPath(new URL(GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH, import.meta.url)),
      "utf8",
    ),
  ) as {
    schemaVersion?: unknown
    contentHash?: unknown
    deployment?: { target?: unknown; mode?: unknown; providers?: unknown }
    requirements?: unknown
    diagnostics?: unknown
  }
}

const isMainModule = import.meta.url === pathToFileURL(process.argv[1] ?? "").href
if (isMainModule) {
  assertGeneratedDeploymentGraphArtifact()
  const { startManagedProfileRuntime } = await import("@voyant-travel/framework/managed-runtime")
  const handle = await startManagedProfileRuntime({
    profileSnapshotPath: resolveGeneratedProfileSnapshotPath(),
    deployment: resolveGeneratedRuntimeDeployment(),
    deploymentRequirements: resolveGeneratedDeploymentRequirements(),
  })
  console.info(
    `[managed-runtime] Node runtime listening on :${handle.port} (${GENERATED_DEPLOYMENT_GRAPH_HASH})`,
  )
}

function isErrorDiagnostic(value: unknown): boolean {
  if (!value || typeof value !== "object" || Array.isArray(value) || !("severity" in value)) {
    return false
  }
  return (value as { severity?: unknown }).severity === "error"
}

function formatGeneratedDiagnostic(value: unknown): string {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "- unknown diagnostic"
  const diagnostic = value as { code?: unknown; message?: unknown; source?: unknown; facet?: unknown }
  const context = [
    typeof diagnostic.source === "string" ? `source=${diagnostic.source}` : undefined,
    typeof diagnostic.facet === "string" ? `facet=${diagnostic.facet}` : undefined,
  ]
    .filter(Boolean)
    .join(", ")
  return `- ${String(diagnostic.code ?? "UNKNOWN")}: ${String(diagnostic.message ?? "")}${
    context ? ` (${context})` : ""
  }`
}
