// GENERATED by pnpm --filter operator graph:emit - do not edit.
// Recreate after changing the managed profile, package lockfile, or graph resolver.

import { fileURLToPath, pathToFileURL } from "node:url"

import { startManagedProfileRuntime } from "@voyant-travel/framework/managed-runtime"

export const GENERATED_DEPLOYMENT_GRAPH_SCHEMA_VERSION = "voyant.resolved-graph.v1" as const
export const GENERATED_DEPLOYMENT_GRAPH_HASH = "sha256:963c397abac564cd5aea200269c5492fc9057bc35d1bfb853dbb97a796552130" as const
export const GENERATED_DEPLOYMENT_GRAPH_TARGET = "node" as const
export const GENERATED_DEPLOYMENT_GRAPH_MODE = "self-hosted" as const
export const GENERATED_DEPLOYMENT_GRAPH_ARTIFACT_PATH = "../deployment-graph.generated.json" as const
export const GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH = "../managed-profile.json" as const

export const GENERATED_DEPLOYMENT_GRAPH_MODULE_IDS = [
  "@voyant-travel/action-ledger",
  "@voyant-travel/relationships",
  "@voyant-travel/quotes",
  "@voyant-travel/operations",
  "@voyant-travel/identity",
  "@voyant-travel/distribution",
  "@voyant-travel/inventory#extras",
  "@voyant-travel/bookings#requirements",
  "@voyant-travel/commerce",
  "@voyant-travel/inventory",
  "@voyant-travel/catalog",
  "@voyant-travel/accommodations",
  "@voyant-travel/bookings",
  "@voyant-travel/finance",
  "@voyant-travel/legal",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/notifications",
  "@voyant-travel/trips",
  "@voyant-travel/flights",
  "@voyant-travel/operator-settings",
  "@voyant-travel/operator#mcp",
  "@voyant-travel/operator#catalog-booking",
  "@voyant-travel/operator#catalog-content",
  "@voyant-travel/operator#media",
  "@voyant-travel/operator#payment-link",
  "@voyant-travel/operator#contract-document",
] as const
export const GENERATED_DEPLOYMENT_GRAPH_PLUGIN_IDS = [
  "@voyant-travel/bookings#booking-supplier-extension",
  "@voyant-travel/finance#bookings-create-extension",
  "@voyant-travel/inventory#booking-extension",
  "@voyant-travel/inventory#authoring.extension",
  "@voyant-travel/quotes#booking-extension",
  "@voyant-travel/distribution#extension",
  "@voyant-travel/distribution#channel-push-extension",
  "@voyant-travel/finance#booking-tax-extension",
  "@voyant-travel/operator#booking-schedule-extension",
  "@voyant-travel/operator#quote-version-snapshot-extension",
  "@voyant-travel/operator#booking-maintenance-extension",
  "@voyant-travel/operator#action-ledger-health-extension",
  "@voyant-travel/operator#proposal-extension",
  "@voyant-travel/operator#catalog-offers-extension",
  "@voyant-travel/operator#catalog-checkout-extension",
] as const
export const GENERATED_DEPLOYMENT_GRAPH_PACKAGE_NAMES = [
  "@voyant-travel/accommodations",
  "@voyant-travel/action-ledger",
  "@voyant-travel/bookings",
  "@voyant-travel/catalog",
  "@voyant-travel/commerce",
  "@voyant-travel/distribution",
  "@voyant-travel/finance",
  "@voyant-travel/flights",
  "@voyant-travel/framework",
  "@voyant-travel/framework-migrations",
  "@voyant-travel/identity",
  "@voyant-travel/inventory",
  "@voyant-travel/legal",
  "@voyant-travel/notifications",
  "@voyant-travel/operations",
  "@voyant-travel/operator",
  "@voyant-travel/operator-settings",
  "@voyant-travel/public-document-delivery",
  "@voyant-travel/quotes",
  "@voyant-travel/relationships",
  "@voyant-travel/trips",
] as const

export function resolveGeneratedProfileSnapshotPath(): string {
  const fromEnv = process.env.MANAGED_PROFILE_SNAPSHOT?.trim()
  if (fromEnv) return fromEnv
  return fileURLToPath(new URL(GENERATED_MANAGED_PROFILE_SNAPSHOT_PATH, import.meta.url))
}

const isMainModule = import.meta.url === pathToFileURL(process.argv[1] ?? "").href
if (isMainModule) {
  const handle = await startManagedProfileRuntime({
    profileSnapshotPath: resolveGeneratedProfileSnapshotPath(),
  })
  console.info(
    `[managed-runtime] Node runtime listening on :${handle.port} (${GENERATED_DEPLOYMENT_GRAPH_HASH})`,
  )
}
