export {
  getChannelsQueryOptions,
  getProductChannelMappingsQueryOptions,
  getProductDetailMediaQueryOptions,
  getProductDetailMediaQueryOptions as getProductMediaQueryOptions,
  getProductDetailPricingCategoriesQueryOptions,
  getProductDetailPricingCategoriesQueryOptions as getPricingCategoriesQueryOptions,
  getProductDetailProductOptionsQueryOptions,
  getProductDetailProductOptionsQueryOptions as getProductOptionsQueryOptions,
  getProductRulesQueryOptions,
  getProductSlotsQueryOptions,
  type ProductDetailApi,
  type ProductDetailBreadcrumb,
  ProductDetailHostProvider,
  type ProductDetailHostValue,
  type ProductDetailMessages,
  type ProductDetailNavigation,
  ProductDetailPage,
  ProductDetailSkeleton,
  useProductDetailHost,
} from "./product-detail/index.js"
