/**
 * Pure part of the generated-OpenAPI drift check, so it can be tested without
 * running a generator.
 */

/**
 * @param {ReadonlyArray<{ file: string, before: Buffer | null, after: Buffer | null }>} snapshots
 * @returns {string[]} one line per file whose regenerated bytes differ
 */
export function driftedFiles(snapshots) {
  return snapshots.flatMap(({ file, before, after }) => {
    if (after === null) return [`${file}: the generator did not produce this file`]
    if (before === null) return [`${file}: generated but not checked in`]
    return before.equals(after) ? [] : [`${file}: checked-in document is stale`]
  })
}
