export const localizedCountriesWithRegionsEnPart1 = [
  { name: "Afghanistan", code: "AF", region: "as", slug: "afghanistan" },
  { name: "Åland Islands", code: "AX", region: "eu", slug: "aland-islands" },
  { name: "Albania", code: "AL", region: "eu", slug: "albania" },
  { name: "Algeria", code: "DZ", region: "af", slug: "algeria" },
  { name: "American Samoa", code: "AS", region: "oc", slug: "american-samoa" },
  { name: "Andorra", code: "AD", region: "eu", slug: "andorra" },
  { name: "Angola", code: "AO", region: "af", slug: "angola" },
  { name: "Anguilla", code: "AI", region: "na", slug: "anguilla" },
  { name: "Antarctica", code: "AQ", region: "an", slug: "antarctica" },
  { name: "Antigua and Barbuda", code: "AG", region: "na", slug: "antigua-and-barbuda" },
  { name: "Argentina", code: "AR", region: "sa", slug: "argentina" },
  { name: "Armenia", code: "AM", region: "as", slug: "armenia" },
  { name: "Aruba", code: "AW", region: "na", slug: "aruba" },
  { name: "Australia", code: "AU", region: "oc", slug: "australia" },
  { name: "Austria", code: "AT", region: "eu", slug: "austria" },
  { name: "Azerbaijan", code: "AZ", region: "as", slug: "azerbaijan" },
  { name: "Bahamas", code: "BS", region: "na", slug: "bahamas" },
  { name: "Bahrain", code: "BH", region: "me", slug: "bahrain" },
  { name: "Bangladesh", code: "BD", region: "as", slug: "bangladesh" },
  { name: "Barbados", code: "BB", region: "na", slug: "barbados" },
  { name: "Belarus", code: "BY", region: "eu", slug: "belarus" },
  { name: "Belgium", code: "BE", region: "eu", slug: "belgium" },
  { name: "Belize", code: "BZ", region: "na", slug: "belize" },
  { name: "Benin", code: "BJ", region: "af", slug: "benin" },
  { name: "Bermuda", code: "BM", region: "na", slug: "bermuda" },
  { name: "Bhutan", code: "BT", region: "as", slug: "bhutan" },
  { name: "Bolivia", code: "BO", region: "sa", slug: "bolivia" },
  { name: "Bosnia and Herzegovina", code: "BA", region: "eu", slug: "bosnia-and-herzegovina" },
  { name: "Botswana", code: "BW", region: "af", slug: "botswana" },
  { name: "Bouvet Island", code: "BV", region: "an", slug: "bouvet-island" },
  { name: "Brazil", code: "BR", region: "sa", slug: "brazil" },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    region: "af",
    slug: "british-indian-ocean-territory",
  },
  { name: "Brunei Darussalam", code: "BN", region: "as", slug: "brunei-darussalam" },
  { name: "Bulgaria", code: "BG", region: "eu", slug: "bulgaria" },
  { name: "Burkina Faso", code: "BF", region: "af", slug: "burkina-faso" },
  { name: "Burundi", code: "BI", region: "af", slug: "burundi" },
  { name: "Cambodia", code: "KH", region: "as", slug: "cambodia" },
  { name: "Cameroon", code: "CM", region: "af", slug: "cameroon" },
  { name: "Canada", code: "CA", region: "na", slug: "canada" },
  { name: "Cape Verde", code: "CV", region: "af", slug: "cape-verde" },
  { name: "Cayman Islands", code: "KY", region: "na", slug: "cayman-islands" },
  {
    name: "Central African Republic",
    code: "CF",
    region: "af",
    slug: "central-african-republic",
  },
  { name: "Chad", code: "TD", region: "af", slug: "chad" },
  { name: "Chile", code: "CL", region: "sa", slug: "chile" },
  { name: "China", code: "CN", region: "as", slug: "china" },
  { name: "Christmas Island", code: "CX", region: "oc", slug: "christmas-island" },
  { name: "Cocos (Keeling) Islands", code: "CC", region: "oc", slug: "cocos-keeling-islands" },
  { name: "Colombia", code: "CO", region: "sa", slug: "colombia" },
  { name: "Comoros", code: "KM", region: "af", slug: "comoros" },
  { name: "Congo", code: "CG", region: "af", slug: "congo" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    region: "af",
    slug: "congo-the-democratic-republic-of-the",
  },
  { name: "Cook Islands", code: "CK", region: "oc", slug: "cook-islands" },
  { name: "Costa Rica", code: "CR", region: "na", slug: "costa-rica" },
  { name: "Cote D'Ivoire", code: "CI", region: "af", slug: "cote-d-ivoire" },
  { name: "Croatia", code: "HR", region: "eu", slug: "croatia" },
  { name: "Cuba", code: "CU", region: "na", slug: "cuba" },
  { name: "Cyprus", code: "CY", region: "me", slug: "cyprus" },
  { name: "Czech Republic", code: "CZ", region: "eu", slug: "czech-republic" },
  { name: "Denmark", code: "DK", region: "eu", slug: "denmark" },
  { name: "Djibouti", code: "DJ", region: "af", slug: "djibouti" },
  { name: "Dominica", code: "DM", region: "na", slug: "dominica" },
  { name: "Dominican Republic", code: "DO", region: "na", slug: "dominican-republic" },
  { name: "Ecuador", code: "EC", region: "sa", slug: "ecuador" },
  { name: "Egypt", code: "EG", region: "af", slug: "egypt" },
  { name: "El Salvador", code: "SV", region: "na", slug: "el-salvador" },
  { name: "Equatorial Guinea", code: "GQ", region: "af", slug: "equatorial-guinea" },
  { name: "Eritrea", code: "ER", region: "af", slug: "eritrea" },
  { name: "Estonia", code: "EE", region: "eu", slug: "estonia" },
  { name: "Ethiopia", code: "ET", region: "af", slug: "ethiopia" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    region: "sa",
    slug: "falkland-islands-malvinas",
  },
  { name: "Faroe Islands", code: "FO", region: "eu", slug: "faroe-islands" },
  { name: "Fiji", code: "FJ", region: "oc", slug: "fiji" },
  { name: "Finland", code: "FI", region: "eu", slug: "finland" },
  { name: "France", code: "FR", region: "eu", slug: "france" },
  { name: "French Guiana", code: "GF", region: "sa", slug: "french-guiana" },
  { name: "French Polynesia", code: "PF", region: "oc", slug: "french-polynesia" },
  {
    name: "French Southern Territories",
    code: "TF",
    region: "an",
    slug: "french-southern-territories",
  },
  { name: "Gabon", code: "GA", region: "af", slug: "gabon" },
  { name: "Gambia", code: "GM", region: "af", slug: "gambia" },
  { name: "Georgia", code: "GE", region: "as", slug: "georgia" },
  { name: "Germany", code: "DE", region: "eu", slug: "germany" },
  { name: "Ghana", code: "GH", region: "af", slug: "ghana" },
  { name: "Gibraltar", code: "GI", region: "eu", slug: "gibraltar" },
  { name: "Greece", code: "GR", region: "eu", slug: "greece" },
  { name: "Greenland", code: "GL", region: "na", slug: "greenland" },
  { name: "Grenada", code: "GD", region: "na", slug: "grenada" },
  { name: "Guadeloupe", code: "GP", region: "na", slug: "guadeloupe" },
  { name: "Guam", code: "GU", region: "oc", slug: "guam" },
  { name: "Guatemala", code: "GT", region: "na", slug: "guatemala" },
  { name: "Guernsey", code: "GG", region: "eu", slug: "guernsey" },
]
