export const localizedCountriesWithRegionsEnPart3 = [
  { name: "Russian Federation", code: "RU", region: "eu", slug: "russian-federation" },
  { name: "RWANDA", code: "RW", region: "af", slug: "rwanda" },
  { name: "Saint Helena", code: "SH", region: "af", slug: "saint-helena" },
  { name: "Saint Kitts and Nevis", code: "KN", region: "na", slug: "saint-kitts-and-nevis" },
  { name: "Saint Lucia", code: "LC", region: "na", slug: "saint-lucia" },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    region: "na",
    slug: "saint-pierre-and-miquelon",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    region: "na",
    slug: "saint-vincent-and-the-grenadines",
  },
  { name: "Samoa", code: "WS", region: "oc", slug: "samoa" },
  { name: "San Marino", code: "SM", region: "eu", slug: "san-marino" },
  { name: "Sao Tome and Principe", code: "ST", region: "af", slug: "sao-tome-and-principe" },
  { name: "Saudi Arabia", code: "SA", region: "me", slug: "saudi-arabia" },
  { name: "Senegal", code: "SN", region: "af", slug: "senegal" },
  { name: "Serbia and Montenegro", code: "CS", region: "eu", slug: "serbia-and-montenegro" },
  { name: "Seychelles", code: "SC", region: "af", slug: "seychelles" },
  { name: "Sierra Leone", code: "SL", region: "af", slug: "sierra-leone" },
  { name: "Singapore", code: "SG", region: "as", slug: "singapore" },
  { name: "Slovakia", code: "SK", region: "eu", slug: "slovakia" },
  { name: "Slovenia", code: "SI", region: "eu", slug: "slovenia" },
  { name: "Solomon Islands", code: "SB", region: "oc", slug: "solomon-islands" },
  { name: "Somalia", code: "SO", region: "af", slug: "somalia" },
  { name: "South Africa", code: "ZA", region: "af", slug: "south-africa" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    region: "sa",
    slug: "south-georgia-and-the-south-sandwich-islands",
  },
  { name: "Spain", code: "ES", region: "eu", slug: "spain" },
  { name: "Sri Lanka", code: "LK", region: "as", slug: "sri-lanka" },
  { name: "Sudan", code: "SD", region: "af", slug: "sudan" },
  { name: "Suriname", code: "SR", region: "sa", slug: "suriname" },
  { name: "Svalbard and Jan Mayen", code: "SJ", region: "eu", slug: "svalbard-and-jan-mayen" },
  { name: "Swaziland", code: "SZ", region: "af", slug: "swaziland" },
  { name: "Sweden", code: "SE", region: "eu", slug: "sweden" },
  { name: "Switzerland", code: "CH", region: "eu", slug: "switzerland" },
  { name: "Syrian Arab Republic", code: "SY", region: "me", slug: "syrian-arab-republic" },
  {
    name: "Taiwan, Province of China",
    code: "TW",
    region: "as",
    slug: "taiwan-province-of-china",
  },
  { name: "Tajikistan", code: "TJ", region: "as", slug: "tajikistan" },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    region: "af",
    slug: "tanzania-united-republic-of",
  },
  { name: "Thailand", code: "TH", region: "as", slug: "thailand" },
  { name: "Timor-Leste", code: "TL", region: "as", slug: "timor-leste" },
  { name: "Togo", code: "TG", region: "af", slug: "togo" },
  { name: "Tokelau", code: "TK", region: "oc", slug: "tokelau" },
  { name: "Tonga", code: "TO", region: "oc", slug: "tonga" },
  { name: "Trinidad and Tobago", code: "TT", region: "na", slug: "trinidad-and-tobago" },
  { name: "Tunisia", code: "TN", region: "af", slug: "tunisia" },
  { name: "Turkey", code: "TR", region: "me", slug: "turkey" },
  { name: "Turkmenistan", code: "TM", region: "as", slug: "turkmenistan" },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    region: "na",
    slug: "turks-and-caicos-islands",
  },
  { name: "Tuvalu", code: "TV", region: "oc", slug: "tuvalu" },
  { name: "Uganda", code: "UG", region: "af", slug: "uganda" },
  { name: "Ukraine", code: "UA", region: "eu", slug: "ukraine" },
  { name: "United Arab Emirates", code: "AE", region: "me", slug: "united-arab-emirates" },
  { name: "United Kingdom", code: "GB", region: "eu", slug: "united-kingdom" },
  { name: "United States", code: "US", region: "na", slug: "united-states" },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    region: "oc",
    slug: "united-states-minor-outlying-islands",
  },
  { name: "Uruguay", code: "UY", region: "sa", slug: "uruguay" },
  { name: "Uzbekistan", code: "UZ", region: "as", slug: "uzbekistan" },
  { name: "Vanuatu", code: "VU", region: "oc", slug: "vanuatu" },
  { name: "Venezuela", code: "VE", region: "sa", slug: "venezuela" },
  { name: "Viet Nam", code: "VN", region: "as", slug: "viet-nam" },
  { name: "Virgin Islands, British", code: "VG", region: "na", slug: "virgin-islands-british" },
  { name: "Virgin Islands, U.S.", code: "VI", region: "na", slug: "virgin-islands-u-s" },
  { name: "Wallis and Futuna", code: "WF", region: "oc", slug: "wallis-and-futuna" },
  { name: "Western Sahara", code: "EH", region: "af", slug: "western-sahara" },
  { name: "Yemen", code: "YE", region: "me", slug: "yemen" },
  { name: "Zambia", code: "ZM", region: "af", slug: "zambia" },
  { name: "Zimbabwe", code: "ZW", region: "af", slug: "zimbabwe" },
]
