export const localizedCountriesWithRegionsEnPart2 = [
  { name: "Guinea", code: "GN", region: "af", slug: "guinea" },
  { name: "Guinea-Bissau", code: "GW", region: "af", slug: "guinea-bissau" },
  { name: "Guyana", code: "GY", region: "sa", slug: "guyana" },
  { name: "Haiti", code: "HT", region: "na", slug: "haiti" },
  {
    name: "Heard Island and Mcdonald Islands",
    code: "HM",
    region: "an",
    slug: "heard-island-and-mcdonald-islands",
  },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    region: "eu",
    slug: "holy-see-vatican-city-state",
  },
  { name: "Honduras", code: "HN", region: "na", slug: "honduras" },
  { name: "Hong Kong", code: "HK", region: "as", slug: "hong-kong" },
  { name: "Hungary", code: "HU", region: "eu", slug: "hungary" },
  { name: "Iceland", code: "IS", region: "eu", slug: "iceland" },
  { name: "India", code: "IN", region: "as", slug: "india" },
  { name: "Indonesia", code: "ID", region: "as", slug: "indonesia" },
  {
    name: "Iran, Islamic Republic Of",
    code: "IR",
    region: "me",
    slug: "iran-islamic-republic-of",
  },
  { name: "Iraq", code: "IQ", region: "me", slug: "iraq" },
  { name: "Ireland", code: "IE", region: "eu", slug: "ireland" },
  { name: "Isle of Man", code: "IM", region: "eu", slug: "isle-of-man" },
  { name: "Israel", code: "IL", region: "me", slug: "israel" },
  { name: "Italy", code: "IT", region: "eu", slug: "italy" },
  { name: "Jamaica", code: "JM", region: "na", slug: "jamaica" },
  { name: "Japan", code: "JP", region: "as", slug: "japan" },
  { name: "Jersey", code: "JE", region: "eu", slug: "jersey" },
  { name: "Jordan", code: "JO", region: "me", slug: "jordan" },
  { name: "Kazakhstan", code: "KZ", region: "as", slug: "kazakhstan" },
  { name: "Kenya", code: "KE", region: "af", slug: "kenya" },
  { name: "Kiribati", code: "KI", region: "oc", slug: "kiribati" },
  {
    name: "Korea, Democratic People’s Republic of",
    code: "KP",
    region: "as",
    slug: "korea-democratic-people-s-republic-of",
  },
  { name: "Korea, Republic of", code: "KR", region: "as", slug: "korea-republic-of" },
  { name: "Kuwait", code: "KW", region: "me", slug: "kuwait" },
  { name: "Kyrgyzstan", code: "KG", region: "as", slug: "kyrgyzstan" },
  {
    name: "Lao People’s Democratic Republic",
    code: "LA",
    region: "as",
    slug: "lao-people-s-democratic-republic",
  },
  { name: "Latvia", code: "LV", region: "eu", slug: "latvia" },
  { name: "Lebanon", code: "LB", region: "me", slug: "lebanon" },
  { name: "Lesotho", code: "LS", region: "af", slug: "lesotho" },
  { name: "Liberia", code: "LR", region: "af", slug: "liberia" },
  { name: "Libyan Arab Jamahiriya", code: "LY", region: "af", slug: "libyan-arab-jamahiriya" },
  { name: "Liechtenstein", code: "LI", region: "eu", slug: "liechtenstein" },
  { name: "Lithuania", code: "LT", region: "eu", slug: "lithuania" },
  { name: "Luxembourg", code: "LU", region: "eu", slug: "luxembourg" },
  { name: "Macao", code: "MO", region: "as", slug: "macao" },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    region: "eu",
    slug: "macedonia-the-former-yugoslav-republic-of",
  },
  { name: "Madagascar", code: "MG", region: "af", slug: "madagascar" },
  { name: "Malawi", code: "MW", region: "af", slug: "malawi" },
  { name: "Malaysia", code: "MY", region: "as", slug: "malaysia" },
  { name: "Maldives", code: "MV", region: "as", slug: "maldives" },
  { name: "Mali", code: "ML", region: "af", slug: "mali" },
  { name: "Malta", code: "MT", region: "eu", slug: "malta" },
  { name: "Marshall Islands", code: "MH", region: "oc", slug: "marshall-islands" },
  { name: "Martinique", code: "MQ", region: "na", slug: "martinique" },
  { name: "Mauritania", code: "MR", region: "af", slug: "mauritania" },
  { name: "Mauritius", code: "MU", region: "af", slug: "mauritius" },
  { name: "Mayotte", code: "YT", region: "af", slug: "mayotte" },
  { name: "Mexico", code: "MX", region: "na", slug: "mexico" },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    region: "oc",
    slug: "micronesia-federated-states-of",
  },
  { name: "Moldova, Republic of", code: "MD", region: "eu", slug: "moldova-republic-of" },
  { name: "Monaco", code: "MC", region: "eu", slug: "monaco" },
  { name: "Mongolia", code: "MN", region: "as", slug: "mongolia" },
  { name: "Montserrat", code: "MS", region: "na", slug: "montserrat" },
  { name: "Morocco", code: "MA", region: "af", slug: "morocco" },
  { name: "Mozambique", code: "MZ", region: "af", slug: "mozambique" },
  { name: "Myanmar", code: "MM", region: "as", slug: "myanmar" },
  { name: "Namibia", code: "NA", region: "af", slug: "namibia" },
  { name: "Nauru", code: "NR", region: "oc", slug: "nauru" },
  { name: "Nepal", code: "NP", region: "as", slug: "nepal" },
  { name: "Netherlands", code: "NL", region: "eu", slug: "netherlands" },
  { name: "Netherlands Antilles", code: "AN", region: "na", slug: "netherlands-antilles" },
  { name: "New Caledonia", code: "NC", region: "oc", slug: "new-caledonia" },
  { name: "New Zealand", code: "NZ", region: "oc", slug: "new-zealand" },
  { name: "Nicaragua", code: "NI", region: "na", slug: "nicaragua" },
  { name: "Niger", code: "NE", region: "af", slug: "niger" },
  { name: "Nigeria", code: "NG", region: "af", slug: "nigeria" },
  { name: "Niue", code: "NU", region: "oc", slug: "niue" },
  { name: "Norfolk Island", code: "NF", region: "oc", slug: "norfolk-island" },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    region: "oc",
    slug: "northern-mariana-islands",
  },
  { name: "Norway", code: "NO", region: "eu", slug: "norway" },
  { name: "Oman", code: "OM", region: "me", slug: "oman" },
  { name: "Pakistan", code: "PK", region: "as", slug: "pakistan" },
  { name: "Palau", code: "PW", region: "oc", slug: "palau" },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    region: "me",
    slug: "palestinian-territory-occupied",
  },
  { name: "Panama", code: "PA", region: "na", slug: "panama" },
  { name: "Papua New Guinea", code: "PG", region: "oc", slug: "papua-new-guinea" },
  { name: "Paraguay", code: "PY", region: "sa", slug: "paraguay" },
  { name: "Peru", code: "PE", region: "sa", slug: "peru" },
  { name: "Philippines", code: "PH", region: "as", slug: "philippines" },
  { name: "Pitcairn", code: "PN", region: "oc", slug: "pitcairn" },
  { name: "Poland", code: "PL", region: "eu", slug: "poland" },
  { name: "Portugal", code: "PT", region: "eu", slug: "portugal" },
  { name: "Puerto Rico", code: "PR", region: "na", slug: "puerto-rico" },
  { name: "Qatar", code: "QA", region: "me", slug: "qatar" },
  { name: "Reunion", code: "RE", region: "af", slug: "reunion" },
  { name: "Romania", code: "RO", region: "eu", slug: "romania" },
]
