export const localizedCountriesWithRegionsRoPart1 = [
  { name: "Afghanistan", code: "AF", region: "as", slug: "afghanistan" },
  { name: "Insulele Åland", code: "AX", region: "eu", slug: "insulele-aland" },
  { name: "Albania", code: "AL", region: "eu", slug: "albania" },
  { name: "Algeria", code: "DZ", region: "af", slug: "algeria" },
  { name: "Samoa Americană", code: "AS", region: "oc", slug: "samoa-americana" },
  { name: "Andorra", code: "AD", region: "eu", slug: "andorra" },
  { name: "Angola", code: "AO", region: "af", slug: "angola" },
  { name: "Anguilla", code: "AI", region: "na", slug: "anguilla" },
  { name: "Antarctica", code: "AQ", region: "an", slug: "antarctica" },
  { name: "Antigua și Barbuda", code: "AG", region: "na", slug: "antigua-si-barbuda" },
  { name: "Argentina", code: "AR", region: "sa", slug: "argentina" },
  { name: "Armenia", code: "AM", region: "as", slug: "armenia" },
  { name: "Aruba", code: "AW", region: "na", slug: "aruba" },
  { name: "Australia", code: "AU", region: "oc", slug: "australia" },
  { name: "Austria", code: "AT", region: "eu", slug: "austria" },
  { name: "Azerbaidjan", code: "AZ", region: "as", slug: "azerbaidjan" },
  { name: "Bahamas", code: "BS", region: "na", slug: "bahamas" },
  { name: "Bahrain", code: "BH", region: "me", slug: "bahrain" },
  { name: "Bangladesh", code: "BD", region: "as", slug: "bangladesh" },
  { name: "Barbados", code: "BB", region: "na", slug: "barbados" },
  { name: "Belarus", code: "BY", region: "eu", slug: "belarus" },
  { name: "Belgia", code: "BE", region: "eu", slug: "belgia" },
  { name: "Belize", code: "BZ", region: "na", slug: "belize" },
  { name: "Benin", code: "BJ", region: "af", slug: "benin" },
  { name: "Bermuda", code: "BM", region: "na", slug: "bermuda" },
  { name: "Bhutan", code: "BT", region: "as", slug: "bhutan" },
  { name: "Bolivia", code: "BO", region: "sa", slug: "bolivia" },
  { name: "Bosnia și Herțegovina", code: "BA", region: "eu", slug: "bosnia-si-hertegovina" },
  { name: "Botswana", code: "BW", region: "af", slug: "botswana" },
  { name: "Insula Bouvet", code: "BV", region: "an", slug: "insula-bouvet" },
  { name: "Brazilia", code: "BR", region: "sa", slug: "brazilia" },
  {
    name: "Teritoriul Britanic din Oceanul Indian",
    code: "IO",
    region: "af",
    slug: "teritoriul-britanic-din-oceanul-indian",
  },
  { name: "Brunei Darussalam", code: "BN", region: "as", slug: "brunei-darussalam" },
  { name: "Bulgaria", code: "BG", region: "eu", slug: "bulgaria" },
  { name: "Burkina Faso", code: "BF", region: "af", slug: "burkina-faso" },
  { name: "Burundi", code: "BI", region: "af", slug: "burundi" },
  { name: "Cambodgia", code: "KH", region: "as", slug: "cambodgia" },
  { name: "Camerun", code: "CM", region: "af", slug: "camerun" },
  { name: "Canada", code: "CA", region: "na", slug: "canada" },
  { name: "Capul Verde", code: "CV", region: "af", slug: "capul-verde" },
  { name: "Insulele Cayman", code: "KY", region: "na", slug: "insulele-cayman" },
  { name: "Republica Centrafricană", code: "CF", region: "af", slug: "republica-centrafricana" },
  { name: "Ciad", code: "TD", region: "af", slug: "ciad" },
  { name: "Chile", code: "CL", region: "sa", slug: "chile" },
  { name: "China", code: "CN", region: "as", slug: "china" },
  { name: "Insula Christmas", code: "CX", region: "oc", slug: "insula-christmas" },
  { name: "Insulele Cocos (Keeling)", code: "CC", region: "oc", slug: "insulele-cocos-keeling" },
  { name: "Columbia", code: "CO", region: "sa", slug: "columbia" },
  { name: "Comore", code: "KM", region: "af", slug: "comore" },
  { name: "Congo", code: "CG", region: "af", slug: "congo" },
  {
    name: "Congo, Republica Democrată",
    code: "CD",
    region: "af",
    slug: "congo-republica-democrata",
  },
  { name: "Insulele Cook", code: "CK", region: "oc", slug: "insulele-cook" },
  { name: "Costa Rica", code: "CR", region: "na", slug: "costa-rica" },
  { name: "Coasta de Fildeș", code: "CI", region: "af", slug: "coasta-de-fildes" },
  { name: "Croația", code: "HR", region: "eu", slug: "croatia" },
  { name: "Cuba", code: "CU", region: "na", slug: "cuba" },
  { name: "Cipru", code: "CY", region: "me", slug: "cipru" },
  { name: "Republica Cehă", code: "CZ", region: "eu", slug: "republica-ceha" },
  { name: "Danemarca", code: "DK", region: "eu", slug: "danemarca" },
  { name: "Djibouti", code: "DJ", region: "af", slug: "djibouti" },
  { name: "Dominica", code: "DM", region: "na", slug: "dominica" },
  { name: "Republica Dominicană", code: "DO", region: "na", slug: "republica-dominicana" },
  { name: "Ecuador", code: "EC", region: "sa", slug: "ecuador" },
  { name: "Egipt", code: "EG", region: "af", slug: "egipt" },
  { name: "El Salvador", code: "SV", region: "na", slug: "el-salvador" },
  { name: "Guineea Ecuatorială", code: "GQ", region: "af", slug: "guineea-ecuatoriala" },
  { name: "Eritreea", code: "ER", region: "af", slug: "eritreea" },
  { name: "Estonia", code: "EE", region: "eu", slug: "estonia" },
  { name: "Etiopia", code: "ET", region: "af", slug: "etiopia" },
  {
    name: "Insulele Falkland (Malvine)",
    code: "FK",
    region: "sa",
    slug: "insulele-falkland-malvine",
  },
  { name: "Insulele Feroe", code: "FO", region: "eu", slug: "insulele-feroe" },
  { name: "Fiji", code: "FJ", region: "oc", slug: "fiji" },
  { name: "Finlanda", code: "FI", region: "eu", slug: "finlanda" },
  { name: "Franța", code: "FR", region: "eu", slug: "franta" },
  { name: "Guyana Franceză", code: "GF", region: "sa", slug: "guyana-franceza" },
  { name: "Polinezia Franceză", code: "PF", region: "oc", slug: "polinezia-franceza" },
  {
    name: "Teritoriile Australe și Antarctice Franceze",
    code: "TF",
    region: "an",
    slug: "teritoriile-australe-si-antarctice-franceze",
  },
  { name: "Gabon", code: "GA", region: "af", slug: "gabon" },
  { name: "Gambia", code: "GM", region: "af", slug: "gambia" },
  { name: "Georgia", code: "GE", region: "as", slug: "georgia" },
  { name: "Germania", code: "DE", region: "eu", slug: "germania" },
  { name: "Ghana", code: "GH", region: "af", slug: "ghana" },
  { name: "Gibraltar", code: "GI", region: "eu", slug: "gibraltar" },
  { name: "Grecia", code: "GR", region: "eu", slug: "grecia" },
  { name: "Groenlanda", code: "GL", region: "na", slug: "groenlanda" },
  { name: "Grenada", code: "GD", region: "na", slug: "grenada" },
  { name: "Guadeloupe", code: "GP", region: "na", slug: "guadeloupe" },
  { name: "Guam", code: "GU", region: "oc", slug: "guam" },
  { name: "Guatemala", code: "GT", region: "na", slug: "guatemala" },
  { name: "Guernsey", code: "GG", region: "eu", slug: "guernsey" },
]
