export const localizedCountriesWithRegionsRoPart3 = [
  { name: "Federația Rusă", code: "RU", region: "eu", slug: "federatia-rusa" },
  { name: "Rwanda", code: "RW", region: "af", slug: "rwanda" },
  { name: "Sfânta Elena", code: "SH", region: "af", slug: "sfanta-elena" },
  { name: "Saint Kitts și Nevis", code: "KN", region: "na", slug: "saint-kitts-si-nevis" },
  { name: "Saint Lucia", code: "LC", region: "na", slug: "saint-lucia" },
  {
    name: "Saint Pierre și Miquelon",
    code: "PM",
    region: "na",
    slug: "saint-pierre-si-miquelon",
  },
  {
    name: "Saint Vincent și Grenadine",
    code: "VC",
    region: "na",
    slug: "saint-vincent-si-grenadine",
  },
  { name: "Samoa", code: "WS", region: "oc", slug: "samoa" },
  { name: "San Marino", code: "SM", region: "eu", slug: "san-marino" },
  { name: "Sao Tome și Principe", code: "ST", region: "af", slug: "sao-tome-si-principe" },
  { name: "Arabia Saudită", code: "SA", region: "me", slug: "arabia-saudita" },
  { name: "Senegal", code: "SN", region: "af", slug: "senegal" },
  { name: "Serbia și Muntenegru", code: "CS", region: "eu", slug: "serbia-si-muntenegru" },
  { name: "Seychelles", code: "SC", region: "af", slug: "seychelles" },
  { name: "Sierra Leone", code: "SL", region: "af", slug: "sierra-leone" },
  { name: "Singapore", code: "SG", region: "as", slug: "singapore" },
  { name: "Slovacia", code: "SK", region: "eu", slug: "slovacia" },
  { name: "Slovenia", code: "SI", region: "eu", slug: "slovenia" },
  { name: "Insulele Solomon", code: "SB", region: "oc", slug: "insulele-solomon" },
  { name: "Somalia", code: "SO", region: "af", slug: "somalia" },
  { name: "Africa de Sud", code: "ZA", region: "af", slug: "africa-de-sud" },
  {
    name: "Georgia de Sud și Insulele Sandwich de Sud",
    code: "GS",
    region: "sa",
    slug: "georgia-de-sud-si-insulele-sandwich-de-sud",
  },
  { name: "Spania", code: "ES", region: "eu", slug: "spania" },
  { name: "Sri Lanka", code: "LK", region: "as", slug: "sri-lanka" },
  { name: "Sudan", code: "SD", region: "af", slug: "sudan" },
  { name: "Surinam", code: "SR", region: "sa", slug: "surinam" },
  { name: "Svalbard și Jan Mayen", code: "SJ", region: "eu", slug: "svalbard-si-jan-mayen" },
  { name: "Swaziland (Eswatini)", code: "SZ", region: "af", slug: "swaziland-eswatini" },
  { name: "Suedia", code: "SE", region: "eu", slug: "suedia" },
  { name: "Elveția", code: "CH", region: "eu", slug: "elvetia" },
  { name: "Siria", code: "SY", region: "me", slug: "siria" },
  { name: "Taiwan", code: "TW", region: "as", slug: "taiwan" },
  { name: "Tadjikistan", code: "TJ", region: "as", slug: "tadjikistan" },
  { name: "Tanzania", code: "TZ", region: "af", slug: "tanzania" },
  { name: "Thailanda", code: "TH", region: "as", slug: "thailanda" },
  { name: "Timorul de Est", code: "TL", region: "as", slug: "timorul-de-est" },
  { name: "Togo", code: "TG", region: "af", slug: "togo" },
  { name: "Tokelau", code: "TK", region: "oc", slug: "tokelau" },
  { name: "Tonga", code: "TO", region: "oc", slug: "tonga" },
  { name: "Trinidad și Tobago", code: "TT", region: "na", slug: "trinidad-si-tobago" },
  { name: "Tunisia", code: "TN", region: "af", slug: "tunisia" },
  { name: "Turcia", code: "TR", region: "me", slug: "turcia" },
  { name: "Turkmenistan", code: "TM", region: "as", slug: "turkmenistan" },
  {
    name: "Insulele Turks și Caicos",
    code: "TC",
    region: "na",
    slug: "insulele-turks-si-caicos",
  },
  { name: "Tuvalu", code: "TV", region: "oc", slug: "tuvalu" },
  { name: "Uganda", code: "UG", region: "af", slug: "uganda" },
  { name: "Ucraina", code: "UA", region: "eu", slug: "ucraina" },
  { name: "Emiratele Arabe Unite", code: "AE", region: "me", slug: "emiratele-arabe-unite" },
  { name: "Regatul Unit", code: "GB", region: "eu", slug: "regatul-unit" },
  { name: "Statele Unite", code: "US", region: "na", slug: "statele-unite" },
  {
    name: "Insulele Minore Îndepărtate ale Statelor Unite",
    code: "UM",
    region: "oc",
    slug: "insulele-minore-indepartate-ale-statelor-unite",
  },
  { name: "Uruguay", code: "UY", region: "sa", slug: "uruguay" },
  { name: "Uzbekistan", code: "UZ", region: "as", slug: "uzbekistan" },
  { name: "Vanuatu", code: "VU", region: "oc", slug: "vanuatu" },
  { name: "Venezuela", code: "VE", region: "sa", slug: "venezuela" },
  { name: "Vietnam", code: "VN", region: "as", slug: "vietnam" },
  {
    name: "Insulele Virgine Britanice",
    code: "VG",
    region: "na",
    slug: "insulele-virgine-britanice",
  },
  {
    name: "Insulele Virgine Americane",
    code: "VI",
    region: "na",
    slug: "insulele-virgine-americane",
  },
  { name: "Wallis și Futuna", code: "WF", region: "oc", slug: "wallis-si-futuna" },
  { name: "Sahara Occidentală", code: "EH", region: "af", slug: "sahara-occidentala" },
  { name: "Yemen", code: "YE", region: "me", slug: "yemen" },
  { name: "Zambia", code: "ZM", region: "af", slug: "zambia" },
  { name: "Zimbabwe", code: "ZW", region: "af", slug: "zimbabwe" },
]
