export const localizedCountriesWithRegionsRoPart2 = [
  { name: "Guineea", code: "GN", region: "af", slug: "guineea" },
  { name: "Guineea-Bissau", code: "GW", region: "af", slug: "guineea-bissau" },
  { name: "Guyana", code: "GY", region: "sa", slug: "guyana" },
  { name: "Haiti", code: "HT", region: "na", slug: "haiti" },
  {
    name: "Insula Heard și Insulele McDonald",
    code: "HM",
    region: "an",
    slug: "insula-heard-si-insulele-mcdonald",
  },
  {
    name: "Sfântul Scaun (Statul Vatican)",
    code: "VA",
    region: "eu",
    slug: "sfantul-scaun-statul-vatican",
  },
  { name: "Honduras", code: "HN", region: "na", slug: "honduras" },
  { name: "Hong Kong", code: "HK", region: "as", slug: "hong-kong" },
  { name: "Ungaria", code: "HU", region: "eu", slug: "ungaria" },
  { name: "Islanda", code: "IS", region: "eu", slug: "islanda" },
  { name: "India", code: "IN", region: "as", slug: "india" },
  { name: "Indonezia", code: "ID", region: "as", slug: "indonezia" },
  { name: "Iran", code: "IR", region: "me", slug: "iran" },
  { name: "Irak", code: "IQ", region: "me", slug: "irak" },
  { name: "Irlanda", code: "IE", region: "eu", slug: "irlanda" },
  { name: "Insula Man", code: "IM", region: "eu", slug: "insula-man" },
  { name: "Israel", code: "IL", region: "me", slug: "israel" },
  { name: "Italia", code: "IT", region: "eu", slug: "italia" },
  { name: "Jamaica", code: "JM", region: "na", slug: "jamaica" },
  { name: "Japonia", code: "JP", region: "as", slug: "japonia" },
  { name: "Jersey", code: "JE", region: "eu", slug: "jersey" },
  { name: "Iordania", code: "JO", region: "me", slug: "iordania" },
  { name: "Kazahstan", code: "KZ", region: "as", slug: "kazahstan" },
  { name: "Kenya", code: "KE", region: "af", slug: "kenya" },
  { name: "Kiribati", code: "KI", region: "oc", slug: "kiribati" },
  { name: "Coreea de Nord", code: "KP", region: "as", slug: "coreea-de-nord" },
  { name: "Coreea de Sud", code: "KR", region: "as", slug: "coreea-de-sud" },
  { name: "Kuweit", code: "KW", region: "me", slug: "kuweit" },
  { name: "Kârgâzstan", code: "KG", region: "as", slug: "kargazstan" },
  { name: "Laos", code: "LA", region: "as", slug: "laos" },
  { name: "Letonia", code: "LV", region: "eu", slug: "letonia" },
  { name: "Liban", code: "LB", region: "me", slug: "liban" },
  { name: "Lesotho", code: "LS", region: "af", slug: "lesotho" },
  { name: "Liberia", code: "LR", region: "af", slug: "liberia" },
  { name: "Libia", code: "LY", region: "af", slug: "libia" },
  { name: "Liechtenstein", code: "LI", region: "eu", slug: "liechtenstein" },
  { name: "Lituania", code: "LT", region: "eu", slug: "lituania" },
  { name: "Luxemburg", code: "LU", region: "eu", slug: "luxemburg" },
  { name: "Macao", code: "MO", region: "as", slug: "macao" },
  { name: "Macedonia de Nord", code: "MK", region: "eu", slug: "macedonia-de-nord" },
  { name: "Madagascar", code: "MG", region: "af", slug: "madagascar" },
  { name: "Malawi", code: "MW", region: "af", slug: "malawi" },
  { name: "Malaezia", code: "MY", region: "as", slug: "malaezia" },
  { name: "Maldive", code: "MV", region: "as", slug: "maldive" },
  { name: "Mali", code: "ML", region: "af", slug: "mali" },
  { name: "Malta", code: "MT", region: "eu", slug: "malta" },
  { name: "Insulele Marshall", code: "MH", region: "oc", slug: "insulele-marshall" },
  { name: "Martinica", code: "MQ", region: "na", slug: "martinica" },
  { name: "Mauritania", code: "MR", region: "af", slug: "mauritania" },
  { name: "Mauritius", code: "MU", region: "af", slug: "mauritius" },
  { name: "Mayotte", code: "YT", region: "af", slug: "mayotte" },
  { name: "Mexic", code: "MX", region: "na", slug: "mexic" },
  { name: "Micronezia", code: "FM", region: "oc", slug: "micronezia" },
  { name: "Republica Moldova", code: "MD", region: "eu", slug: "republica-moldova" },
  { name: "Monaco", code: "MC", region: "eu", slug: "monaco" },
  { name: "Mongolia", code: "MN", region: "as", slug: "mongolia" },
  { name: "Montserrat", code: "MS", region: "na", slug: "montserrat" },
  { name: "Maroc", code: "MA", region: "af", slug: "maroc" },
  { name: "Mozambic", code: "MZ", region: "af", slug: "mozambic" },
  { name: "Myanmar", code: "MM", region: "as", slug: "myanmar" },
  { name: "Namibia", code: "NA", region: "af", slug: "namibia" },
  { name: "Nauru", code: "NR", region: "oc", slug: "nauru" },
  { name: "Nepal", code: "NP", region: "as", slug: "nepal" },
  { name: "Țările de Jos", code: "NL", region: "eu", slug: "tarile-de-jos" },
  { name: "Antilele Olandeze", code: "AN", region: "na", slug: "antilele-olandeze" },
  { name: "Noua Caledonie", code: "NC", region: "oc", slug: "noua-caledonie" },
  { name: "Noua Zeelandă", code: "NZ", region: "oc", slug: "noua-zeelanda" },
  { name: "Nicaragua", code: "NI", region: "na", slug: "nicaragua" },
  { name: "Niger", code: "NE", region: "af", slug: "niger" },
  { name: "Nigeria", code: "NG", region: "af", slug: "nigeria" },
  { name: "Niue", code: "NU", region: "oc", slug: "niue" },
  { name: "Insula Norfolk", code: "NF", region: "oc", slug: "insula-norfolk" },
  {
    name: "Insulele Marianei de Nord",
    code: "MP",
    region: "oc",
    slug: "insulele-marianei-de-nord",
  },
  { name: "Norvegia", code: "NO", region: "eu", slug: "norvegia" },
  { name: "Oman", code: "OM", region: "me", slug: "oman" },
  { name: "Pakistan", code: "PK", region: "as", slug: "pakistan" },
  { name: "Palau", code: "PW", region: "oc", slug: "palau" },
  {
    name: "Teritoriul Palestinian Ocupat",
    code: "PS",
    region: "me",
    slug: "teritoriul-palestinian-ocupat",
  },
  { name: "Panama", code: "PA", region: "na", slug: "panama" },
  { name: "Papua Noua Guinee", code: "PG", region: "oc", slug: "papua-noua-guinee" },
  { name: "Paraguay", code: "PY", region: "sa", slug: "paraguay" },
  { name: "Peru", code: "PE", region: "sa", slug: "peru" },
  { name: "Filipine", code: "PH", region: "as", slug: "filipine" },
  { name: "Pitcairn", code: "PN", region: "oc", slug: "pitcairn" },
  { name: "Polonia", code: "PL", region: "eu", slug: "polonia" },
  { name: "Portugalia", code: "PT", region: "eu", slug: "portugalia" },
  { name: "Puerto Rico", code: "PR", region: "na", slug: "puerto-rico" },
  { name: "Qatar", code: "QA", region: "me", slug: "qatar" },
  { name: "Réunion", code: "RE", region: "af", slug: "reunion" },
  { name: "Romania", code: "RO", region: "eu", slug: "romania" },
]
