import type { LinkableDefinition, Module } from "@voyantjs/core"
import type { HonoModule } from "@voyantjs/hono/module"

import { productRoutes } from "./routes.js"
import { publicProductRoutes } from "./routes-public.js"

export { productsBookingExtension } from "./booking-extension.js"
export {
  emitProductContentChanged,
  PRODUCT_CONTENT_CHANGED_EVENT,
  type ProductContentChangedEvent,
} from "./events.js"
export type { ProductRoutes } from "./routes.js"
export type { PublicProductRoutes } from "./routes-public.js"
export { publicProductRoutes } from "./routes-public.js"
export { productsService } from "./service.js"
export { catalogProductsService } from "./service-catalog.js"
export { publicProductsService } from "./service-public.js"
export {
  createBasicPdfProductBrochurePrinter,
  createCloudflareBrowserProductBrochurePrinter,
  createCloudflareBrowserProductBrochurePrinterFromEnv,
  createDefaultProductBrochureTemplate,
  type GenerateAndStoreProductBrochureOptions,
  generateAndStoreProductBrochure,
  loadProductBrochureTemplateContext,
  type ProductBrochurePrinter,
  type ProductBrochureTemplateDefinition,
  renderProductBrochureTemplate,
} from "./tasks/index.js"

export const productLinkable: LinkableDefinition = {
  module: "products",
  entity: "product",
  table: "products",
  idPrefix: "prod",
}

export const productsModule: Module = {
  name: "products",
  linkable: {
    product: productLinkable,
  },
}

export const productsHonoModule: HonoModule = {
  module: productsModule,
  adminRoutes: productRoutes,
  publicRoutes: publicProductRoutes,
  routes: productRoutes,
}

export type {
  NewOptionUnit,
  NewOptionUnitTranslation,
  NewProduct,
  NewProductActivationSetting,
  NewProductCapability,
  NewProductCategory,
  NewProductDay,
  NewProductDayService,
  NewProductDayServiceTranslation,
  NewProductDayTranslation,
  NewProductDeliveryFormat,
  NewProductFaq,
  NewProductFeature,
  NewProductItinerary,
  NewProductItineraryTranslation,
  NewProductLocation,
  NewProductMedia,
  NewProductNote,
  NewProductOption,
  NewProductOptionTranslation,
  NewProductTag,
  NewProductTicketSetting,
  NewProductTranslation,
  NewProductType,
  NewProductVersion,
  NewProductVisibilitySetting,
  OptionUnit,
  OptionUnitTranslation,
  Product,
  ProductActivationSetting,
  ProductCapability,
  ProductCategory,
  ProductDay,
  ProductDayService,
  ProductDayServiceTranslation,
  ProductDayTranslation,
  ProductDeliveryFormat,
  ProductFaq,
  ProductFeature,
  ProductItinerary,
  ProductItineraryTranslation,
  ProductLocation,
  ProductMedia,
  ProductNote,
  ProductOption,
  ProductOptionTranslation,
  ProductTag,
  ProductTicketSetting,
  ProductTranslation,
  ProductType,
  ProductVersion,
  ProductVisibilitySetting,
} from "./schema.js"
export {
  destinations,
  destinationTranslations,
  optionUnits,
  optionUnitTranslations,
  productActivationSettings,
  productCapabilities,
  productCategories,
  productCategoryProducts,
  productDayServices,
  productDayServiceTranslations,
  productDays,
  productDayTranslations,
  productDeliveryFormats,
  productDestinations,
  productFaqs,
  productFeatures,
  productItineraries,
  productItineraryTranslations,
  productLocations,
  productMedia,
  productMediaTypeEnum,
  productNotes,
  productOptions,
  productOptionTranslations,
  products,
  productTagProducts,
  productTags,
  productTicketSettings,
  productTranslations,
  productTypes,
  productVersions,
  productVisibilitySettings,
} from "./schema.js"
export {
  dayServiceTranslationListQuerySchema,
  dayTranslationListQuerySchema,
  duplicateItinerarySchema,
  insertDaySchema,
  insertDayServiceSchema,
  insertDayServiceTranslationSchema,
  insertDayTranslationSchema,
  insertItinerarySchema,
  insertItineraryTranslationSchema,
  insertOptionUnitSchema,
  insertOptionUnitTranslationSchema,
  insertProductActivationSettingSchema,
  insertProductCapabilitySchema,
  insertProductCategorySchema,
  insertProductDeliveryFormatSchema,
  insertProductFaqSchema,
  insertProductFeatureSchema,
  insertProductLocationSchema,
  insertProductMediaSchema,
  insertProductNoteSchema,
  insertProductOptionSchema,
  insertProductOptionTranslationSchema,
  insertProductSchema,
  insertProductTagSchema,
  insertProductTicketSettingSchema,
  insertProductTranslationSchema,
  insertProductTypeSchema,
  insertProductVisibilitySettingSchema,
  insertVersionSchema,
  itineraryTranslationListQuerySchema,
  optionUnitListQuerySchema,
  optionUnitTranslationListQuerySchema,
  productActivationSettingListQuerySchema,
  productCapabilityListQuerySchema,
  productCategoryListQuerySchema,
  productDeliveryFormatListQuerySchema,
  productFaqListQuerySchema,
  productFeatureListQuerySchema,
  productListQuerySchema,
  productLocationListQuerySchema,
  productMediaListQuerySchema,
  productOptionListQuerySchema,
  productOptionTranslationListQuerySchema,
  productTagListQuerySchema,
  productTicketSettingListQuerySchema,
  productTranslationListQuerySchema,
  productTypeListQuerySchema,
  productVisibilitySettingListQuerySchema,
  reorderProductMediaSchema,
  selectProductSchema,
  updateDaySchema,
  updateDayServiceSchema,
  updateDayServiceTranslationSchema,
  updateDayTranslationSchema,
  updateItinerarySchema,
  updateItineraryTranslationSchema,
  updateOptionUnitSchema,
  updateOptionUnitTranslationSchema,
  updateProductActivationSettingSchema,
  updateProductCapabilitySchema,
  updateProductCategorySchema,
  updateProductDeliveryFormatSchema,
  updateProductFaqSchema,
  updateProductFeatureSchema,
  updateProductLocationSchema,
  updateProductMediaSchema,
  updateProductOptionSchema,
  updateProductOptionTranslationSchema,
  updateProductSchema,
  updateProductTagSchema,
  updateProductTicketSettingSchema,
  updateProductTranslationSchema,
  updateProductTypeSchema,
  updateProductVisibilitySettingSchema,
  upsertProductBrochureSchema,
} from "./validation.js"
export type {
  CatalogSearchDocument,
  CatalogSearchDocumentListQuery,
  CatalogSearchDocumentListResponse,
  LocalizedCatalogProductDetail,
  LocalizedCatalogProductSummary,
} from "./validation-catalog.js"
export {
  catalogSearchDocumentListQuerySchema,
  catalogSearchDocumentListResponseSchema,
  catalogSearchDocumentSchema,
  localizedCatalogProductDetailSchema,
  localizedCatalogProductSummarySchema,
} from "./validation-catalog.js"
export {
  publicCatalogDestinationListQuerySchema,
  publicCatalogDestinationListResponseSchema,
  publicCatalogDestinationSchema,
} from "./validation-public.js"
